import React, { useState, useEffect, useRef } from 'react';
import ScrollableTabContainer from './ScrollableTabContainer';
import { motion, AnimatePresence } from 'motion/react';
import { 
  X, Send, Bot, User, Loader2, ArrowRight, CheckCircle2,
  Palette, Link as LinkIcon, FileText, SearchCheck, Utensils, Contact,
  Smartphone, Megaphone, Check, Zap
} from 'lucide-react';
import { auth, db } from '../lib/firebase';
import { signInAnonymously } from 'firebase/auth';
import { doc, setDoc } from 'firebase/firestore';
import { playAudioSound } from '../utils/audioFeedback';
import { QRProject } from '../types';
import { useTranslation } from '../utils/i18n';

interface AIAssistantWidgetProps {
  activeTab: string;
  setActiveTab: (tab: any) => void;
  onNavigate: (path: string) => void;
  currentProject?: Partial<QRProject>;
  onUpdateProject?: (project: any) => void;
}

interface ChatMessage {
  id: string;
  sender: 'user' | 'assistant';
  text: string;
  status?: 'loading' | 'success' | 'error';
  category?: string;
  customType?: 'color-palette' | 'utm-builder' | 'vcard-opt' | 'diagnostics';
  customData?: any;
}

// Preset Color Palettes generated by AI Co-Pilot
const AI_COLOR_PALETTES = [
  {
    id: 'palette-slate-indigo',
    name: 'Modern Slate & Indigo',
    desc: 'High contrast, clean corporate look with linear gradient',
    fgColor: '#0f172a',
    bgColor: '#f8fafc',
    gradientType: 'linear' as const,
    gradientColor: '#4f46e5',
    eyeTopLeft: '#4f46e5',
    tags: ['Popular', 'High Contrast']
  },
  {
    id: 'palette-luxury-gold',
    name: 'Luxury Midnight & Amber Gold',
    desc: 'Deep radial glow ideal for VIP events & menus',
    fgColor: '#1e1b4b',
    bgColor: '#ffffff',
    gradientType: 'radial' as const,
    gradientColor: '#d97706',
    eyeTopLeft: '#d97706',
    tags: ['Luxury', 'VIP']
  },
  {
    id: 'palette-eco-emerald',
    name: 'Eco Emerald & Fresh Mint',
    desc: 'Vibrant organic colors for retail & sustainability',
    fgColor: '#064e3b',
    bgColor: '#f0fdf4',
    gradientType: 'linear' as const,
    gradientColor: '#10b981',
    eyeTopLeft: '#059669',
    tags: ['Eco', 'Fresh']
  },
  {
    id: 'palette-neon-sunset',
    name: 'Cyber Neon Sunset',
    desc: 'Eye-catching purple-pink gradient for campaigns',
    fgColor: '#2e1065',
    bgColor: '#faf5ff',
    gradientType: 'radial' as const,
    gradientColor: '#a855f7',
    eyeTopLeft: '#ec4899',
    tags: ['Creative', 'Bold']
  }
];

const CATEGORY_QUICK_COMMANDS = [
  { label: 'Create Restaurant Campaign', desc: 'Generate a digital, multi-language QR menu layout', icon: Utensils, category: 'restaurant-menus' },
  { label: 'Create Business Card', desc: 'Design a sleek digital vCard profile with action links', icon: Contact, category: 'business-cards' },
  { label: 'Create Landing Page', desc: 'Generate a gorgeous, mobile-responsive promo page', icon: Smartphone, category: 'landing-pages' },
  { label: 'Create Event', desc: 'Build an RSVP campaign tracker with scanning analytics', icon: Megaphone, category: 'campaigns' },
  { label: 'Create PDF Share', desc: 'Upload and configure a tracking QR download page', icon: FileText, category: 'pdf-sharing' }
];

export default function AIAssistantWidget({
  activeTab,
  setActiveTab,
  onNavigate,
  currentProject,
  onUpdateProject
}: AIAssistantWidgetProps) {
  const { t } = useTranslation();
  const [isOpen, setIsOpen] = useState(false);
  const [hasOpened, setHasOpened] = useState(() => {
    try {
      return localStorage.getItem('qr_has_opened_ai_assistant') === 'true';
    } catch {
      return false;
    }
  });
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'welcome',
      sender: 'assistant',
      text: "Hello! I am your AI Workspace Assistant. I can suggest brand color palettes, format UTM tracking links, optimize vCard / menu content, run scannability diagnostics, or build complete campaign layouts in real time!"
    }
  ]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [currentStep, setCurrentStep] = useState('');
  const [appliedItems, setAppliedItems] = useState<{ [key: string]: boolean }>({});
  
  // Custom UTM Builder State inside AI Assistant
  const [utmSource, setUtmSource] = useState('qr_code');
  const [utmMedium, setUtmMedium] = useState('offline_print');
  const [utmCampaign, setUtmCampaign] = useState('ai_promo_2026');

  const chatEndRef = useRef<HTMLDivElement>(null);

  // Close drawer when pressing ESC key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        setIsOpen(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen]);

  useEffect(() => {
    if (chatEndRef.current && isOpen) {
      chatEndRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [messages, isLoading, isOpen]);

  // Direct Apply to QR Generator state handler
  const handleApplyToGenerator = (
    updatePayload: any,
    itemKey: string,
    successMessage: string
  ) => {
    // 1. Invoke callback prop
    if (onUpdateProject) {
      onUpdateProject((prev: any) => {
        const prevDesign = prev?.design || {};
        const incomingDesign = updatePayload.design || {};
        return {
          ...prev,
          ...updatePayload,
          design: {
            ...prevDesign,
            ...incomingDesign
          }
        };
      });
    }

    // 2. Dispatch global event
    window.dispatchEvent(new CustomEvent('apply-qr-ai-config', { detail: updatePayload }));

    // 3. Play audio feedback
    playAudioSound('generate');

    // 4. Mark item as applied
    setAppliedItems(prev => ({ ...prev, [itemKey]: true }));

    // 5. Append confirmation message to chat thread
    setMessages(prev => [
      ...prev,
      {
        id: `confirm-${Date.now()}`,
        sender: 'assistant',
        text: `✅ ${successMessage}`,
        status: 'success'
      }
    ]);
  };

  const saveGeneratedPayload = async (category: string, payload: any) => {
    let userId = auth.currentUser?.uid;
    if (!userId) {
      try {
        const anon = await signInAnonymously(auth);
        userId = anon.user.uid;
      } catch (e) {
        console.warn('Anon auth notice:', e);
      }
    }

    if (userId) {
      try {
        if (category === 'restaurant-menus') {
          await setDoc(doc(db, 'restaurant_menus', payload.id), { ...payload, userId });
        } else if (category === 'business-cards') {
          await setDoc(doc(db, 'business_cards', payload.id), { ...payload, userId });
        } else if (category === 'pdf-sharing') {
          await setDoc(doc(db, 'pdf_shares', payload.id), { ...payload, userId });
        } else if (category === 'campaigns') {
          await setDoc(doc(db, 'projects', payload.id), {
            id: payload.id,
            name: payload.name,
            type: 'url',
            content: 'https://www.freeqrbarcodes.com',
            trackingEnabled: true,
            createdAt: new Date().toISOString(),
            userId
          });
        } else if (category === 'landing-pages') {
          await setDoc(doc(db, 'landingPages', payload.id), { ...payload, userId });
        }
      } catch (err) {
        console.error('Error saving AI generated payload to Firestore:', err);
      }
    }

    window.dispatchEvent(new Event('qr-marketing-data-updated'));
    window.dispatchEvent(new Event('projects-changed'));
  };

  // Quick Action: Suggest Color Palette
  const handleTriggerColorPalettes = () => {
    playAudioSound('preview');
    setMessages(prev => [
      ...prev,
      {
        id: `user-colors-${Date.now()}`,
        sender: 'user',
        text: "🎨 Suggest Brand Color Palettes"
      },
      {
        id: `asst-colors-${Date.now()}`,
        sender: 'assistant',
        text: "Here are 4 hand-crafted, high-contrast brand color palettes optimized for maximum QR code scannability and visual impact:",
        customType: 'color-palette'
      }
    ]);
  };

  // Quick Action: UTM Link Builder
  const handleTriggerUTM = () => {
    playAudioSound('preview');
    setMessages(prev => [
      ...prev,
      {
        id: `user-utm-${Date.now()}`,
        sender: 'user',
        text: "🔗 Add UTM Tracking Parameters"
      },
      {
        id: `asst-utm-${Date.now()}`,
        sender: 'assistant',
        text: "I can attach Google Analytics tracking parameters to your destination URL so you can monitor offline print performance in your analytics suite:",
        customType: 'utm-builder'
      }
    ]);
  };

  // Quick Action: Optimize vCard / Menu
  const handleTriggerTextOptimization = () => {
    playAudioSound('preview');
    const isMenu = activeTab === 'menu';
    const sampleVCard = `BEGIN:VCARD\nVERSION:3.0\nN:Rivera;Alex;;;\nFN:Alex Rivera\nTITLE:Principal Creative Director\nORG:Apex Brand Strategy Group\nTEL;TYPE=CELL,VOICE:+15550192834\nEMAIL:alex.rivera@apexgroup.com\nURL:https://apexgroup.com\nEND:VCARD`;
    const sampleMenuText = `🍔 THE ARTISAN BISTRO - DIGITAL QR MENU\n• Truffle Wagyu Burger - $18.50\n• Wild Mushroom Risotto - $22.00\n• Organic Matcha Latte - $6.50\nScan or click to view full dietary options & order online!`;

    setMessages(prev => [
      ...prev,
      {
        id: `user-vcard-${Date.now()}`,
        sender: 'user',
        text: isMenu ? "📄 Optimize Text for Digital Restaurant Menu" : "📄 Optimize Text for Digital vCard Profile"
      },
      {
        id: `asst-vcard-${Date.now()}`,
        sender: 'assistant',
        text: isMenu
          ? "Here is a clean, structured text optimization for your digital restaurant menu:"
          : "Here is a standard, error-free vCard contact payload ready for instant smartphone import:",
        customType: 'vcard-opt',
        customData: {
          textPayload: isMenu ? sampleMenuText : sampleVCard,
          type: isMenu ? 'menu' : 'vcard'
        }
      }
    ]);
  };

  // Quick Action: Scan Diagnostics & Troubleshooting
  const handleTriggerDiagnostics = () => {
    playAudioSound('preview');

    const design: any = currentProject?.design || {};
    const fg = design.fgColor || '#000000';
    const bg = design.bgColor || '#ffffff';
    const ecl = design.errorCorrectionLevel || 'M';
    const margin = design.margin ?? 20;
    const logoScale = design.logoScale ?? 0.18;

    // Evaluate basic scannability health
    const isEclHigh = ecl === 'Q' || ecl === 'H';
    const isMarginSafe = margin >= 10;
    const isLogoSafe = logoScale <= 0.22;
    
    let score = 85;
    if (isEclHigh) score += 10;
    if (isMarginSafe) score += 5;
    if (!isLogoSafe) score -= 15;

    setMessages(prev => [
      ...prev,
      {
        id: `user-diag-${Date.now()}`,
        sender: 'user',
        text: "🔍 Run Scan Diagnostics & Troubleshooting Check"
      },
      {
        id: `asst-diag-${Date.now()}`,
        sender: 'assistant',
        text: `Diagnostic Audit Complete for active project. Scannability Rating: ${score}%`,
        customType: 'diagnostics',
        customData: {
          score,
          fg,
          bg,
          ecl,
          margin,
          logoScale,
          isEclHigh,
          isMarginSafe,
          isLogoSafe
        }
      }
    ]);
  };

  const handleCommandSubmit = async (promptText: string) => {
    if (!promptText.trim()) return;

    playAudioSound('preview');

    const userMsg: ChatMessage = {
      id: `user-${Date.now()}`,
      sender: 'user',
      text: promptText
    };

    setMessages(prev => [...prev, userMsg]);
    setInputValue('');
    setIsLoading(true);
    setCurrentStep('Analyzing campaign requirements...');

    const generationSteps = [
      'Applying premium brand palettes...',
      'Structuring layout and visual blocks...',
      'Deploying secure schema routing...',
      'Finalizing high-contrast asset configurations...'
    ];

    let stepIndex = 0;
    const interval = setInterval(() => {
      if (stepIndex < generationSteps.length) {
        setCurrentStep(generationSteps[stepIndex]);
        stepIndex++;
      }
    }, 1100);

    try {
      const response = await fetch('/api/ai/assistant', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: promptText,
          userId: auth.currentUser?.uid || '',
          locale: 'en'
        })
      });

      const data = await response.json();
      clearInterval(interval);

      if (data && data.category && data.payload) {
        const { category, payload, assistantMessage } = data;

        await saveGeneratedPayload(category, payload);
        playAudioSound('generate');

        setMessages(prev => [...prev, {
          id: `assistant-${Date.now()}`,
          sender: 'assistant',
          text: assistantMessage || `Perfect! Your campaign has been automatically generated in your workspace.`,
          status: 'success',
          category
        }]);

        setTimeout(() => {
          if (category === 'restaurant-menus') {
            setActiveTab('menu');
          } else if (category === 'business-cards') {
            setActiveTab('card');
          } else if (category === 'pdf-sharing') {
            setActiveTab('pdf');
          } else if (category === 'landing-pages' || category === 'campaigns') {
            onNavigate('/marketing-platform');
          }
        }, 1500);

      } else {
        throw new Error('Invalid schema format received');
      }

    } catch (err) {
      clearInterval(interval);
      console.error(err);
      setMessages(prev => [...prev, {
        id: `assistant-err-${Date.now()}`,
        sender: 'assistant',
        text: "I analyzed your request. Please select one of the core quick tools below or try another prompt!",
        status: 'error'
      }]);
    } finally {
      setIsLoading(false);
      setCurrentStep('');
    }
  };

  // Helper to construct current UTM URL
  const buildCurrentUtmUrl = () => {
    const baseUrl = currentProject?.originalUrl || currentProject?.content || 'https://www.freeqrbarcodes.com/promo';
    try {
      const u = new URL(baseUrl.startsWith('http') ? baseUrl : `https://${baseUrl}`);
      u.searchParams.set('utm_source', utmSource.trim() || 'qr_code');
      u.searchParams.set('utm_medium', utmMedium.trim() || 'offline_print');
      u.searchParams.set('utm_campaign', utmCampaign.trim() || 'ai_promo');
      return u.toString();
    } catch {
      return `${baseUrl}?utm_source=${encodeURIComponent(utmSource)}&utm_medium=${encodeURIComponent(utmMedium)}&utm_campaign=${encodeURIComponent(utmCampaign)}`;
    }
  };

  return (
    <>
      {/* 1. Floating Trigger Button (Positioned vertically separated from reCAPTCHA badge & MobileNav) */}
      <div className="ai-assistant-floating-container" id="ai-assistant-floating-wrapper">
        <AnimatePresence>
          {!isOpen && (
            <motion.button
              id="ai-assistant-floating-trigger"
              initial={{ scale: 0, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0, opacity: 0 }}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={() => {
                playAudioSound('preview');
                try {
                  localStorage.setItem('qr_has_opened_ai_assistant', 'true');
                } catch {}
                setHasOpened(true);
                setIsOpen(true);
              }}
              aria-label="Open AI Workspace Assistant"
              className="flex items-center gap-2.5 px-4 py-3 bg-gradient-to-r from-indigo-600 via-indigo-700 to-violet-700 hover:from-indigo-700 hover:to-violet-800 text-white rounded-full shadow-xl hover:shadow-2xl font-bold text-xs tracking-wide transition-all cursor-pointer border border-indigo-400/30 group"
            >
              <div className="relative">
                <Zap className="w-4 h-4 animate-pulse text-amber-300" />
                {!hasOpened && (
                  <span className="absolute -top-1 -right-1 w-2 h-2 bg-emerald-400 rounded-full animate-ping" />
                )}
              </div>
              <span>{t('ai.buttonLabel', 'AI Assistant')}</span>
            </motion.button>
          )}
        </AnimatePresence>
      </div>

      {/* 2. Slide-Over Side Drawer & Backdrop Overlay */}
      <AnimatePresence>
        {isOpen && (
          <>
            {/* Backdrop Overlay */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setIsOpen(false)}
              className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs z-40"
            />

            {/* Slide-over Drawer Container */}
            <motion.div
              id="ai-assistant-slide-drawer"
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 28, stiffness: 320 }}
              className="fixed inset-y-0 right-0 rtl:right-auto rtl:left-0 z-50 w-full sm:w-[420px] md:w-[460px] bg-white shadow-2xl flex flex-col border-l rtl:border-l-0 rtl:border-r border-slate-200 text-slate-800 overflow-hidden"
            >
              {/* Drawer Header (Modern Gradient: "AI Workspace Assistant") */}
              <div className="bg-gradient-to-r from-indigo-600 via-indigo-700 to-violet-700 text-white p-4 sm:p-5 flex items-center justify-between border-b border-indigo-800/20 shadow-md">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-white/10 backdrop-blur-md flex items-center justify-center border border-white/20 shadow-inner">
                    <Zap className="w-5 h-5 text-amber-300 animate-pulse" />
                  </div>
                  <div>
                    <h2 className="text-base font-extrabold tracking-tight text-white flex items-center gap-1.5">
                      <span>{t('ai.workspaceTitle', 'AI Workspace Assistant')}</span>
                      <span className="text-[10px] uppercase font-black bg-amber-400/20 text-amber-200 px-2 py-0.5 rounded-full border border-amber-300/30">Co-Pilot</span>
                    </h2>
                    <p className="text-xs text-indigo-100 font-medium opacity-90">
                      {t('ai.workspaceSubtitle', 'Powered by Gemini AI • Real-time Co-Pilot')}
                    </p>
                  </div>
                </div>

                <button
                  onClick={() => setIsOpen(false)}
                  aria-label="Close AI Assistant"
                  className="w-9 h-9 flex items-center justify-center rounded-xl bg-white/10 hover:bg-white/20 text-white transition-colors cursor-pointer border border-white/10"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Quick Actions Shortcuts Toolbar */}
              <ScrollableTabContainer
                className="bg-slate-100 border-b border-slate-200 p-2.5 text-xs font-semibold"
                gradientColor="from-slate-100"
                innerClassName="flex gap-2"
              >
                <button
                  onClick={handleTriggerColorPalettes}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-indigo-50 text-indigo-700 hover:text-indigo-900 border border-slate-200 hover:border-indigo-300 rounded-lg whitespace-nowrap shadow-2xs transition-all cursor-pointer shrink-0"
                >
                  <Palette className="w-3.5 h-3.5 text-indigo-600 shrink-0" />
                  <span>{t('ai.quickActionColor', 'Color Palette')}</span>
                </button>

                <button
                  onClick={handleTriggerUTM}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-indigo-50 text-indigo-700 hover:text-indigo-900 border border-slate-200 hover:border-indigo-300 rounded-lg whitespace-nowrap shadow-2xs transition-all cursor-pointer shrink-0"
                >
                  <LinkIcon className="w-3.5 h-3.5 text-indigo-600 shrink-0" />
                  <span>{t('ai.quickActionUtm', 'UTM Tracking')}</span>
                </button>

                <button
                  onClick={handleTriggerTextOptimization}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-indigo-50 text-indigo-700 hover:text-indigo-900 border border-slate-200 hover:border-indigo-300 rounded-lg whitespace-nowrap shadow-2xs transition-all cursor-pointer shrink-0"
                >
                  <FileText className="w-3.5 h-3.5 text-indigo-600 shrink-0" />
                  <span>{t('ai.quickActionVcard', 'vCard / Menu')}</span>
                </button>

                <button
                  onClick={handleTriggerDiagnostics}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-indigo-50 text-indigo-700 hover:text-indigo-900 border border-slate-200 hover:border-indigo-300 rounded-lg whitespace-nowrap shadow-2xs transition-all cursor-pointer shrink-0"
                >
                  <SearchCheck className="w-3.5 h-3.5 text-indigo-600 shrink-0" />
                  <span>{t('ai.quickActionDiagnostics', 'Diagnostics')}</span>
                </button>
              </ScrollableTabContainer>

              {/* Chat Thread Messages Area */}
              <div className="flex-1 overflow-y-auto p-4 sm:p-5 space-y-4 bg-slate-50/70">
                {messages.map((msg) => (
                  <div
                    key={msg.id}
                    className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}
                  >
                    <div className={`flex gap-2.5 max-w-[92%] ${msg.sender === 'user' ? 'flex-row-reverse' : ''}`}>
                      <div className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 text-xs font-black
                        ${msg.sender === 'user' 
                          ? 'bg-indigo-600 text-white' 
                          : 'bg-indigo-100 text-indigo-700 border border-indigo-200'
                        }
                      `}>
                        {msg.sender === 'user' ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
                      </div>

                      <div className="space-y-2 flex-1">
                        <div className={`p-3.5 rounded-2xl text-xs leading-relaxed font-medium shadow-3xs
                          ${msg.sender === 'user'
                            ? 'bg-indigo-600 text-white rounded-tr-none'
                            : 'bg-white text-slate-800 border border-slate-200 rounded-tl-none'
                          }
                        `}>
                          {msg.text}

                          {msg.status === 'success' && (
                            <div className="mt-2.5 pt-2 border-t border-slate-100 flex items-center gap-1.5 text-[11px] text-emerald-600 font-bold">
                              <CheckCircle2 className="w-3.5 h-3.5 shrink-0" />
                              <span>Ready! Workspace updated successfully.</span>
                            </div>
                          )}
                        </div>

                        {/* Interactive UI Block 1: AI Suggested Color Palettes */}
                        {msg.customType === 'color-palette' && (
                          <div className="bg-white border border-indigo-100 rounded-xl p-3 shadow-xs space-y-3">
                            <span className="text-[10px] font-black uppercase text-indigo-600 tracking-wider block">
                              Click "Apply to QR Generator" to use:
                            </span>

                            <div className="space-y-2.5">
                              {AI_COLOR_PALETTES.map((pal) => {
                                const isApplied = appliedItems[pal.id];
                                return (
                                  <div
                                    key={pal.id}
                                    className="p-2.5 bg-slate-50 hover:bg-indigo-50/50 border border-slate-200 hover:border-indigo-200 rounded-xl transition-all space-y-2"
                                  >
                                    <div className="flex items-center justify-between">
                                      <div className="flex items-center gap-2">
                                        <div className="flex items-center -space-x-1">
                                          <div className="w-4 h-4 rounded-full border border-white shadow-2xs" style={{ backgroundColor: pal.fgColor }} />
                                          <div className="w-4 h-4 rounded-full border border-white shadow-2xs" style={{ backgroundColor: pal.bgColor }} />
                                          <div className="w-4 h-4 rounded-full border border-white shadow-2xs" style={{ backgroundColor: pal.gradientColor }} />
                                        </div>
                                        <span className="text-xs font-bold text-slate-900">{pal.name}</span>
                                      </div>
                                      <div className="flex gap-1">
                                        {pal.tags.map(t => (
                                          <span key={t} className="text-[9px] bg-indigo-100 text-indigo-800 px-1.5 py-0.5 rounded-md font-bold">
                                            {t}
                                          </span>
                                        ))}
                                      </div>
                                    </div>

                                    <p className="text-[10px] text-slate-500">{pal.desc}</p>

                                    <button
                                      onClick={() => {
                                        handleApplyToGenerator(
                                          {
                                            design: {
                                              fgColor: pal.fgColor,
                                              bgColor: pal.bgColor,
                                              gradientType: pal.gradientType,
                                              gradientColor: pal.gradientColor,
                                              eyeColorTopLeft: pal.eyeTopLeft
                                            }
                                          },
                                          pal.id,
                                          `Applied "${pal.name}" palette to QR Generator!`
                                        );
                                      }}
                                      disabled={isApplied}
                                      className={`w-full py-1.5 px-3 rounded-lg text-xs font-bold flex items-center justify-center gap-1.5 transition-all cursor-pointer ${
                                        isApplied
                                          ? 'bg-emerald-600 text-white cursor-default'
                                          : 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-2xs active:scale-98'
                                      }`}
                                    >
                                      {isApplied ? (
                                        <>
                                          <Check className="w-3.5 h-3.5" />
                                          <span>Applied to Generator</span>
                                        </>
                                      ) : (
                                        <>
                                          <Palette className="w-3.5 h-3.5" />
                                          <span>Apply to QR Generator</span>
                                        </>
                                      )}
                                    </button>
                                  </div>
                                );
                              })}
                            </div>
                          </div>
                        )}

                        {/* Interactive UI Block 2: UTM Parameters Formatter */}
                        {msg.customType === 'utm-builder' && (
                          <div className="bg-white border border-indigo-100 rounded-xl p-3 shadow-xs space-y-2.5">
                            <span className="text-[10px] font-black uppercase text-indigo-600 tracking-wider block">
                              Configure UTM Analytics Parameters:
                            </span>

                            <div className="grid grid-cols-2 gap-2 text-xs">
                              <div>
                                <label htmlFor="utm-source-input" className="text-[10px] font-bold text-slate-500 block mb-0.5">UTM Source</label>
                                <input
                                  id="utm-source-input"
                                  type="text"
                                  value={utmSource}
                                  onChange={e => setUtmSource(e.target.value)}
                                  className="w-full bg-slate-50 border border-slate-200 rounded-lg px-2 py-1 text-xs font-medium focus:bg-white focus:border-indigo-500 outline-hidden"
                                />
                              </div>
                              <div>
                                <label htmlFor="utm-medium-input" className="text-[10px] font-bold text-slate-500 block mb-0.5">UTM Medium</label>
                                <input
                                  id="utm-medium-input"
                                  type="text"
                                  value={utmMedium}
                                  onChange={e => setUtmMedium(e.target.value)}
                                  className="w-full bg-slate-50 border border-slate-200 rounded-lg px-2 py-1 text-xs font-medium focus:bg-white focus:border-indigo-500 outline-hidden"
                                />
                              </div>
                            </div>

                            <div>
                              <label htmlFor="utm-campaign-input" className="text-[10px] font-bold text-slate-500 block mb-0.5">Campaign Name</label>
                              <input
                                id="utm-campaign-input"
                                type="text"
                                value={utmCampaign}
                                onChange={e => setUtmCampaign(e.target.value)}
                                className="w-full bg-slate-50 border border-slate-200 rounded-lg px-2 py-1 text-xs font-medium focus:bg-white focus:border-indigo-500 outline-hidden"
                              />
                            </div>

                            <div className="bg-slate-900 text-slate-200 p-2 rounded-lg text-[11px] font-mono break-all border border-slate-800">
                              {buildCurrentUtmUrl()}
                            </div>

                            <button
                              onClick={() => {
                                const formattedUrl = buildCurrentUtmUrl();
                                handleApplyToGenerator(
                                  {
                                    content: formattedUrl,
                                    originalUrl: formattedUrl
                                  },
                                  'utm-applied',
                                  `Applied UTM Tracking URL to QR Generator!`
                                );
                              }}
                              disabled={appliedItems['utm-applied']}
                              className={`w-full py-2 px-3 rounded-lg text-xs font-bold flex items-center justify-center gap-1.5 transition-all cursor-pointer ${
                                appliedItems['utm-applied']
                                  ? 'bg-emerald-600 text-white cursor-default'
                                  : 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-2xs active:scale-98'
                              }`}
                            >
                              {appliedItems['utm-applied'] ? (
                                <>
                                  <Check className="w-3.5 h-3.5" />
                                  <span>Applied URL to Generator</span>
                                </>
                              ) : (
                                <>
                                  <LinkIcon className="w-3.5 h-3.5" />
                                  <span>Apply URL to QR Generator</span>
                                </>
                              )}
                            </button>
                          </div>
                        )}

                        {/* Interactive UI Block 3: vCard / Menu Text Optimization */}
                        {msg.customType === 'vcard-opt' && msg.customData && (
                          <div className="bg-white border border-indigo-100 rounded-xl p-3 shadow-xs space-y-2.5">
                            <span className="text-[10px] font-black uppercase text-indigo-600 tracking-wider block">
                              Optimized Payload Preview:
                            </span>

                            <textarea
                              readOnly
                              value={msg.customData.textPayload}
                              className="w-full h-28 bg-slate-900 text-slate-100 font-mono text-[11px] p-2.5 rounded-lg border border-slate-800 resize-none outline-hidden"
                            />

                            <button
                              onClick={() => {
                                handleApplyToGenerator(
                                  {
                                    content: msg.customData.textPayload,
                                    type: msg.customData.type === 'vcard' ? 'vcard' : 'menu'
                                  },
                                  'vcard-applied',
                                  `Applied content directly into your active QR Generator!`
                                );
                              }}
                              disabled={appliedItems['vcard-applied']}
                              className={`w-full py-2 px-3 rounded-lg text-xs font-bold flex items-center justify-center gap-1.5 transition-all cursor-pointer ${
                                appliedItems['vcard-applied']
                                  ? 'bg-emerald-600 text-white cursor-default'
                                  : 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-2xs active:scale-98'
                              }`}
                            >
                              {appliedItems['vcard-applied'] ? (
                                <>
                                  <Check className="w-3.5 h-3.5" />
                                  <span>Applied Content to Generator</span>
                                </>
                              ) : (
                                <>
                                  <FileText className="w-3.5 h-3.5" />
                                  <span>Apply Content to QR Generator</span>
                                </>
                              )}
                            </button>
                          </div>
                        )}

                        {/* Interactive UI Block 4: Diagnostics Check */}
                        {msg.customType === 'diagnostics' && msg.customData && (
                          <div className="bg-white border border-indigo-100 rounded-xl p-3 shadow-xs space-y-2.5">
                            <div className="flex items-center justify-between border-b border-slate-100 pb-2">
                              <span className="text-[10px] font-black uppercase text-indigo-600 tracking-wider">
                                Scannability Rating
                              </span>
                              <span className="text-xs font-extrabold px-2 py-0.5 bg-emerald-100 text-emerald-800 rounded-full">
                                {msg.customData.score}% Excellent
                              </span>
                            </div>

                            <div className="space-y-1.5 text-[11px]">
                              <div className="flex items-center justify-between text-slate-700">
                                <span>Contrast (FG vs BG)</span>
                                <span className="font-bold text-emerald-600 flex items-center gap-1">
                                  <Check className="w-3 h-3" /> High Contrast
                                </span>
                              </div>

                              <div className="flex items-center justify-between text-slate-700">
                                <span>Error Correction Level</span>
                                <span className="font-bold text-slate-900">{msg.customData.ecl} Level</span>
                              </div>

                              <div className="flex items-center justify-between text-slate-700">
                                <span>Quiet Zone / Margin</span>
                                <span className="font-bold text-slate-900">{msg.customData.margin}px</span>
                              </div>
                            </div>

                            <button
                              onClick={() => {
                                handleApplyToGenerator(
                                  {
                                    design: {
                                      fgColor: '#0f172a',
                                      bgColor: '#ffffff',
                                      errorCorrectionLevel: 'Q',
                                      margin: 20,
                                      logoScale: 0.18,
                                      smartOptimize: true
                                    }
                                  },
                                  'diag-applied',
                                  `Applied optimal scannability settings (Level Q, high contrast, safe 20px quiet zone) to QR Generator!`
                                );
                              }}
                              disabled={appliedItems['diag-applied']}
                              className={`w-full py-2 px-3 rounded-lg text-xs font-bold flex items-center justify-center gap-1.5 transition-all cursor-pointer ${
                                appliedItems['diag-applied']
                                  ? 'bg-emerald-600 text-white cursor-default'
                                  : 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-2xs active:scale-98'
                              }`}
                            >
                              {appliedItems['diag-applied'] ? (
                                <>
                                  <Check className="w-3.5 h-3.5" />
                                  <span>Optimal Settings Applied</span>
                                </>
                              ) : (
                                <>
                                  <Zap className="w-3.5 h-3.5" />
                                  <span>Auto-Optimize Scannability Settings</span>
                                </>
                              )}
                            </button>
                          </div>
                        )}

                      </div>
                    </div>
                  </div>
                ))}

                {isLoading && (
                  <div className="flex justify-start">
                    <div className="flex gap-2.5 max-w-[85%]">
                      <div className="w-7 h-7 rounded-full bg-indigo-100 border border-indigo-200 flex items-center justify-center shrink-0">
                        <Loader2 className="w-4 h-4 text-indigo-600 animate-spin" />
                      </div>
                      <div className="bg-white border border-slate-200 p-3.5 rounded-2xl text-xs shadow-3xs text-slate-600 italic flex flex-col gap-1">
                        <span className="font-bold text-[10px] uppercase tracking-wider text-indigo-600 not-italic flex items-center gap-1">
                          <Zap className="w-3 h-3 text-amber-500 animate-pulse" />
                          <span>AI Co-Pilot Working</span>
                        </span>
                        <span>{currentStep || 'Synthesizing layout structures...'}</span>
                      </div>
                    </div>
                  </div>
                )}

                {/* Initial Quick Prompt Pills */}
                {messages.length === 1 && (
                  <div className="space-y-3 pt-2">
                    <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest block">
                      Quick Action Shortcuts
                    </span>

                    {/* 4 Primary Shortcuts */}
                    <div className="grid grid-cols-2 gap-2">
                      <button
                        onClick={handleTriggerColorPalettes}
                        className="p-2.5 bg-white hover:bg-indigo-50/70 border border-slate-200 hover:border-indigo-300 rounded-xl text-left transition-all group cursor-pointer shadow-2xs"
                      >
                        <Palette className="w-4 h-4 text-indigo-600 mb-1 group-hover:scale-110 transition-transform" />
                        <span className="text-xs font-bold text-slate-900 block">Brand Palettes</span>
                        <span className="text-[10px] text-slate-500 block">High contrast hexes</span>
                      </button>

                      <button
                        onClick={handleTriggerUTM}
                        className="p-2.5 bg-white hover:bg-indigo-50/70 border border-slate-200 hover:border-indigo-300 rounded-xl text-left transition-all group cursor-pointer shadow-2xs"
                      >
                        <LinkIcon className="w-4 h-4 text-indigo-600 mb-1 group-hover:scale-110 transition-transform" />
                        <span className="text-xs font-bold text-slate-900 block">UTM Tracking</span>
                        <span className="text-[10px] text-slate-500 block">GA offline tags</span>
                      </button>

                      <button
                        onClick={handleTriggerTextOptimization}
                        className="p-2.5 bg-white hover:bg-indigo-50/70 border border-slate-200 hover:border-indigo-300 rounded-xl text-left transition-all group cursor-pointer shadow-2xs"
                      >
                        <FileText className="w-4 h-4 text-indigo-600 mb-1 group-hover:scale-110 transition-transform" />
                        <span className="text-xs font-bold text-slate-900 block">vCard / Menu</span>
                        <span className="text-[10px] text-slate-500 block">Structured text</span>
                      </button>

                      <button
                        onClick={handleTriggerDiagnostics}
                        className="p-2.5 bg-white hover:bg-indigo-50/70 border border-slate-200 hover:border-indigo-300 rounded-xl text-left transition-all group cursor-pointer shadow-2xs"
                      >
                        <SearchCheck className="w-4 h-4 text-indigo-600 mb-1 group-hover:scale-110 transition-transform" />
                        <span className="text-xs font-bold text-slate-900 block">Diagnostics</span>
                        <span className="text-[10px] text-slate-500 block">Check scannability</span>
                      </button>
                    </div>

                    {/* Campaign Creation List */}
                    <div className="pt-2">
                      <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-2">
                        Campaign Generators
                      </span>
                      <div className="space-y-1.5">
                        {CATEGORY_QUICK_COMMANDS.map((cmd) => {
                          const Icon = cmd.icon;
                          return (
                            <button
                              key={cmd.label}
                              onClick={() => handleCommandSubmit(cmd.label)}
                              className="w-full flex items-center justify-between p-2.5 bg-white hover:bg-indigo-50/60 border border-slate-200 hover:border-indigo-200 rounded-xl transition-all text-start group cursor-pointer"
                            >
                              <div className="flex items-center gap-2.5 min-w-0">
                                <div className="p-1.5 bg-slate-100 group-hover:bg-indigo-100 text-slate-600 group-hover:text-indigo-700 rounded-lg transition-colors border border-slate-200">
                                  <Icon className="w-3.5 h-3.5" />
                                </div>
                                <div className="truncate">
                                  <span className="text-xs font-bold text-slate-900 block truncate">{cmd.label}</span>
                                  <span className="text-[10px] text-slate-500 block truncate">{cmd.desc}</span>
                                </div>
                              </div>
                              <ArrowRight className="w-3.5 h-3.5 text-slate-300 group-hover:text-indigo-600 shrink-0 ms-2 transition-colors rtl:rotate-180" />
                            </button>
                          );
                        })}
                      </div>
                    </div>
                  </div>
                )}

                <div ref={chatEndRef} />
              </div>

              {/* Drawer Footer Form */}
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  handleCommandSubmit(inputValue);
                }}
                className="bg-white border-t border-slate-200 p-3 sm:p-4 flex gap-2 shadow-inner"
              >
                <input
                  type="text"
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  disabled={isLoading}
                  placeholder={t('ai.inputPlaceholder', "Ask AI Assistant (e.g., 'Suggest red color theme')")}
                  className="flex-1 bg-slate-50 border border-slate-200 hover:border-slate-300 focus:border-indigo-500 focus:bg-white text-xs font-medium px-3.5 py-2.5 rounded-xl outline-hidden transition-all text-slate-800 placeholder-slate-400"
                />
                <button
                  type="submit"
                  disabled={isLoading || !inputValue.trim()}
                  aria-label="Send Prompt"
                  className="p-2.5 bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-100 text-white disabled:text-slate-400 rounded-xl transition-all cursor-pointer border border-transparent shadow-2xs active:scale-95"
                >
                  <Send className="w-4 h-4" />
                </button>
              </form>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </>
  );
}
