import json
import re

with open("src/locales/en.json", "r", encoding="utf-8") as f:
    en_data = json.load(f)

with open("src/locales/hi.json", "r", encoding="utf-8") as f:
    hi_data = json.load(f)

ALLOWED_ACRONYMS = {
    "QR", "PNG", "SVG", "PDF", "JPEG", "JPG", "WEBP", "EPS", "CSS", "HTML",
    "URL", "URI", "API", "WIFI", "WI-FI", "VCARD", "VCARDS", "MECARD", "EPC",
    "EAN", "UPC", "EAN-13", "EAN-8", "UPC-A", "UPC-E", "CODE128", "CODE39",
    "ITF", "ITF-14", "MSI", "PLESSEY", "DATAMATRIX", "PDF417", "AZTEC", "CODABAR",
    "ID", "UUID", "OS", "IOS", "ANDROID", "GOOGLE", "APPLE", "WALLET", "SMS",
    "EMAIL", "GPS", "SKU", "ASCII", "ISO", "GS1", "FREEQRBARCODES.COM",
    "FREEQRGEN.PRO", "WHATSAPP", "TWITTER", "FACEBOOK", "LINKEDIN", "INSTAGRAM",
    "YOUTUBE", "TIKTOK", "ZOOM", "SKYPE", "TELEGRAM", "VIBER", "PAYPAL", "STRIPE",
    "SEPA", "IBAN", "BIC", "SWIFT", "JSON", "CSV", "XLSX", "ZIP", "HTTP", "HTTPS",
    "WWW", "A4", "A3", "A5", "EPSON", "ZEBRA", "DPI", "CMYK", "RGB", "TLS", "SQL", "POS"
}

def get_english_words(val):
    if not isinstance(val, str):
        return []
    words = re.findall(r'[a-zA-Z]+', val)
    return [w for w in words if w.upper() not in ALLOWED_ACRONYMS]

def is_pure_hindi(val):
    if not isinstance(val, str):
        return False
    eng = get_english_words(val)
    return len(eng) == 0 and bool(re.search(r'[\u0900-\u097F]', val))

# Complete translation mapping dictionary
EXACT_MAP = {
    # NAV & UI
    "nav.analyticsTab": "स्कैन विश्लेषण",
    "nav.formTab": "फॉर्म बिल्डर",
    "nav.restaurantMenuTab": "रेस्तरां मेनू",
    "nav.digitalCardTab": "डिजिटल कार्ड",
    "nav.pdfTab": "PDF साझाकरण",
    "nav.bulkGeneratorTab": "बल्क जनरेटर",
    "nav.barcodeGeneratorTab": "बारकोड जनरेटर",
    "nav.generator": "QR स्टूडियो",
    "nav.myProfile": "प्रोफ़ाइल और सेटिंग्स",
    "nav.savedQRs": "सहेजे गए QR कोड",
    "footer.aboutUs": "हमारे बारे में",
    "footer.whyUs": "हमें क्यों चुनें?",
    "footer.privacyPolicy": "गोपनीयता नीति",
    "footer.termsOfService": "सेवा की शर्तें",
    "footer.contactUs": "संपर्क करें",
    "footer.rights": "सभी अधिकार सुरक्षित हैं © {{year}} FreeQRGen.pro",
    "ui.back": "वापस जाएं",
    "common.none": "कोई नहीं",

    # BARCODE
    "barcode.title": "बारकोड जनरेशन स्टेशन",
    "barcode.subtitle": "सटीक रेंडरिंग, स्कैनर सत्यापन सुरक्षा और कस्टम रंग प्रीसेट के साथ मानक लीनियर बारकोड जनरेट करें।",
    "barcode.valEmpty": "बारकोड जनरेट करने के लिए कृपया एक मान दर्ज करें।",
    "barcode.valEanDigits": "EAN-13 में केवल संख्यात्मक अंक (0-9) होना आवश्यक है।",
    "barcode.valEanLen": "EAN-13 में ठीक 12 या 13 अंक होने चाहिए (वर्तमान: {count})। 12-अंकों का इनपुट स्वतः ही अपनी चेकसम संख्या जोड़ लेता है।",
    "barcode.valUpcDigits": "UPC-A में केवल संख्यात्मक अंक (0-9) होना आवश्यक है।",
    "barcode.valUpcLen": "UPC-A में ठीक 11 या 12 अंक होने चाहिए (वर्तमान: {count})। 11-अंकों का इनपुट स्वतः ही अपनी चेकसम संख्या जोड़ लेता है।",
    "barcode.valCode39Chars": "CODE39 0-9, A-Z (बड़े अक्षर), स्पेस और प्रतीकों का समर्थन करता है: - . $ / + %",
    "barcode.valCode128Ascii": "CODE128 केवल मानक 128 ASCII वर्णों का समर्थन करता है।",
    "barcode.passedValidation": "प्रारूप सत्यापन सफल! उच्च भौतिक कंट्रास्ट रेंडर के लिए तैयार है।",
    "barcode.validFormat": "वैध बारकोड प्रारूप।",

    # BLOG
    "blog.category.qr_code_guides": "QR कोड गाइड",
    "blog.category.business_marketing": "व्यावसायिक मार्केटिंग",
    "blog.category.digital_marketing": "डिजिटल मार्केटिंग",
    "blog.category.small_business_tools": "लघु व्यवसाय उपकरण",
    "blog.category.technology": "प्रौद्योगिकी",
    "blog.category.contactless_solutions": "कॉन्टैक्टलेस समाधान",
    "blog.category.restaurant_qr_menus": "रेस्तरां QR मेनू",
    "blog.category.event_qr_codes": "इवेंट QR कोड",
    "blog.category.education_qr_codes": "शिक्षा QR कोड",
    "blog.category.social_media_marketing": "सोशल मीडिया मार्केटिंग",

    # ANALYTICS
    "analytics.colBrowser": "क्लाइंट ब्राउज़र",
    "analytics.colDatetime": "स्कैन समय और तिथि",
    "analytics.colLocation": "अनुमानित स्थान",
    "analytics.colPlatform": "ऑपरेटिंग सिस्टम",
    "analytics.desc": "सक्रिय उपयोगकर्ता रीडायरेक्ट को ट्रैक करने वाले सुरक्षित क्लाउड लॉगिंग मीट्रिक।",
    "analytics.heatmapDesc": "उपयोगकर्ता सहभागिता दर्शाने वाले इंटरैक्टिव होवर हॉटस्पॉट।",
    "analytics.heatmapTitle": "क्षेत्रीय हीटमैप वितरण",
    "analytics.leaderboardDesc": "स्कैन के आधार पर वर्गीकृत सक्रिय क्षेत्र।",
    "analytics.leaderboardTitle": "शीर्ष प्रदर्शन करने वाले क्षेत्र",
    "analytics.liveLogTitle": "लाइव रियल-टाइम स्कैन स्ट्रीम",
    "analytics.noLogs": "अभी तक कोई स्कैन रिकॉर्ड दर्ज नहीं किया गया है।",
    "analytics.noLogsDesc": "जब उपयोगकर्ता आपके जनरेट किए गए QR कोड को स्कैन करेंगे, तो डेटा यहां दिखाई देगा।",
    "analytics.title": "स्कैन विश्लेषण एवं एनालिटिक्स",

    # AUTH & CONTROL
    "auth.accessRestrictedDesc": "कृपया इस सुविधा तक पहुँचने के लिए अपने खाते में लॉग इन करें।",
    "auth.signInSignUpButton": "साइन इन / खाता बनाएं",
    "control.payPixAmountLabel": "राशि (BRL R$)",
    "control.payGrabLinkLabel": "GrabPay भुगतान लिंक या फ़ोन नंबर",
    "control.payTillLabel": "टिल नंबर",
    "control.payPaybillLabel": "पेबिल नंबर (वैकल्पिक)",
    "control.payMpesaAccountLabel": "पेबिल खाता संख्या",
    "control.payJazzAccountLabel": "JazzCash खाता / मोबाइल नंबर",
    "control.payJazzAmountLabel": "राशि (PKR) (वैकल्पिक)",
    "control.payEasyAccountLabel": "EasyPaisa खाता / मोबाइल नंबर",
    "control.payStcPhoneLabel": "STC Pay मोबाइल नंबर",
    "control.payStcAmountLabel": "राशि (SAR) (वैकल्पिक)",

    # ERRORS & CONFIRMS
    "error.signInToSave": "अपनी लाइब्रेरी में QR डिज़ाइन सहेजने के लिए कृपया साइन इन करें या खाता बनाएं।",
    "confirm.clearAllScans": "क्या आप निश्चित रूप से सभी स्कैन लॉग साफ़ करना चाहते हैं? इसे वापस नहीं लिया जा सकता।",
    "confirm.deletePreset": "क्या आप निश्चित रूप से इस प्रीसेट को हटाना चाहते हैं?",

    # GUIDES & HUB & TOOLS
    "kb.allCategories": "सभी श्रेणियां",
    "knowledge.aiSummaryTitle": "AI खोज इंजन कोर संश्लेषण बॉक्स",
    "mockup.activeScanning": "स्कैनिंग कैमरा सक्रिय",
    "tour.skip": "टूर छोड़ें",
    "status.connected": "कनेक्टेड",
    "palette.bgColorLabel": "बैकग्राउंड कैनवास का रंग",
    "preview.a4Sheet": "A4 शीट",
    "preview.a3Sheet": "A3 शीट",
    "preview.a5Sheet": "A5 शीट",
    "print.activeAlignmentMarks": "सक्रिय कटलाइन्स और संरेखण निशान — प्रिंट में छिपे हुए",
    "programmatic.authorName": "FreeQRGen.pro संपादकीय बोर्ड",
    "saved.allCount": "सभी ({count})",
    "seo.aestheticOptimization": "सौंदर्य अनुकूलन (एस्थेटिक ऑप्टिमाइज़ेशन)",
    "shortcuts.close": "मॉडल विंडो बंद करें",
    "templates.activateGenerator": "जनरेटर सक्रिय करें",
    "templatesHub.allCategories": "सभी श्रेणियां",
    "templatesTab.applyBtn": "टेम्प्लेट प्रीसेट लागू करें",
    "vision.ready": "तैयार",
    "landing.home": "मुख्य पृष्ठ",
    "home.popularQrTools": "लोकप्रिय QR कोड उपकरण",
    "tools.wifi.title": "वाई-फाई नेटवर्क साझाकरण",
    "colorPalette.title": "रंग पैलेट",
    "scannability.title": "QR स्कैन-क्षमता जांचकर्ता",
    "directory.badge": "उच्च प्रदर्शन डायरेक्टरी",
    "recent.badge": "लाइव उपयोग आंकड़े और रुझान",
    "guides.title": "संबंधित निःशुल्क QR जनरेशन गाइड"
}

# Replacement dictionary for translating mixed words or pure English strings
REPLACEMENTS = [
    (r"\bScan Analytics\b", "स्कैन विश्लेषण"),
    (r"\bScan Analytics Registered\b", "स्कैन विश्लेषण पंजीकृत"),
    (r"\bAnalytics\b", "विश्लेषण"),
    (r"\bOverview\b", "अवलोकन"),
    (r"\bDashboard\b", "डैशबोर्ड"),
    (r"\bSettings\b", "सेटिंग्स"),
    (r"\bConfiguration\b", "कॉन्फ़िगरेशन"),
    (r"\bSecurity\b", "सुरक्षा"),
    (r"\bVerification\b", "सत्यापन"),
    (r"\bValidation\b", "वैधता जाँच"),
    (r"\bResolution\b", "रिज़ॉल्यूशन"),
    (r"\bHigh Contrast\b", "उच्च कंट्रास्ट"),
    (r"\bVector Quality\b", "वेक्टर गुणवत्ता"),
    (r"\bDownload PNG\b", "PNG डाउनलोड करें"),
    (r"\bDownload SVG\b", "SVG डाउनलोड करें"),
    (r"\bDownload PDF\b", "PDF डाउनलोड करें"),
    (r"\bDownload\b", "डाउनलोड करें"),
    (r"\bExport\b", "निर्यात करें"),
    (r"\bImport\b", "आयात करें"),
    (r"\bGenerator\b", "जनरेटर"),
    (r"\bGenerate\b", "जनरेट करें"),
    (r"\bEnterprise\b", "एंटरप्राइज"),
    (r"\bSolutions\b", "समाधान"),
    (r"\bTemplates\b", "टेम्प्लेट"),
    (r"\bTemplate\b", "टेम्प्लेट"),
    (r"\bPreview\b", "पूर्वावलोकन"),
    (r"\bActive\b", "सक्रिय"),
    (r"\bDisabled\b", "निष्क्रिय"),
    (r"\bEnabled\b", "सक्षम"),
    (r"\bCopy Link\b", "लिंक कॉपी करें"),
    (r"\bCopied!\b", "कॉपी हो गया!"),
    (r"\bCopied\b", "कॉपी किया गया"),
    (r"\bSaved\b", "सहेजा गया"),
    (r"\bSave\b", "सहेजें"),
    (r"\bDelete\b", "हटाएं"),
    (r"\bEdit\b", "संपादित करें"),
    (r"\bCancel\b", "रद्द करें"),
    (r"\bConfirm\b", "पुष्टि करें"),
    (r"\bClose\b", "बंद करें"),
    (r"\bBack\b", "वापस"),
    (r"\bNext\b", "आगे"),
    (r"\bSubmit\b", "सबमिट करें"),
    (r"\bSearch\b", "खोजें"),
    (r"\bCategories\b", "श्रेणियां"),
    (r"\bCategory\b", "श्रेणी"),
    (r"\bAll Categories\b", "सभी श्रेणियां"),
    (r"\bDescription\b", "विवरण"),
    (r"\bTitle\b", "शीर्षक"),
    (r"\bName\b", "नाम"),
    (r"\bEmail\b", "ईमेल"),
    (r"\bPhone\b", "फ़ोन"),
    (r"\bAddress\b", "पता"),
    (r"\bWebsite\b", "वेबसाइट"),
    (r"\bLogo\b", "लोगो"),
    (r"\bColor\b", "रंग"),
    (r"\bBackground\b", "पृष्ठभूमि"),
    (r"\bForeground\b", "अग्रभूमि"),
    (r"\bFrame\b", "फ्रेम"),
    (r"\bMargin\b", "मार्जिन"),
    (r"\bHeight\b", "ऊंचाई"),
    (r"\bWidth\b", "चौड़ाई"),
    (r"\bThickness\b", "मोटाई"),
    (r"\bSize\b", "आकार"),
    (r"\bQuiet Zone\b", "शांत क्षेत्र"),
    (r"\bSilent Zone\b", "शांत क्षेत्र"),
    (r"\bError Correction\b", "त्रुटि सुधार"),
    (r"\bCorrection Level\b", "सुधार स्तर"),
    (r"\bPayload\b", "पेलोड"),
    (r"\bDynamic\b", "डायनेमिक"),
    (r"\bStatic\b", "स्टैटिक"),
    (r"\bCustomization\b", "कस्टमाइजेशन"),
    (r"\bScanning\b", "स्कैनिंग"),
    (r"\bScannability\b", "स्कैन-क्षमता"),
    (r"\bWorkspace\b", "कार्यस्थान"),
    (r"\bTeam\b", "टीम"),
    (r"\bCollaboration\b", "सहयोग"),
    (r"\bIntegration\b", "एकीकरण"),
    (r"\bWebhook\b", "वेबहुक"),
    (r"\bDomain\b", "डोमेन"),
    (r"\bRedirect\b", "पुनर्निर्देशन"),
    (r"\bLogs\b", "लॉग्स"),
    (r"\bMetrics\b", "मीट्रिक"),
    (r"\bSubscription\b", "सदस्यता"),
    (r"\bPlan\b", "योजना"),
    (r"\bUnlimited\b", "असीमित"),
    (r"\bFree\b", "निःशुल्क"),
    (r"\bGuides\b", "गाइड"),
    (r"\bGuide\b", "गाइड"),
    (r"\bDirectory\b", "डायरेक्टरी"),
    (r"\bRecent\b", "हाल की"),
    (r"\bPopular\b", "लोकप्रिय"),
    (r"\bTools\b", "उपकरण"),
    (r"\bTool\b", "उपकरण"),
    (r"\bPresets\b", "प्रीसेट"),
    (r"\bPreset\b", "प्रीसेट"),
    (r"\bSheet\b", "शीट"),
    (r"\bPrint\b", "प्रिंट"),
    (r"\bAcademic\b", "अकादमिक"),
    (r"\bCitations\b", "उद्धरण"),
    (r"\bReference\b", "संदर्भ"),
    (r"\bPapers\b", "कागजात"),
    (r"\bBoard\b", "बोर्ड"),
    (r"\bEditorial\b", "संपादकीय"),
    (r"\bSystem\b", "सिस्टम"),
    (r"\bArchitecture\b", "वास्तुकला"),
    (r"\bInfrastructure\b", "अवसंरचना"),
    (r"\bNetwork\b", "नेटवर्क"),
    (r"\bLocal\b", "स्थानीय"),
    (r"\bGlobal\b", "वैश्विक"),
    (r"\bStandard\b", "मानक"),
    (r"\bCustom\b", "कस्टम"),
    (r"\bPerformance\b", "प्रदर्शन"),
    (r"\bOptimization\b", "अनुकूलन"),
    (r"\bAesthetic\b", "सौंदर्य"),
    (r"\bAll\b", "सभी"),
    (r"\bHome\b", "मुख्य पृष्ठ"),
    (r"\bNone\b", "कोई नहीं"),
    (r"\bProfile\b", "प्रोफ़ाइल"),
    (r"\bCode\b", "कोड"),
    (r"\bCodes\b", "कोड"),
    (r"\bUser\b", "उपयोगकर्ता"),
    (r"\bUsers\b", "उपयोगकर्ता"),
    (r"\bManagement\b", "प्रबंधन"),
    (r"\bControl\b", "नियंत्रण"),
    (r"\bPanel\b", "पैनल"),
    (r"\bLevel\b", "स्तर"),
    (r"\bType\b", "प्रकार"),
    (r"\bFormat\b", "प्रारूप"),
    (r"\bStyle\b", "शैली"),
    (r"\bStyles\b", "शैली"),
    (r"\bDesign\b", "डिज़ाइन"),
    (r"\bDesigns\b", "डिज़ाइन"),
    (r"\bStudio\b", "स्टूडियो"),
    (r"\bCreator\b", "क्रिएटर"),
    (r"\bCreation\b", "सृजन"),
    (r"\bHelp\b", "सहायता"),
    (r"\bSupport\b", "सहायता"),
    (r"\bContact\b", "संपर्क"),
    (r"\bAbout\b", "के बारे में"),
    (r"\bUs\b", "हमारे"),
    (r"\bTerms\b", "शर्तें"),
    (r"\bPrivacy\b", "गोपनीयता"),
    (r"\bPolicy\b", "नीति"),
    (r"\bRights\b", "अधिकार"),
    (r"\bReserved\b", "सुरक्षित"),
    (r"\bAll Rights Reserved\b", "सभी अधिकार सुरक्षित"),
    (r"\bKey\b", "कुंजी"),
    (r"\bKeys\b", "कुंजियां"),
    (r"\bValue\b", "मान"),
    (r"\bValues\b", "मान"),
    (r"\bOption\b", "विकल्प"),
    (r"\bOptions\b", "विकल्प"),
    (r"\bStatus\b", "स्थिति"),
    (r"\bSuccess\b", "सफल"),
    (r"\bFailed\b", "विफल"),
    (r"\bError\b", "त्रुटि"),
    (r"\bWarning\b", "चेतावनी"),
    (r"\bInfo\b", "जानकारी"),
    (r"\bNotice\b", "सूचना"),
    (r"\bAlert\b", "अलर्ट"),
    (r"\bAlerts\b", "अलर्ट"),
    (r"\bMessage\b", "संदेश"),
    (r"\bMessages\b", "संदेश"),
    (r"\bNotification\b", "अधिसूचना"),
    (r"\bNotifications\b", "अधिसूचनाएं"),
    (r"\bShare\b", "साझा करें"),
    (r"\bShared\b", "साझा किया गया"),
    (r"\bSharing\b", "साझाकरण"),
    (r"\bLink\b", "लिंक"),
    (r"\bLinks\b", "लिंक"),
    (r"\bUrl\b", "URL"),
    (r"\bData\b", "डेटा"),
    (r"\bFile\b", "फ़ाइल"),
    (r"\bFiles\b", "फ़ाइलें"),
    (r"\bFolder\b", "फ़ोल्डर"),
    (r"\bFolders\b", "फ़ोल्डर"),
    (r"\bLibrary\b", "लाइब्रेरी"),
    (r"\bCollection\b", "संग्रह"),
    (r"\bItem\b", "आइटम"),
    (r"\bItems\b", "आइटम"),
    (r"\bList\b", "सूची"),
    (r"\bView\b", "देखें"),
    (r"\bShow\b", "दिखाएं"),
    (r"\bHide\b", "छिपाएं"),
    (r"\bSelect\b", "चुनें"),
    (r"\bSelected\b", "चयनित"),
    (r"\bChoose\b", "चुनें"),
    (r"\bAdd\b", "जोड़ें"),
    (r"\bCreate\b", "बनाएं"),
    (r"\bUpdate\b", "अपडेट करें"),
    (r"\bRemove\b", "हटाएं"),
    (r"\bClear\b", "साफ़ करें"),
    (r"\bReset\b", "रीसेट करें"),
    (r"\bApply\b", "लागू करें"),
    (r"\bApplied\b", "लागू किया गया"),
    (r"\bLoad\b", "लोड करें"),
    (r"\bLoading\b", "लोड हो रहा है"),
    (r"\bSave Changes\b", "परिवर्तन सहेजें"),
    (r"\bQuick\b", "त्वरित"),
    (r"\bFast\b", "तेज़"),
    (r"\bEasy\b", "आसान"),
    (r"\bSimple\b", "सरल"),
    (r"\bSmart\b", "स्मार्ट"),
    (r"\bAdvanced\b", "उन्नत"),
    (r"\bPro\b", "प्रो"),
    (r"\bBasic\b", "मूल"),
    (r"\bPremium\b", "प्रीमियम"),
    (r"\bOfficial\b", "आधिकारिक"),
    (r"\bPublic\b", "सार्वजनिक"),
    (r"\bPrivate\b", "निजी"),
    (r"\bProtected\b", "संरक्षित"),
    (r"\bSecure\b", "सुरक्षित"),
    (r"\bSafety\b", "सुरक्षा"),
    (r"\bTrust\b", "विश्वास"),
    (r"\bCenter\b", "केंद्र"),
    (r"\bHub\b", "हब"),
    (r"\bBase\b", "बेस"),
    (r"\bKnowledge\b", "ज्ञान"),
    (r"\bArticle\b", "लेख"),
    (r"\bArticles\b", "लेख"),
    (r"\bPaper\b", "कागज़"),
    (r"\bDocument\b", "दस्तावेज़"),
    (r"\bDocuments\b", "दस्तावेज़"),
    (r"\bPage\b", "पृष्ठ"),
    (r"\bPages\b", "पृष्ठ"),
    (r"\bSection\b", "अनुभाग"),
    (r"\bSections\b", "अनुभाग"),
    (r"\bBlock\b", "ब्लॉक"),
    (r"\bBlocks\b", "ब्लॉक"),
    (r"\bCard\b", "कार्ड"),
    (r"\bCards\b", "कार्ड"),
    (r"\bForm\b", "फॉर्म"),
    (r"\bForms\b", "फॉर्म"),
    (r"\bInput\b", "इनपुट"),
    (r"\bOutput\b", "आउटपुट"),
    (r"\bResult\b", "परिणाम"),
    (r"\bResults\b", "परिणाम"),
    (r"\bTotal\b", "कुल"),
    (r"\bCount\b", "गिनती"),
    (r"\bNumber\b", "संख्या"),
    (r"\bText\b", "पाठ"),
    (r"\bImage\b", "छवि"),
    (r"\bImages\b", "छवियां"),
    (r"\bIcon\b", "आइकन"),
    (r"\bIcons\b", "आइकन"),
    (r"\bShape\b", "आकार"),
    (r"\bShapes\b", "आकार"),
    (r"\bEye\b", "आई (आंख)"),
    (r"\bEyes\b", "आई स्टाइल"),
    (r"\bDot\b", "डॉट (बिंदु)"),
    (r"\bDots\b", "डॉट स्टाइल"),
    (r"\bPattern\b", "पैटर्न"),
    (r"\bPatterns\b", "पैटर्न"),
    (r"\bGradient\b", "ग्रेडिएंट"),
    (r"\bSolid\b", "ठोस"),
    (r"\bLinear\b", "लीनियर"),
    (r"\bRadial\b", "रेडियल"),
    (r"\bCorner\b", "कोना"),
    (r"\bCorners\b", "कोने"),
    (r"\bBorder\b", "बॉडर"),
    (r"\bBorders\b", "बॉडर"),
    (r"\bPadding\b", "पैडिंग"),
    (r"\bSpacing\b", "स्पेसिंग"),
    (r"\bAlign\b", "संरेखित करें"),
    (r"\bAlignment\b", "संरेखण"),
    (r"\bCenter\b", "केंद्र"),
    (r"\bLeft\b", "बाएं"),
    (r"\bRight\b", "दाएं"),
    (r"\bTop\b", "ऊपर"),
    (r"\bBottom\b", "नीचे")
]

def clean_text(text):
    if not isinstance(text, str):
        return text
    res = text
    for pat, repl in REPLACEMENTS:
        res = re.sub(pat, repl, res)
    return res

new_hi_data = {}
updated_keys_count = 0

for k in en_data.keys():
    en_val = en_data[k]
    hi_val = hi_data.get(k, "")

    if k in EXACT_MAP:
        new_hi_data[k] = EXACT_MAP[k]
        updated_keys_count += 1
    elif is_pure_hindi(hi_val):
        # Check if any lingering English words exist
        cleaned = clean_text(hi_val)
        new_hi_data[k] = cleaned
    else:
        # Translate from hi_val or en_val using clean_text
        source = hi_val if hi_val else en_val
        cleaned = clean_text(source)
        new_hi_data[k] = cleaned
        updated_keys_count += 1

print(f"Total keys processed: {len(new_hi_data)}")

# Save updated hi.json
with open("src/locales/hi.json", "w", encoding="utf-8") as f:
    json.dump(new_hi_data, f, ensure_ascii=False, indent=2)

print("Saved updated src/locales/hi.json!")
