import json

wifi_locales_data = {
    "de": {
        "seo.landing.wifi-qr-generator.seoTitle": "Kostenloser WLAN QR-Code Generator | Ohne Passworteingabe verbinden",
        "seo.landing.wifi-qr-generator.metaDescription": "Erstellen Sie kostenlose WLAN-QR-Codes. Ermöglichen Sie Gästen, sich ohne Eintippen des Passworts mit Ihrem Netzwerk zu verbinden.",
        "seo.landing.wifi-qr-generator.keyword": "kostenloser wlan qr code generator",
        "seo.landing.wifi-qr-generator.h1": "Kostenloser WLAN QR-Code Generator",
        "seo.landing.wifi-qr-generator.intro.title": "Sofortige WLAN-Kopplung über statischen QR-Code",
        "seo.landing.wifi-qr-generator.intro.text1": "Das manuelle Eintippen langer alphanumerischer Passwörter ist zeitraubend und fehleranfällig. Unser kostenloser WLAN-QR-Code-Generator fasst Netzwerkname (SSID), Verschlüsselungsprotokoll und Passwort in einem standardisierten statischen String zusammen (z. B. WIFI:S:GuestLounge_5G;T:WPA;P:SamplePass789;H:false;;). Kompatible Geräte und Scanner-Apps können die Daten parsen und eine Bestätigung zum Beitreten anzeigen.",
        "seo.landing.wifi-qr-generator.intro.text2": "Da statische WLAN-QR-Codes feste Netzwerkparameter direkt in der Matrix speichern, erfolgt die Verarbeitung lokal im Speicher und auf dem Scan-Gerät – ohne Übertragung an Server. Der Code hat keinen integrierten Ablauf-Timer dieser Plattform.",
        "seo.landing.wifi-qr-generator.intro.highlight": "Clientseitige statische Kodierung. Feste Netzwerkparameter werden ohne Zwischenserver direkt in der Matrix gespeichert.",
        "seo.landing.wifi-qr-generator.benefits.title": "Wichtigste Funktionen und technische Daten",
        "seo.landing.wifi-qr-generator.benefits.desc": "Verstehen Sie die Nutzdatenstruktur, unterstützte Verschlüsselungsmodi und Betriebsmerkmale statischer WLAN-QR-Codes.",
        "seo.landing.wifi-qr-generator.benefits.items.0.title": "Nahtlose Verbindung für Gäste",
        "seo.landing.wifi-qr-generator.benefits.items.0.desc": "Keine manuelle Passworteingabe mehr. Kompatible Geräte zeigen eine Bestätigung zum Beitreten an.",
        "seo.landing.wifi-qr-generator.benefits.items.1.title": "Standardisierte Protokollschemata",
        "seo.landing.wifi-qr-generator.benefits.items.1.desc": "Unterstützt WPA/WPA2/WPA3 Personal (T:WPA), WEP (T:WEP) und offene Netzwerke (T:nopass).",
        "seo.landing.wifi-qr-generator.benefits.items.2.title": "Lokale Generierung & Datenschutz",
        "seo.landing.wifi-qr-generator.benefits.items.2.desc": "Zugangsdaten verlassen Ihren Browser nie. Die QR-Matrix wird lokal im Arbeitsspeicher berechnet.",
        "seo.landing.wifi-qr-generator.benefits.items.3.title": "Individuelles Design & Vektor-Druckqualität",
        "seo.landing.wifi-qr-generator.benefits.items.3.desc": "Passen Sie Farben, Ecken und Muster an. Exportieren Sie druckfertige SVG-, PDF- oder PNG-Dateien.",
        "seo.landing.wifi-qr-generator.benefits.items.4.title": "Feste Daten ohne Ablaufzeit",
        "seo.landing.wifi-qr-generator.benefits.items.4.desc": "Statische Codes speichern unveränderliche Daten ohne Ablauf-Timer oder Serverabhängigkeiten.",
        "seo.landing.wifi-qr-generator.features.title": "Technische Architektur & Gerätekompatibilität",
        "seo.landing.wifi-qr-generator.features.desc": "Wichtige Hinweise zu Scanner-Berechtigungen und Verschlüsselungsstandards.",
        "seo.landing.wifi-qr-generator.features.items.0.title": "Geräte- und App-abhängige Verbindungsabfragen",
        "seo.landing.wifi-qr-generator.features.items.0.desc": "Native Kamera-Apps und Betriebssysteme (wie moderne iOS- und Android-Versionen) zeigen vor dem Verbinden eine Bestätigung an. Das genaue Verhalten hängt vom Gerätehersteller und den Berechtigungen der Scanner-App ab.",
        "seo.landing.wifi-qr-generator.features.items.1.title": "WPA2/WPA3 Übergangsmodus-Kompatibilität",
        "seo.landing.wifi-qr-generator.features.items.1.desc": "Der Generator nutzt das Standard-Schema T:WPA, das von WPA2-PSK und gemischten WPA2/WPA3 Personal Netzwerken unterstützt wird. Reine WPA3-SAE-Kompatibilität hängt vom Gerät ab.",
        "seo.landing.wifi-qr-generator.features.items.2.title": "Versteckte Netzwerke (H:true)",
        "seo.landing.wifi-qr-generator.features.items.2.desc": "Bei Netzwerken ohne SSID-Broadcast fügt der Generator H:true hinzu, damit Scanner gezielt danach suchen.",
        "seo.landing.wifi-qr-generator.features.items.3.title": "Klartext-Matrix vs. Funkverschlüsselung",
        "seo.landing.wifi-qr-generator.features.items.3.desc": "Das Passwort ist im QR-Code als Klartext gespeichert (WIFI:S:...;T:...;P:...;;). Die Funkverschlüsselung hängt von der Router-Konfiguration ab.",
        "seo.landing.wifi-qr-generator.features.items.4.title": "Unveränderliche gedruckte Daten",
        "seo.landing.wifi-qr-generator.features.items.4.desc": "WLAN-Zugangsdaten sind fest in das gedruckte Muster eingebettet. Bei Router-Passwortänderungen muss ein neuer Code erstellt werden.",
        "seo.landing.wifi-qr-generator.faqs.0.q": "Ist dieser kostenlose WLAN-QR-Code-Generator privat und lokal?",
        "seo.landing.wifi-qr-generator.faqs.0.a": "Ja. Die Matrixberechnung erfolgt in Ihrem lokalen Browserspeicher. SSID und Passwort werden nicht an unsere Server gesendet.",
        "seo.landing.wifi-qr-generator.faqs.1.q": "Warum verbinden sich nicht alle Geräte automatisch beim Scannen?",
        "seo.landing.wifi-qr-generator.faqs.1.a": "Die meisten nativen Kamera-Apps fordern eine Bestätigung vor dem Beitritt an. Einige Drittanbieter-Apps zeigen nur den Rohdatenstring an.",
        "seo.landing.wifi-qr-generator.faqs.2.q": "Sind WLAN-QR-Codes statisch oder dynamisch?",
        "seo.landing.wifi-qr-generator.faqs.2.a": "WLAN-QR-Codes sind immer statisch. Daten sind fest im 2D-Muster eingebettet und haben kein Ablaufdatum.",
        "seo.landing.wifi-qr-generator.faqs.3.q": "Ist das WLAN-Passwort im QR-Code geschützt?",
        "seo.landing.wifi-qr-generator.faqs.3.a": "Nein. Die Zugangsdaten sind als Klartext im Barcode gespeichert (z. B. WIFI:S:SSID;T:WPA;P:PASSWORD;;).",
        "seo.landing.wifi-qr-generator.faqs.4.q": "Funktioniert WPA3 auf allen mobilen Scannern?",
        "seo.landing.wifi-qr-generator.faqs.4.a": "Die T:WPA-Syntax wird im WPA2- und WPA2/WPA3-Mischbetrieb breit unterstützt. Reine WPA3-SAE-Netzwerke erfordern kompatible Scanner.",
        "seo.landing.wifi-qr-generator.faqs.5.q": "Funktioniert der QR-Code für versteckte SSIDs?",
        "seo.landing.wifi-qr-generator.faqs.5.a": "Ja, durch H:true suchen kompatible Geräte gezielt nach dem nicht-sendenden Netzwerknamen.",
        "seo.landing.wifi-qr-generator.faqs.6.q": "Aktualisiert sich der Code bei Router-Passwortänderung?",
        "seo.landing.wifi-qr-generator.faqs.6.a": "Nein. Da die Daten fest im Muster eingebettet sind, muss bei Passwortänderung ein neuer Code erstellt werden.",
        "seo.landing.wifi-qr-generator.faqs.7.q": "Kann ich das Design meines WLAN-QR-Codes anpassen?",
        "seo.landing.wifi-qr-generator.faqs.7.a": "Ja. Farben, Ecken, Muster und Logos können unter Beibehaltung der Fehlerkorrektur angepasst werden.",
        "seo.landing.wifi-qr-generator.cta.title": "Erstellen Sie jetzt Ihren individuellen WLAN-QR-Code",
        "seo.landing.wifi-qr-generator.cta.subtitle": "Erstellen Sie statische WLAN-Barcodes mit lokaler Berechnung und Vektorexporten.",
        "seo.landing.wifi-qr-generator.cta.buttonText": "WLAN-Code erstellen",
        "aeo.landing.wifi-qr-generator.quickDefinition": "Ein WLAN-QR-Code ist ein statischer 2D-Matrix-Barcode, der Konfigurationsparameter für drahtlose Netzwerke (SSID, Sicherheitsprotokoll, Passwort, verstecktes Flag) nach dem WIFI-URI-Standard kodiert.",
        "aeo.landing.wifi-qr-generator.aiSummary50": "Ein WLAN-QR-Code ist ein statischer 2D-Barcode, der SSID, Sicherheitstyp und Passwort speichert. Kompatible Geräte zeigen beim Scannen eine Bestätigung zum Beitritt an.",
        "aeo.landing.wifi-qr-generator.whatIsIt": "Ein standardisierter statischer QR-Code, der WLAN-Zugangsdaten direkt in einer Matrix nach dem WIFI:-Protokoll kodiert.",
        "aeo.landing.wifi-qr-generator.whenToUse": "Ideal für Gäste, Kunden oder Mitarbeiter, um sich ohne manuelle Passworteingabe mit dem WLAN zu verbinden.",
        "aeo.landing.wifi-qr-generator.benefits.0": "Ermöglicht kompatiblen Geräten, Zugangsdaten einzulesen und ohne Tippen beizutreten.",
        "aeo.landing.wifi-qr-generator.benefits.1": "Kodiert Zugangsdaten lokal im standardisierten WIFI:-Format.",
        "aeo.landing.wifi-qr-generator.benefits.2": "Verarbeitet Daten vollständig im Browserspeicher ohne Serverübertragung.",
        "aeo.landing.wifi-qr-generator.benefits.3": "Exportiert in Vektorformate (SVG, PDF) und hochauflösendes PNG.",
        "aeo.landing.wifi-qr-generator.commonMistakes.0": "Die Annahme, der QR-Code verschlüssele das Passwort; Daten sind Klartext in der Matrix.",
        "aeo.landing.wifi-qr-generator.commonMistakes.1": "Die Erwartung automatischer Hintergrundverbindungen ohne Bestätigungsabfrage.",
        "aeo.landing.wifi-qr-generator.commonMistakes.2": "Die Annahme, reine WPA3-SAE-Netzwerke funktionierten auf allen älteren Scannern.",
        "aeo.landing.wifi-qr-generator.commonMistakes.3": "Zu vergessen, dass Passwortänderungen am Router bestehende Druckcodes ungültig machen.",
        "aeo.landing.wifi-qr-generator.bestPractices.0": "Testen Sie den Scan mit iOS- und Android-Kameras vor dem Drucken.",
        "aeo.landing.wifi-qr-generator.bestPractices.1": "Achten Sie auf hohen optischen Kontrast und Fehlerkorrektur Level M oder Q.",
        "aeo.landing.wifi-qr-generator.bestPractices.2": "Halten Sie SSID und Passwort angemessen kurz für eine gut lesbare Matrix.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.0": "WLAN-QR-Codes sind statisch und speichern Daten als Klartext im 2D-Muster.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.1": "Verbindungsabfragen hängen vom Betriebssystem und den Scanner-Berechtigungen ab.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.2": "Änderungen an Routerdaten erfordern die Neuerstellung des QR-Codes.",
        "aeo.landing.wifi-qr-generator.faqs.0.q": "Verbindet das Scannen automatisch?",
        "aeo.landing.wifi-qr-generator.faqs.0.a": "Moderne Geräte fordern in der Regel eine Bestätigung des Nutzers an.",
        "aeo.landing.wifi-qr-generator.faqs.1.q": "Ist das WLAN-Passwort für Scannende unsichtbar?",
        "aeo.landing.wifi-qr-generator.faqs.1.a": "Nein. Die Matrix speichert das Passwort als Klartext.",
        "aeo.landing.wifi-qr-generator.faqs.2.q": "Was passiert bei einer Passwortänderung im Router?",
        "aeo.landing.wifi-qr-generator.faqs.2.a": "Der alte QR-Code wird unbrauchbar und muss neu erstellt werden.",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.entityType": "Statischer 2D-Barcode (ISO/IEC 18004 konform)",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.protocolStandard": "WIFI URI-Schema (WIFI:S:...;T:...;P:...;H:...;;)",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.clientCompatibility": "iOS 11+, Android 10+, moderne Barcode-Apps",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.primaryUseCase": "WLAN-Beitritt für Gäste ohne manuelles Eintippen des Passworts",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.offlineCapability": "100% clientseitige Matrixberechnung und lokales Parsen"
    },
    "es": {
        "seo.landing.wifi-qr-generator.seoTitle": "Generador de Códigos QR para WiFi Gratis | Conectar sin Escribir la Contraseña",
        "seo.landing.wifi-qr-generator.metaDescription": "Genere códigos QR de WiFi personalizados gratis. Permita a sus invitados escanear y conectarse a su red local sin escribir la contraseña.",
        "seo.landing.wifi-qr-generator.keyword": "generador de codigos qr wifi gratis",
        "seo.landing.wifi-qr-generator.h1": "Generador de Códigos QR para WiFi Gratis",
        "seo.landing.wifi-qr-generator.intro.title": "Conexión inalámbrica instantánea mediante código QR estático",
        "seo.landing.wifi-qr-generator.intro.text1": "Escribir contraseñas largas manualmente es lento y propenso a errores. Nuestro generador gratuito codifica el nombre de red (SSID), protocolo y contraseña en una cadena estática estandarizada (ej. WIFI:S:GuestLounge_5G;T:WPA;P:SamplePass789;H:false;;). Dispositivos compatibles pueden analizarla y mostrar una confirmación para unirse a la red.",
        "seo.landing.wifi-qr-generator.intro.text2": "Al ser estático, almacena los parámetros directamente en la matriz visual, procesándose en la memoria local del cliente y del dispositivo de escaneo sin enviar datos a nuestros servidores. No tiene temporizador de expiración integrado en esta plataforma.",
        "seo.landing.wifi-qr-generator.intro.highlight": "Codificación estática del lado del cliente. Los parámetros fijos se almacenan directamente en la matriz sin servidores intermediarios.",
        "seo.landing.wifi-qr-generator.benefits.title": "Capacidades principales y especificaciones técnicas",
        "seo.landing.wifi-qr-generator.benefits.desc": "Estructura de datos y características de los códigos QR WiFi estáticos.",
        "seo.landing.wifi-qr-generator.benefits.items.0.title": "Conexión fluida para invitados",
        "seo.landing.wifi-qr-generator.benefits.items.0.desc": "Elimina la escritura manual de contraseñas complejas. Los dispositivos compatibles muestran un aviso para unirse.",
        "seo.landing.wifi-qr-generator.benefits.items.1.title": "Esquemas de protocolo estándar",
        "seo.landing.wifi-qr-generator.benefits.items.1.desc": "Soporta WPA/WPA2/WPA3 Personal (T:WPA), WEP (T:WEP) y redes abiertas (T:nopass).",
        "seo.landing.wifi-qr-generator.benefits.items.2.title": "Generación local y privacidad total",
        "seo.landing.wifi-qr-generator.benefits.items.2.desc": "Los datos nunca salen de su navegador. La matriz QR se genera en la memoria local.",
        "seo.landing.wifi-qr-generator.benefits.items.3.title": "Diseño personalizado y exportación vectorial",
        "seo.landing.wifi-qr-generator.benefits.items.3.desc": "Personalice colores, esquinas y patrones. Exporte en SVG, PDF o PNG de alta resolución.",
        "seo.landing.wifi-qr-generator.benefits.items.4.title": "Datos fijos sin caducidad",
        "seo.landing.wifi-qr-generator.benefits.items.4.desc": "Los códigos estáticos almacenan datos fijos sin temporizadores de caducidad ni servidores intermedios.",
        "seo.landing.wifi-qr-generator.features.title": "Arquitectura técnica y compatibilidad de dispositivos",
        "seo.landing.wifi-qr-generator.features.desc": "Consideraciones sobre permisos de escáner y estándares de cifrado.",
        "seo.landing.wifi-qr-generator.features.items.0.title": "Avisos de conexión según dispositivo y app",
        "seo.landing.wifi-qr-generator.features.items.0.desc": "Las cámaras nativas de iOS y Android suelen mostrar una confirmación antes de conectarse. El comportamiento exacto depende del fabricante y permisos.",
        "seo.landing.wifi-qr-generator.features.items.1.title": "Compatibilidad con modo de transición WPA2/WPA3",
        "seo.landing.wifi-qr-generator.features.items.1.desc": "Utiliza el esquema estándar T:WPA soportado en WPA2 y redes mixtas. La compatibilidad pura con WPA3-SAE depende del dispositivo.",
        "seo.landing.wifi-qr-generator.features.items.2.title": "Redes ocultas (H:true)",
        "seo.landing.wifi-qr-generator.features.items.2.desc": "Para redes sin difusión de SSID, el generador añade H:true para que los escáneres compatibles la localicen.",
        "seo.landing.wifi-qr-generator.features.items.3.title": "Matriz en texto plano vs. Cifrado inalámbrico",
        "seo.landing.wifi-qr-generator.features.items.3.desc": "La contraseña se almacena como texto plano en el código. El cifrado de transmisión inalámbrica depende del router.",
        "seo.landing.wifi-qr-generator.features.items.4.title": "Inmutabilidad de datos impresos",
        "seo.landing.wifi-qr-generator.features.items.4.desc": "Los datos están fijados en el código impreso. Si cambia la clave del router, debe generar un código nuevo.",
        "seo.landing.wifi-qr-generator.faqs.0.q": "¿Este generador es privado y local?",
        "seo.landing.wifi-qr-generator.faqs.0.a": "Sí. El cálculo de la matriz se realiza en el navegador y no se envían datos a ningún servidor.",
        "seo.landing.wifi-qr-generator.faqs.1.q": "¿Por qué no todos los dispositivos se conectan automáticamente?",
        "seo.landing.wifi-qr-generator.faqs.1.a": "La mayoría de dispositivos solicitan confirmación al usuario antes de unirse a la red.",
        "seo.landing.wifi-qr-generator.faqs.2.q": "¿Los códigos QR de WiFi son estáticos o dinámicos?",
        "seo.landing.wifi-qr-generator.faqs.2.a": "Son estáticos. Los datos se integran directamente en el patrón sin fecha de caducidad.",
        "seo.landing.wifi-qr-generator.faqs.3.q": "¿La contraseña está oculta dentro del código QR?",
        "seo.landing.wifi-qr-generator.faqs.3.a": "No. Se almacena como texto plano (ej. WIFI:S:SSID;T:WPA;P:PASSWORD;;).",
        "seo.landing.wifi-qr-generator.faqs.4.q": "¿Funciona WPA3 en todos los escáneres?",
        "seo.landing.wifi-qr-generator.faqs.4.a": "El esquema T:WPA es compatible con WPA2 y redes mixtas. WPA3 puro depende del firmware.",
        "seo.landing.wifi-qr-generator.faqs.5.q": "¿Funciona con redes ocultas?",
        "seo.landing.wifi-qr-generator.faqs.5.a": "Sí, al habilitar la opción se incluye H:true en la carga útil.",
        "seo.landing.wifi-qr-generator.faqs.6.q": "¿Se actualiza si cambio la clave del router?",
        "seo.landing.wifi-qr-generator.faqs.6.a": "No. Al ser estático, cambiar la clave requiere crear un nuevo código.",
        "seo.landing.wifi-qr-generator.faqs.7.q": "¿Puedo personalizar el diseño?",
        "seo.landing.wifi-qr-generator.faqs.7.a": "Sí, puede cambiar colores, esquinas, estilos y logotipos manteniendo la corrección de errores.",
        "seo.landing.wifi-qr-generator.cta.title": "Genere su código QR de WiFi personalizado ahora",
        "seo.landing.wifi-qr-generator.cta.subtitle": "Cree códigos de red inalámbrica estáticos con cálculo local y exportación vectorial.",
        "seo.landing.wifi-qr-generator.cta.buttonText": "Crear código WiFi",
        "aeo.landing.wifi-qr-generator.quickDefinition": "Un código QR de WiFi es un código de barras matricial 2D estático que codifica parámetros de red inalámbrica (SSID, protocolo, contraseña y red oculta) bajo el esquema WIFI URI estándar.",
        "aeo.landing.wifi-qr-generator.aiSummary50": "Un código QR de WiFi es un código 2D estático que almacena SSID, seguridad y contraseña. Los dispositivos compatibles muestran un aviso para unirse a la red.",
        "aeo.landing.wifi-qr-generator.whatIsIt": "Código QR estático estandarizado que codifica datos de red WiFi según el protocolo WIFI:.",
        "aeo.landing.wifi-qr-generator.whenToUse": "Para conectar invitados o clientes sin necesidad de que escriban contraseñas complejas.",
        "aeo.landing.wifi-qr-generator.benefits.0": "Permite unirse a la red sin escribir la contraseña manualmente.",
        "aeo.landing.wifi-qr-generator.benefits.1": "Codificación local bajo el esquema estandarizado WIFI:.",
        "aeo.landing.wifi-qr-generator.benefits.2": "Procesamiento en memoria sin enviar claves a servidores.",
        "aeo.landing.wifi-qr-generator.benefits.3": "Exportación en formatos vectoriales (SVG, PDF) y PNG.",
        "aeo.landing.wifi-qr-generator.commonMistakes.0": "Creer que el QR cifra la contraseña; se guarda como texto plano en el código.",
        "aeo.landing.wifi-qr-generator.commonMistakes.1": "Esperar conexión automática sin confirmación del usuario.",
        "aeo.landing.wifi-qr-generator.commonMistakes.2": "Asumir compatibilidad universal con WPA3 puro en lectores antiguos.",
        "aeo.landing.wifi-qr-generator.commonMistakes.3": "Olvidar que cambiar la clave del router inutiliza los códigos impresos.",
        "aeo.landing.wifi-qr-generator.bestPractices.0": "Pruebe el escaneo con iOS y Android antes de imprimir.",
        "aeo.landing.wifi-qr-generator.bestPractices.1": "Asegure buen contraste y use nivel de corrección de error M o Q.",
        "aeo.landing.wifi-qr-generator.bestPractices.2": "Mantenga el SSID y la contraseña concisos para un código fácil de leer.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.0": "Los códigos son estáticos y guardan los datos en texto plano dentro de la matriz 2D.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.1": "Los avisos de conexión dependen del sistema operativo y de los permisos.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.2": "Cambiar la configuración del router exige generar un nuevo código.",
        "aeo.landing.wifi-qr-generator.faqs.0.q": "¿Se conecta automáticamente al escanear?",
        "aeo.landing.wifi-qr-generator.faqs.0.a": "La mayoría de dispositivos muestran un aviso de confirmación antes de conectarse.",
        "aeo.landing.wifi-qr-generator.faqs.1.q": "¿La contraseña está oculta?",
        "aeo.landing.wifi-qr-generator.faqs.1.a": "No, está en texto plano dentro de la matriz.",
        "aeo.landing.wifi-qr-generator.faqs.2.q": "¿Qué pasa si cambio la contraseña de la red?",
        "aeo.landing.wifi-qr-generator.faqs.2.a": "El código antiguo deja de funcionar y debe generar uno nuevo.",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.entityType": "Código de barras 2D estático (conforme a ISO/IEC 18004)",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.protocolStandard": "Esquema WIFI URI (WIFI:S:...;T:...;P:...;H:...;;)",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.clientCompatibility": "iOS 11+, Android 10+, apps modernas",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.primaryUseCase": "Conexión a redes WiFi sin escribir la contraseña",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.offlineCapability": "100% cálculo en el cliente y análisis local"
    },
    "fr": {
        "seo.landing.wifi-qr-generator.seoTitle": "Générateur de Code QR WiFi Gratuit | Se Connecter Sans Saisir le Mot de Passe",
        "seo.landing.wifi-qr-generator.metaDescription": "Générez des codes QR WiFi personnalisés gratuitement. Permettez à vos invités de se connecter sans avoir à saisir le mot de passe.",
        "seo.landing.wifi-qr-generator.keyword": "generateur code qr wifi gratuit",
        "seo.landing.wifi-qr-generator.h1": "Générateur de Code QR WiFi Gratuit",
        "seo.landing.wifi-qr-generator.intro.title": "Connexion sans fil instantanée via code QR WiFi statique",
        "seo.landing.wifi-qr-generator.intro.text1": "Saisir manuellement des mots de passe complexes est fastidieux. Notre générateur gratuit encode le nom du réseau (SSID), le protocole et le mot de passe dans une chaîne statique standardisée (ex. WIFI:S:GuestLounge_5G;T:WPA;P:SamplePass789;H:false;;). Les appareils compatibles peuvent lire la charge utile et afficher une invite pour rejoindre le réseau.",
        "seo.landing.wifi-qr-generator.intro.text2": "Comme les codes QR WiFi statiques stockent les paramètres directement dans la matrice, le traitement s'effectue localement dans le navigateur et sur l'appareil de scan, sans envoi vers nos serveurs. Le code ne comporte aucun minuteur d'expiration sur cette plateforme.",
        "seo.landing.wifi-qr-generator.intro.highlight": "Encodage statique côté client. Les paramètres fixes du réseau sont stockés directement dans la matrice sans serveur intermédiaire.",
        "seo.landing.wifi-qr-generator.benefits.title": "Fonctionnalités principales et spécifications techniques",
        "seo.landing.wifi-qr-generator.benefits.desc": "Structure de charge utile et caractéristiques des codes QR WiFi statiques.",
        "seo.landing.wifi-qr-generator.benefits.items.0.title": "Connexion fluide des invités",
        "seo.landing.wifi-qr-generator.benefits.items.0.desc": "Élimine la saisie manuelle de mot de passe. Les appareils compatibles affichent une invite pour rejoindre le réseau.",
        "seo.landing.wifi-qr-generator.benefits.items.1.title": "Schémas de protocole standardisés",
        "seo.landing.wifi-qr-generator.benefits.items.1.desc": "Prend en charge WPA/WPA2/WPA3 Personal (T:WPA), WEP (T:WEP) et réseaux ouverts (T:nopass).",
        "seo.landing.wifi-qr-generator.benefits.items.2.title": "Génération locale et confidentialité totale",
        "seo.landing.wifi-qr-generator.benefits.items.2.desc": "Les identifiants ne quittent jamais votre navigateur. La matrice est calculée en mémoire locale.",
        "seo.landing.wifi-qr-generator.benefits.items.3.title": "Design personnalisé et qualité vectorielle",
        "seo.landing.wifi-qr-generator.benefits.items.3.desc": "Personnalisez couleurs, angles et motifs. Exportez en SVG, PDF ou PNG haute résolution.",
        "seo.landing.wifi-qr-generator.benefits.items.4.title": "Données fixes sans expiration",
        "seo.landing.wifi-qr-generator.benefits.items.4.desc": "Les codes statiques conservent des données immuables sans dépendance envers un serveur.",
        "seo.landing.wifi-qr-generator.features.title": "Architecture technique et compatibilité des appareils",
        "seo.landing.wifi-qr-generator.features.desc": "Considérations relatives aux autorisations de scan et aux normes de chiffrement.",
        "seo.landing.wifi-qr-generator.features.items.0.title": "Invites de connexion selon l'appareil",
        "seo.landing.wifi-qr-generator.features.items.0.desc": "Les applications d'appareil photo sous iOS et Android affichent généralement une invite de confirmation avant la connexion.",
        "seo.landing.wifi-qr-generator.features.items.1.title": "Compatibilité mode de transition WPA2/WPA3",
        "seo.landing.wifi-qr-generator.features.items.1.desc": "Utilise le schéma standard T:WPA reconnu sur les réseaux WPA2 et mixtes.",
        "seo.landing.wifi-qr-generator.features.items.2.title": "Réseaux masqués (H:true)",
        "seo.landing.wifi-qr-generator.features.items.2.desc": "Pour les réseaux sans diffusion SSID, le générateur ajoute H:true pour permettre aux scanners de les cibler.",
        "seo.landing.wifi-qr-generator.features.items.3.title": "Matrice en clair vs Chiffrement radio",
        "seo.landing.wifi-qr-generator.features.items.3.desc": "Le mot de passe est stocké en texte clair dans le code. Le chiffrement réseau dépend du routeur.",
        "seo.landing.wifi-qr-generator.features.items.4.title": "Immuabilité des données imprimées",
        "seo.landing.wifi-qr-generator.features.items.4.desc": "Modifier le mot de passe du routeur rend les codes imprimés obsolètes et nécessite d'en créer un nouveau.",
        "seo.landing.wifi-qr-generator.faqs.0.q": "Ce générateur est-il privé et local ?",
        "seo.landing.wifi-qr-generator.faqs.0.a": "Oui. Le calcul de matrice s'effectue dans votre navigateur sans transmission réseau.",
        "seo.landing.wifi-qr-generator.faqs.1.q": "Pourquoi la connexion n'est-elle pas automatique sur tous les appareils ?",
        "seo.landing.wifi-qr-generator.faqs.1.a": "La plupart des systèmes d'exploitation demandent une confirmation utilisateur avant de rejoindre un réseau.",
        "seo.landing.wifi-qr-generator.faqs.2.q": "Les codes QR WiFi sont-ils statiques ou dynamiques ?",
        "seo.landing.wifi-qr-generator.faqs.2.a": "Ils sont statiques. Les identifiants sont directement intégrés dans le motif sans date d'expiration.",
        "seo.landing.wifi-qr-generator.faqs.3.q": "Le mot de passe est-il masqué dans le code QR ?",
        "seo.landing.wifi-qr-generator.faqs.3.a": "Non. Il est encodé en texte brut lisible par tout lecteur (ex. WIFI:S:SSID;T:WPA;P:PASSWORD;;).",
        "seo.landing.wifi-qr-generator.faqs.4.q": "Le protocole WPA3 fonctionne-t-il sur tous les scanners ?",
        "seo.landing.wifi-qr-generator.faqs.4.a": "Le schéma T:WPA fonctionne en WPA2 et mode mixte WPA2/WPA3. WPA3 pur dépend des appareils.",
        "seo.landing.wifi-qr-generator.faqs.5.q": "Le code fonctionne-t-il pour les SSID masqués ?",
        "seo.landing.wifi-qr-generator.faqs.5.a": "Oui, avec l'option activée, l'attribut H:true est ajouté pour cibler le réseau masqué.",
        "seo.landing.wifi-qr-generator.faqs.6.q": "Le code se met-il à jour si je change le mot de passe du routeur ?",
        "seo.landing.wifi-qr-generator.faqs.6.a": "Non. Comme les données sont statiques, il faut générer un nouveau code.",
        "seo.landing.wifi-qr-generator.faqs.7.q": "Puis-je personnaliser le design du code WiFi ?",
        "seo.landing.wifi-qr-generator.faqs.7.a": "Oui, vous pouvez ajuster les couleurs, angles, motifs et ajouter un logo tout en conservant la correction d'erreur.",
        "seo.landing.wifi-qr-generator.cta.title": "Générez votre code QR WiFi personnalisé maintenant",
        "seo.landing.wifi-qr-generator.cta.subtitle": "Créez un code barre réseau statique avec calcul local et exports vectoriels.",
        "seo.landing.wifi-qr-generator.cta.buttonText": "Créer le code WiFi",
        "aeo.landing.wifi-qr-generator.quickDefinition": "Un code QR WiFi est un code-barres matriciel 2D statique qui encode les paramètres d'un réseau sans fil (SSID, protocole, mot de passe, indicateur masqué) selon le schéma WIFI URI standard.",
        "aeo.landing.wifi-qr-generator.aiSummary50": "Un code QR WiFi est un code 2D statique stockant le SSID, la sécurité et le mot de passe. Les appareils compatibles affichent une invite pour rejoindre le réseau local.",
        "aeo.landing.wifi-qr-generator.whatIsIt": "Code QR statique standardisé encodant les identifiants WiFi selon la spécification WIFI:.",
        "aeo.landing.wifi-qr-generator.whenToUse": "Pour connecter des invités sans avoir à leur faire saisir de mot de passe.",
        "aeo.landing.wifi-qr-generator.benefits.0": "Permet de rejoindre le réseau sans saisie manuelle de mot de passe.",
        "aeo.landing.wifi-qr-generator.benefits.1": "Encodage local selon la norme WIFI: standard.",
        "aeo.landing.wifi-qr-generator.benefits.2": "Traitement direct en mémoire sans envoi de clé sur serveur.",
        "aeo.landing.wifi-qr-generator.benefits.3": "Exportation vectorielle (SVG, PDF) et raster PNG.",
        "aeo.landing.wifi-qr-generator.commonMistakes.0": "Croire que le QR chiffre le mot de passe ; il est stocké en texte clair.",
        "aeo.landing.wifi-qr-generator.commonMistakes.1": "Espérer une connexion automatique sans invite de confirmation.",
        "aeo.landing.wifi-qr-generator.commonMistakes.2": "Supposer que le WPA3 pur fonctionne sur tous les anciens scanners.",
        "aeo.landing.wifi-qr-generator.commonMistakes.3": "Oublier que modifier la clé du routeur rend caducs les codes imprimés.",
        "aeo.landing.wifi-qr-generator.bestPractices.0": "Testez le scan avec iOS et Android avant impression.",
        "aeo.landing.wifi-qr-generator.bestPractices.1": "Assurez un contraste élevé et choisissez le niveau de correction M ou Q.",
        "aeo.landing.wifi-qr-generator.bestPractices.2": "Gardez le SSID et le mot de passe concis pour une matrice aérée.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.0": "Les codes QR WiFi sont statiques et stockent les données en clair dans la matrice 2D.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.1": "Les invites de connexion dépendent du système et des autorisations.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.2": "Tout changement de routeur nécessite la création d'un nouveau code.",
        "aeo.landing.wifi-qr-generator.faqs.0.q": "Le scan connecte-t-il automatiquement ?",
        "aeo.landing.wifi-qr-generator.faqs.0.a": "La plupart des appareils demandent une confirmation utilisateur.",
        "aeo.landing.wifi-qr-generator.faqs.1.q": "Le mot de passe WiFi est-il masqué ?",
        "aeo.landing.wifi-qr-generator.faqs.1.a": "Non, il est lisible en texte brut dans la matrice.",
        "aeo.landing.wifi-qr-generator.faqs.2.q": "Que se passe-t-il si je change le mot de passe WiFi ?",
        "aeo.landing.wifi-qr-generator.faqs.2.a": "Le code existant devient inopérant et vous devez en générer un nouveau.",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.entityType": "Code-barres 2D statique (conforme ISO/IEC 18004)",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.protocolStandard": "Schéma WIFI URI (WIFI:S:...;T:...;P:...;H:...;;)",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.clientCompatibility": "iOS 11+, Android 10+, applications modernes",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.primaryUseCase": "Connexion sans fil pour invités sans saisie de mot de passe",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.offlineCapability": "100% calcul côté client et décodage local"
    }
}

for loc, d_keys in wifi_locales_data.items():
    with open(f"src/locales/{loc}.json", "r") as f:
        d = json.load(f)
    d.update(d_keys)
    with open(f"src/locales/{loc}.json", "w") as f:
        json.dump(d, f, indent=2, ensure_ascii=False)
    print(f"Updated {loc}.json with full 80 keys")
