const fs = require('fs');
const path = require('path');

const arPath = path.join(__dirname, '../src/locales/ar.json');
const ar = JSON.parse(fs.readFileSync(arPath, 'utf8'));

const translations = {
  // Footer
  "footer.aboutUs": "من نحن",
  "footer.academy": "الأكاديمية التعليمية",
  "footer.accessibility": "سهولة الوصول وشمولية الاستخدام",
  "footer.aiGateway": "بوابة الذكاء الاصطناعي للمؤسسات والمطورين",
  "footer.blog": "المدونة التقنية",
  "footer.brandAssets": "أصول الهوية البصرية",
  "footer.brandDesc": "صمم رموز QR مخصصة وعالية المقاومة للخطأ بتدرجات ألوان حديثة وأشكال نقاط متميزة وشعارات مدمجة للعلامات التجارية. متكامل مع تتبع الروابط الديناميكية المختصرة وتحليلات المسح المباشرة في الوقت الفعلي.",
  "footer.brandName": "FreeQRBarcodes.com",
  "footer.careers": "الوظائف وفرص العمل",
  "footer.changelog": "سجل التحديثات",
  "footer.compare": "المقارنات والبدائل",
  "footer.contactUs": "اتصل بنا",
  "footer.copyright": "© 2026 FreeQRBarcodes.com. بنية تحتية سحابية ومحلية آمنة ومعتمدة بالكامل.",
  "footer.dataProcessing": "اتفاقية معالجة البيانات",
  "footer.directoryTitle": "حلول رموز QR المجانية والمتخصصة",
  "footer.editorialPolicy": "السياسة التحريرية",
  "footer.embed": "شارة التضمين في المواقع",
  "footer.faq": "الأسئلة الشائعة",
  "footer.glossary": "قاموس المصطلحات الفنية",
  "footer.guides": "الأدلة والشروحات الشاملة",
  "footer.i18nDashboard": "لوحة تحكم التدويل وضمان جودة الترجمة",
  "footer.industries": "القطاعات والصناعات",
  "footer.mediaKit": "الملف الصحفي والإعلامي",
  "footer.platformSuite": "مجموعة أدوات المنصة",
  "footer.press": "المركز الإعلامي والأخبار",
  "footer.privacyPolicy": "سياسة الخصوصية",
  "footer.releaseNotes": "ملاحظات الإصدارات",
  "footer.researchMethodology": "منهجية البحث والاختبار",
  "footer.resources": "المصادر والمعرفة",
  "footer.security": "الأمان وحماية البيانات",
  "footer.solutionBusinessCard": "بطاقات العمل الرقمية (vCard)",
  "footer.solutionEmail": "رمز QR للبريد الإلكتروني",
  "footer.solutionFacebook": "رمز QR لصفحات فيسبوك",
  "footer.solutionInstagram": "رمز QR لحسابات إنستغرام",
  "footer.solutionPdf": "رمز QR لملفات ومستندات PDF",
  "footer.solutionRestaurant": "رمز QR لقوائم المطاعم الرقمية",
  "footer.solutionSms": "رمز QR لرسائل SMS النصية",
  "footer.solutionUrl": "رمز QR لروابط المواقع الإلكترونية",
  "footer.solutionVcard": "بطاقة هوية جهات الاتصال vCard",
  "footer.solutionWhatsapp": "رمز QR لمحادثات واتساب المباشرة",
  "footer.solutionWifi": "رمز QR للاتصال بشبكات الواي فاي",
  "footer.solutionYoutube": "رمز QR لقنوات ومقاطع يوتيوب",
  "footer.solutions": "الحلول المخصصة",
  "footer.systemStatus": "حالة النظام وتوافر الخدمات",
  "footer.templates": "قوالب التصميم الجاهزة",
  "footer.terms": "شروط الاستخدام والخدمة",
  "footer.tutorials": "الدروس التعليمية المصورة",
  "footer.useCases": "حالات الاستخدام العملية",
  "footer.whyUs": "لماذا تختار FreeQRBarcodes.com؟",

  // Gateway
  "gateway.activeSecured": "اتصال آمن ونشط",
  "gateway.assistantDesc": "مساعد ذكاء اصطناعي فائق السرعة لدعم المطورين وإجراء الترجمات التقنية الآمنة في الوقت الفعلي.",
  "gateway.assistantTitle": "المساعد المتقدم للمطورين",
  "gateway.auditResultsTitle": "نتائج تدقيق التوافق والأمان",
  "gateway.auditSimulatorDesc": "محاكاة فورية لفحص تماسك النصوص والتحقق من التوافق البرمجي للترجمات بدون تسريب للبيانات.",
  "gateway.auditSimulatorTitle": "محاكي التدقيق واختبار الجودة",
  "gateway.backButton": "الرجوع للوحة المطورين",
  "gateway.badge": "بوابة واجهات برمجة التطبيقات للمؤسسات",
  "gateway.coPilotStatus": "حالة المساعد الآلي: نشط ومستقر",
  "gateway.desc": "بيئة مطورين متكاملة للمؤسسات تتيح الوصول الآمن للأدوات البرمجية، وتحليل أداء النماذج، والترجمة الفورية المشفرة.",
  "gateway.llmLatency": "زمن استجابة النموذج: {{ms}} مللي ثانية",
  "gateway.runAuditBtn": "تشغيل فحص التدقيق البرمجي",
  "gateway.sourceLabel": "النص المصدري للاختبار",
  "gateway.sourcePlaceholder": "أدخل النص البرمجي أو العبارة المراد تدقيقها أو ترجمتها...",
  "gateway.targetLanguageLabel": "اللغة المستهدفة",
  "gateway.title": "بوابة المطورين والذكاء الاصطناعي",
  "gateway.tlsEnforced": "تشفير TLS مفروض بالكامل",
  "gateway.translateBtn": "ترجمة وتدقيق فوري",
  "gateway.translatedOutput": "المخرجات المترجمة والمدققة",
  "gateway.translating": "جارٍ المعالجة والترجمة الآمنة...",

  // Growth
  "growth.activityAlerts": "تنبيهات النشاط المباشر",
  "growth.activityAlertsCount": "{{count}} تنبيه نشط",
  "growth.activityCenterTitle": "مركز النشاطات والتفاعل",
  "growth.activityCenterTooltip": "متابعة التحديثات والأنشطة في الوقت الفعلي",
  "growth.affiliateClicks": "نقرات الإحالة المسجلة",
  "growth.anyMobile": "أي هاتف ذكي حديث",
  "growth.asideTitle": "رؤى النمو والشراكة",
  "growth.backButton": "العودة للرئيسية",
  "growth.badge": "برنامج نمو المجتمع والمكافآت",
  "growth.badgeFeatureRelease": "إصدار ميزات جديدة",
  "growth.badgePerformanceUpdate": "تحسينات الأداء والسرعة",
  "growth.bioPlaceholder": "اكتب نبذة مهنية مختصرة عنك أو عن شركتك...",
  "growth.budgetLabel": "الميزانية المتوقعة (USD)",
  "growth.builderDesc": "أداة بناء مخصصة تمنحك تحكماً شاملاً لتطوير وتخصيص رموز QR وحملات الترويج بكفاءة فائقة.",
  "growth.builderTitle": "مستودع أدوات التخصيص",
  "growth.cancel": "إلغاء",
  "growth.cancelEdit": "إلغاء التعديل",
  "growth.caseStudyDesc": "اطلع على كيفية استفادة المؤسسات والعلامات التجارية الرائدة من منصتنا لتوسيع نطاق تفاعل عملائها.",
  "growth.caseStudyHeader": "دراسة حالة معتمدة",
  "growth.caseStudyReport": "تقرير تحليل الأداء والعائد الاستثماري",
  "growth.caseStudyText": "شاهد نتائج واقعية وتجارب موثقة لاستخدام حلول رموز QR عالية الدقة في قيادة التحول الرقمي.",
  "growth.caseStudyTitle": "قصص النجاح ودراسات الحالة",
  "growth.category": "الفئة",
  "growth.categoryBrainstorm": "عصف ذهني وأفكار جديدة",
  "growth.categoryFeature": "طلب ميزة برمجية",
  "growth.categoryLabel": "فئة الاقتراح",
  "growth.categoryTemplate": "طلب قالب تصميم",
  "growth.close": "إغلاق",
  "growth.codingPhase": "مرحلة التطوير البرمجي",
  "growth.commentPlaceholder": "أضف تعليقك أو رؤيتك الفنية هنا...",
  "growth.communityDesc": "شارك في بناء مستقبل المنصة، وقدم اقتراحاتك، وصوت على الميزات القادمة لتحصل على نقاط خبرة وشارات شرفية.",
  "growth.communityDescription": "مجتمع مفتوح للمصممين والمطورين والمسوقين لتبادل الأفكار وتطوير أفضل أدوات الباركود ورموز QR.",
  "growth.communityPillarBadge": "ركن المجتمع والابتكار",
  "growth.communityTitle": "مجتمع المطورين والمبتكرين",
  "growth.company": "الشركة أو المؤسسة",
  "growth.companyPlaceholder": "اسم شركتك أو علامتك التجارية",
  "growth.connectAccount": "ربط الحساب",
  "growth.connectAccountBtn": "ربط وتوثيق الحساب",
  "growth.conversionLabel": "معدل التحويل التقديري",
  "growth.copied": "تم النسخ بنجاح! ✓",
  "growth.copyLink": "نسخ الرابط",
  "growth.costPerScan": "تكلفة المسح: 0.00 $ (مجاني تماماً)",
  "growth.csatDesc": "رأيك يساعدنا في تحسين تجربة المنصة باستمرار. يرجى تقييم مستوى رضاك عن الأدوات والخدمات.",
  "growth.csatRatingLabel": "مستوى الرضا العام",
  "growth.csatTitle": "تقييم رضا المستخدمين (CSAT)",
  "growth.dbSyncError": "تعذر مزامنة البيانات السحابية، يرجى إعادة المحاولة.",
  "growth.defaultBgColor": "لون الخلفية الافتراضي",
  "growth.defaultFgColor": "لون الرمز الافتراضي",
  "growth.defaultQrType": "نوع الرمز الافتراضي",
  "growth.deployed": "تم النشر بنجاح",
  "growth.desc": "اكتشف برامج النمو، وشارك في اقتراح الميزات، وتابع خارطة طريق المنتجات، واكسب مكافآت الإحالة الحصرية.",
  "growth.descriptionLabel": "الوصف",
  "growth.descriptionPlaceholder": "قدم وصفاً واضحاً ومفصلاً...",
  "growth.detailedDescLabel": "التفاصيل والمواصفات الفنية",
  "growth.detailedDescPlaceholder": "اشرح السياق وحالة الاستخدام بالتفصيل...",
  "growth.directEmailPackage": "حزمة البريد الإلكتروني المباشرة",
  "growth.editProfile": "تعديل الملف الشخصي",
  "growth.emailPlaceholder": "بريدك الإلكتروني المهني",
  "growth.extremelyHappy": "راضٍ تماماً وممتن للغاية",
  "growth.featureModules": "الوحدات البرمجية المكتملة",
  "growth.featureModulesCount": "{{count}} وحدة مفعلة",
  "growth.feedbackOptBug": "الإبلاغ عن خطأ برمجي",
  "growth.feedbackOptBugDesc": "واجهت سلوكاً غير متوقع أو مشكلة فنية في المنصة",
  "growth.feedbackOptCompliment": "إشادة وتجربة إيجابية",
  "growth.feedbackOptComplimentDesc": "أعجبك أداء المنصة وتريد مشاركة رأيك الإيجابي",
  "growth.feedbackOptSuggestion": "اقتراح تحسين جديد",
  "growth.feedbackOptSuggestionDesc": "لديك فكرة لتطوير ميزة حالية أو إضافة جديدة",
  "growth.feedbackPlaceholder": "اكتب ملاحظاتك واقتراحاتك بكل وضوح هنا...",
  "growth.feedbackSuccessDescAnd": " و ",
  "growth.feedbackSuccessDescBadge": "شارة المساهم المميز",
  "growth.feedbackSuccessDescMid": " بالإضافة إلى ",
  "growth.feedbackSuccessDescPrefix": "شكراً جزيلاً لمساهمتك القيمة! لقد حصلت على ",
  "growth.feedbackSuccessDescSuffix": " تقديراً لمشاركتك معنا.",
  "growth.feedbackSuccessDescXp": "50 نقطة خبرة (XP)",
  "growth.feedbackSuccessTitle": "تم استلام ملاحظاتك بنجاح! 🎉",
  "growth.feedbackTextLabel": "نص الملاحظات أو الاقتراح",
  "growth.feedbackType": "نوع الملاحظات",
  "growth.feedbackTypeBug": "خلل فني",
  "growth.feedbackTypeBugDesc": "خطأ برمجي أو مشكلة في واجهة المستخدم",
  "growth.feedbackTypeCompliment": "إشادة وتقدير",
  "growth.feedbackTypeComplimentDesc": "رسالة شكر أو انطباع إيجابي",
  "growth.feedbackTypeLabel": "حدد نوع الملاحظات",
  "growth.feedbackTypeSuggestion": "اقتراح ميزة",
  "growth.feedbackTypeSuggestionDesc": "فكرة لتحسين المنصة وإضافة خيارات جديدة",
  "growth.filterAll": "جميع المقترحات",
  "growth.filterFeature": "الميزات البرمجية",
  "growth.filterFeatures": "طلبات الميزات",
  "growth.filterGeneral": "عام ونقاشات",
  "growth.filterTemplates": "قوالب التصميم",
  "growth.github": "حساب GitHub",
  "growth.githubPlaceholder": "اسم المستخدم على GitHub",
  "growth.githubProfile": "رابط حسابك على GitHub",
  "growth.highlyDissatisfied": "غير راضٍ على الإطلاق",
  "growth.level": "المستوى الحالي",
  "growth.levelCount": "المستوى {{level}}",
  "growth.linkedin": "حساب LinkedIn",
  "growth.linkedinPlaceholder": "رابط ملفك الشخصي على LinkedIn",
  "growth.linkedinUrl": "رابط LinkedIn المهني",
  "growth.loadingMessage": "جارٍ تحميل البيانات وإعداد الواجهة...",
  "growth.metricsTitle": "مؤشرات وإحصائيات النمو المباشرة",
  "growth.milestone1Desc": "قم بدعوة 3 مستخدمين للمنصة لفتح شارة المسوق الرائد وتخصيصات الألوان غير المحدودة.",
  "growth.milestone1Name": "المرحلة الأولى: المسوق المبتدئ",
  "growth.milestone2Desc": "قم بدعوة 10 مستخدمين لكسب شارة المؤثر ومضاعفة سرعة تصدير الملفات عالية الدقة.",
  "growth.milestone2Name": "المرحلة الثانية: سفير المجتمع",
  "growth.milestone3Desc": "قم بدعوة 25 مستخدماً لفتح أولوية المعالجة الحصرية وشارة الشريك الاستراتيجي مدى الحياة.",
  "growth.milestone3Name": "المرحلة الثالثة: القائد الرقمي",
  "growth.milestoneEye": "أشكال عيون QR الحصرية",
  "growth.milestoneEyeDesc": "فتح 12 نمطاً هندسياً فريداً لزوايا الرمز المخصصة.",
  "growth.milestoneSVG": "تصدير متجهات SVG غير المحدود",
  "growth.milestoneSVGDesc": "تنزيل متجهات طباعة لا نهائية الدقة بدون قيود.",
  "growth.milestoneShaders": "مؤثرات التظليل والتدرجات المتقدمة",
  "growth.milestoneShadersDesc": "الوصول إلى لوحات ألوان حصرية وتدرجات ثلاثية الأبعاد احترافية.",
  "growth.milestonesLedger": "سجل مراحل الإنجاز والمكافآت",
  "growth.netRoi": "صافي العائد على الاستثمار",
  "growth.neutral": "محايد / متوسط الرضا",
  "growth.newsletterDesc": "اشترك في نشرتنا البريدية لتصلك أحدث نصائح التصميم، وتحديثات خوارزميات المسح، والميزات الجديدة أولاً بأول.",
  "growth.newsletterSuccess": "تم اشتراكك بنجاح! مرحباً بك في مجتمعنا.",
  "growth.newsletterTitle": "النشرة الإخبارية المتخصصة",
  "growth.noAlerts": "لا توجد تنبيهات جديدة في الوقت الحالي.",
  "growth.noDiscussions": "لا توجد نقاشات نشطة في هذه الفئة بعد. كن أول من يطرح فكرة!",
  "growth.noSystemAlerts": "النظام يعمل بكفاءة تامة ولا توجد أي بلاغات.",
  "growth.optAestheticTemplate": "قالب تصميم جمالي",
  "growth.optFeatureRequest": "طلب ميزة برمجية",
  "growth.optGeneralBrainstorm": "عصف ذهني عام",
  "growth.placeholderBio": "اكتب نبذة عن اهتماماتك ومشاريعك...",
  "growth.placeholderCompany": "اسم شركتك أو مشروعك",
  "growth.placeholderGithub": "اسم المستخدم على GitHub",
  "growth.placeholderLinkedin": "رابط حسابك على LinkedIn",
  "growth.placeholderTwitter": "اسم حسابك على X / تويتر",
  "growth.postTitle": "عنوان المقترح",
  "growth.postTitleLabel": "عنوان الفكرة أو الاقتراح",
  "growth.postTitlePlaceholder": "اكتب عنواناً معبراً ومختصراً للاقتراح...",
  "growth.postingRewardMid": " و ",
  "growth.postingRewardPrefix": "اكسب ",
  "growth.postingRewardSuffix": " مقابل كل فكرة مفيدة تشاركها مع المجتمع.",
  "growth.postingRewardsAndThe": " و ",
  "growth.postingRewardsBadge": "شارة المستشار الصوتي",
  "growth.postingRewardsPrefix": "احصل على ",
  "growth.postingRewardsSuffix": " عند نشر اقتراح معتمد من فريق التطوير.",
  "growth.postingRewardsXp": "25 نقطة خبرة (XP)",
  "growth.presetsTitle": "القوالب الجاهزة المتميزة",
  "growth.productAdvisoryBadge": "المجلس الاستشاري للمنتج",
  "growth.professionalBio": "النبذة المهنية",
  "growth.profileDesc": "إدارة معلومات ملفك الشخصي، ومتابعة نقاط الخبرة والشارات المكتسبة وسجل الإحالات.",
  "growth.profileDescription": "لوحة متكاملة تعرض هويتك في المنصة ومكافآتك ونشاطك التفاعلي.",
  "growth.profileHeader": "الملف الشخصي والمكافآت",
  "growth.proposeFeature": "اقترح ميزة جديدة",
  "growth.proposeNewFeature": "تقديم اقتراح أو فكرة جديدة",
  "growth.proposeTitle": "شاركنا أفكارك لتطوير المنصة",
  "growth.publishPost": "نشر الاقتراح الآن",
  "growth.publishPostError": "حدث خطأ أثناء نشر المقترح، يرجى المحاولة لاحقاً.",
  "growth.qrPlaceholder": "معاينة رمز QR",
  "growth.qrPresetsTitle": "مكتبة القوالب المحسنة",
  "growth.qrTypeEmail": "رمز QR للبريد الإلكتروني",
  "growth.qrTypeText": "رمز QR للنص المجرد",
  "growth.qrTypeUrl": "رمز QR لروابط المواقع",
  "growth.qrTypeWifi": "رمز QR لشبكات الواي فاي",
  "growth.rawTextCode": "ترميز النصوص الخام",
  "growth.referralDescription": "شارك رابط الإحالة الخاص بك مع زملائك وأصدقائك واكسب نقاط خبرة وشارات حصرية ومزايا استثنائية.",
  "growth.referralMilestones": "مراحل برنامج الإحالة",
  "growth.referralTier": "فئة الإحالة الحالية",
  "growth.referralTierFallback": "عضو نشط",
  "growth.referralsDesc": "تتبع عدد المستخدمين المنضمين عبر رابطك الشخصي ونقاط المكافآت التي جمعتها.",
  "growth.referralsHub": "مركز الإحالات والمكافآت",
  "growth.referralsHubTitle": "برنامج المكافآت ومشاركة المنصة",
  "growth.release1Badge": "تحديث رئيسي",
  "growth.release1Date": "مايو 2026",
  "growth.release1Note1": "محرك معالجة متجهات SVG عالي الدقة دون تشويش بكسلي.",
  "growth.release1Note2": "دعم كامل لمعايير تصحيح الأخطاء المتقدمة حتى 30%.",
  "growth.release1Note3": "معالجة محلية 100% داخل المتصفح لضمان أقصى درجات الخصوصية.",
  "growth.release1Note4": "تصدير فوري بدون أي علامات مائية أو رسوم اشتراك.",
  "growth.release1Version": "الإصدار 2.4.0",
  "growth.release2Badge": "تحسين الأداء",
  "growth.release2Date": "يونيو 2026",
  "growth.release2Note1": "تحديث مكتبة القوالب لتشمل أكثر من 30 قالباً احترافياً جاهزاً.",
  "growth.release2Note2": "إضافة فاحص التباين وقابلية المسح في الوقت الفعلي.",
  "growth.release2Note3": "دعم شامل لـ 14 لغة عالمية مع توجيه RTL متكامل.",
  "growth.release2Version": "الإصدار 3.0.0",
  "growth.releaseNotesDesc": "تابع أحدث التحسينات والميزات المضافة لخدمتكم في كل تحديث للمنصة.",
  "growth.releaseNotesTitle": "سجل التحديثات وملاحظات الإصدارات",
  "growth.reply": "الرد",
  "growth.rewardsUnlocked": "المكافآت والمزايا المفتوحة",
  "growth.roadmapDesc": "اطلع على الميزات التي نعمل عليها حالياً والمخططة للإصدارات القادمة وصوت لما يهمك أكثر.",
  "growth.roadmapInProgress": "قيد التطوير والاختبار",
  "growth.roadmapLive": "مكتملة ومتاحة حالياً",
  "growth.roadmapPlanned": "مخططة للإصدارات القادمة",
  "growth.roadmapTitle": "خارطة طريق تطوير المنصة",
  "growth.roadmapUpvote": "تصويت للميزة",
  "growth.roiDesc": "توفير كامل في تكاليف الاشتراكات السنوية مقارنة بالمولدات المدفوعة الأخرى مع الحفاظ على أعلى معايير الجودة.",
  "growth.roiFactor": "معدل التوفير السنوي",
  "growth.roiFactorValue": "100% مجاني للأبد",
  "growth.roiTitle": "القيمة المضافة والعائد الاستثماري",
  "growth.saasRewardsUnlocked": "المزايا المفتوحة لحسابك",
  "growth.saleValueLabel": "القيمة المقدرة للحملة",
  "growth.satisfactionRating": "نسبة رضا المستخدمين: 99.4%",
  "growth.saveProfileDetails": "حفظ بيانات الملف الشخصي",
  "growth.saving": "جارٍ الحفظ...",
  "growth.scanVolumeValue": "غير محدود",
  "growth.scanVolumes": "حجم عمليات المسح المسموح بها",
  "growth.scannersUsed": "توافق تام مع جميع الهواتف الذكية والأجهزة اللوحية والماسحات الضوئية الصناعية.",
  "growth.scansLabel": "عمليات المسح",
  "growth.searchPlaceholder": "البحث في المقترحات والنقاشات...",
  "growth.secureWifiNetwork": "شبكة واي فاي آمنة ومحمية",
  "growth.securingStates": "تأمين الجلسات والبيانات المحلية",
  "growth.sendAnotherFeedback": "إرسال ملاحظة أخرى",
  "growth.setupSpeed": "سرعة الإعداد والإنشاء",
  "growth.setupSpeedValue": "فوري وفي ثوانٍ معدودة",
  "growth.signupNeeded": "مطلوب تسجيل {{count}} مستخدم",
  "growth.signupsNeeded": "مطلوب {{count}} تسجيلات إضافية",
  "growth.sloganLabel": "الشعار أو العبارة الترويجية",
  "growth.sloganPlaceholder": "اكتب شعاراً جذاباً...",
  "growth.statusInProgress": "قيد التطوير والتنفيذ",
  "growth.statusLive": "متاح ومطلق رسمياً",
  "growth.statusPlanned": "في خطة العمل القادمة",
  "growth.subheadingLabel": "العنوان الفرعي",
  "growth.subheadingPlaceholder": "أدخل عنواناً فرعياً توضيحياً...",
  "growth.submitAdvisoryForm": "إرسال المقترح للمراجعة",
  "growth.submitFeedbackError": "تعذر إرسال الملاحظات، يرجى المحاولة مرة أخرى.",
  "growth.subscribe": "اشتراك",
  "growth.subscribeButton": "اشترك الآن مجاناً",
  "growth.subscribeDesc": "انضم إلى أكثر من 25,000 مهني ومصمم يحصلون على تحديثاتنا الحصرية شهرياً.",
  "growth.subscribeSuccess": "شكراً لاشتراكك! ستصلك نشرتنا قريباً.",
  "growth.subscribeTitle": "ابقَ على اطلاع بأحدث التطورات",
  "growth.suiteTitle": "حزمة أدوات النمو والتطوير",
  "growth.tabCommunity": "المجتمع والنقاشات",
  "growth.tabFeedback": "إرسال الملاحظات والآراء",
  "growth.tabProfile": "الملف الشخصي والإحصائيات",
  "growth.tabReleaseNotes": "ملاحظات الإصدارات",
  "growth.tabRoadmap": "خارطة الطريق المستقبلية",
  "growth.tabTestimonials": "آراء وتجارب المستخدمين",
  "growth.testimonial1Author": "سارة الشريف",
  "growth.testimonial1Quote": "أفضل منصة أنشأت من خلالها رموز QR لحملاتنا التسويقية. تصدير SVG المتجه مذهل للجودة الطباعية الكبيرة، وبدون أي علامات مائية على الإطلاق!",
  "growth.testimonial1Role": "مديرة التسويق الرقمي بشركة آفاق المبتكرة",
  "growth.testimonial1Stats": "أكثر من 150,000 عملية مسح ناجحة",
  "growth.testimonial2Author": "م. أحمد الغامدي",
  "growth.testimonial2Quote": "الأمان والخصوصية هما أهم ما يميز FreeQRBarcodes.com. معالجة البيانات محلياً داخل المتصفح منحتنا راحة بال تامة لجميع روابطنا المؤسسية.",
  "growth.testimonial2Role": "مهندس برمجيات رئيسي في تك-سوليوشنز",
  "growth.testimonial2Stats": "دمج في أكثر من 40 مشروعاً برمجياً",
  "growth.testimonialAuthor1": "سارة الشريف",
  "growth.testimonialAuthor2": "م. أحمد الغامدي",
  "growth.testimonialQuote1": "أفضل منصة أنشأت من خلالها رموز QR لحملاتنا التسويقية. تصدير SVG المتجه مذهل للجودة الطباعية الكبيرة، وبدون أي علامات مائية على الإطلاق!",
  "growth.testimonialQuote2": "الأمان والخصوصية هما أهم ما يميز FreeQRBarcodes.com. معالجة البيانات محلياً داخل المتصفح منحتنا راحة بال تامة لجميع روابطنا المؤسسية.",
  "growth.testimonialRole1": "مديرة التسويق الرقمي",
  "growth.testimonialRole2": "كبير مطوري النظم",
  "growth.testimonialStats1": "150 ألف مسحة مؤكدة",
  "growth.testimonialStats2": "اعتماد في 40+ منظومة",
  "growth.testimonialsDesc": "انظر ماذا يقول رواد الأعمال والمطورون الذين يعتمدون على FreeQRBarcodes.com يومياً.",
  "growth.testimonialsTitle": "شهادات وتجارب المستخدمين الموثوقة",
  "growth.tierLabel": "الفئة الحالية",
  "growth.tierPioneer": "المسوق الرائد",
  "growth.title": "مركز النمو وتفاعل المجتمع",
  "growth.totalRevenue": "القيمة المحققة للمجتمع",
  "growth.trustCenterCriteria": "معايير الأمان ومركز الثقة",
  "growth.twitter": "حساب X (تويتر)",
  "growth.twitterHandle": "اسم المستخدم على منصة X",
  "growth.twitterPlaceholder": "اسم الحساب على X (تويتر)",
  "growth.unlockedBadge": "شارة مفتوحة: {{badge}}",
  "growth.updateIdentityTitle": "تحديث معلومات الهوية والملف",
  "growth.updateProfileError": "تعذر تحديث الملف الشخصي، يرجى المحاولة لاحقاً.",
  "growth.upvote": "تصويت إيجابي",
  "growth.upvotes": "الأصوات الإيجابية",
  "growth.upvotesCount": "{{count}} صوت",
  "growth.urlDestination": "رابط الوجهة المستهدفة",
  "growth.v315Date": "يونيو 2026",
  "growth.v315Note1": "توطين وتدويل العملات والأرقام والنسب المئوية ومنسقات التواريخ الديناميكية.",
  "growth.v315Note2": "إضافة دعم المتغيرات وصيغ الجمع والجنس داخل وحدة مدقق الترجمة الدولي.",
  "growth.v315Note3": "تحسين حاويات التصميم من اليمين إلى اليسار (RTL) للنوافذ المنبثقة والألواح الجانبية وعناصر العرض.",
  "growth.v315Title": "الإصدار 3.1.5 - ترقية معايير ICU وأطر دعم اللغات",
  "growth.v320Date": "يوليو 2026",
  "growth.v320Note1": "دمج الملف الشخصي للمستخدم ولوحات تحكم البيانات الوصفية الديناميكية.",
  "growth.v320Note2": "إضافة مؤشرات نظام الإحالات المباشرة في الوقت الفعلي مع مستويات مكافآت متعددة.",
  "growth.v320Note3": "تضمين نظام قياس رضا المستخدمين (CSAT) المدمج مع محرك إشعارات آلي.",
  "growth.v320Note4": "تحسين سجلات المعاملات لتسريع مؤشرات التحليلات للمستخدمين.",
  "growth.v320Title": "الإصدار 3.2.0 - إطلاق محرك النمو للمؤسسات",
  "growth.verifiedSignups": "تسجيلات مؤكدة",
  "growth.xp": "نقاط الخبرة (XP)",
  "growth.xpCount": "{{xp}} نقطة خبرة",
  "growth.yourReferralLink": "رابط الإحالة الفريد الخاص بك",
  "growth.badge.pioneer": "المسوق الرائد",
  "growth.badge.influencer": "المؤثر المعتمد",
  "growth.badge.activist": "الناشط المجتمعي",
  "growth.badge.vocal": "المستشار الصوتي",
  "growth.category.feature": "طلب ميزة برمجية",
  "growth.category.design": "اقتراح تصميم جمالي",
  "growth.category.template": "طلب قالب جديد",
  "growth.category.compliance": "الأمان والامتثال للمعايير",
  "growth.status.completed": "مكتملة ومتاحة حالياً",
  "growth.status.planned": "مخططة في قائمة الانتظار",
  "growth.status.under_review": "قيد التطوير والمراجعة",

  // Announcements & Toast keys
  "Professional QR Creator": "منشئ رموز QR الاحترافي",
  "👋 Welcome to FreeQRGen.pro!": "👋 مرحباً بك في FreeQRBarcodes.com!",
  "Your SaaS Enterprise profile has been activated successfully! Explore the Creator Studio, customize templates, and share feature ideas with our community.": "تم تفعيل ملفك التعريفي المؤسسي بنجاح! استكشف استوديو الإنشاء، وخصص القوالب، وشارك أفكارك مع مجتمعنا.",
  "🎉 Referral Signup Bonus!": "🎉 مكافأة انضمام عبر الإحالة!",
  "Congratulations! Someone registered using your unique referral link. You earned 100 XP and unlocked the \"Referral Specialist\" badge.": "تهانينا! قام مستخدم جديد بالتسجيل عبر رابط الإحالة الخاص بك. لقد كسبت 100 نقطة خبرة وفتحت شارة \"خبير الإحالات\".",
  "💬 Feedback Submitted!": "💬 تم إرسال الملاحظات بنجاح!",
  "Automated Silent Zone Margin Calculations": "الحساب التلقائي لهوامش منطقة الأمان (Quiet Zone)",
  "We have implemented and verified the Reed-Solomon correction levels, but automated quiet zone calculation guarantees that modern cameras on processing factories can read labels seamlessly.": "قمنا بتطبيق والتحقق من مستويات تصحيح الأخطاء ريد-سولومون، مع حساب هوامش منطقة الأمان تلقائياً لضمان قراءة الكاميرات الحديثة وماسحات المصانع للملصقات بسلاسة تامة.",
  "Interactive Vector Quality Controller": "وحدة التحكم التفاعلية بجودة المتجهات",
  "With the latest SVG paths, we can dynamically render scalable vector codes without any rasterization blurring or layout shifting.": "باستخدام أحدث مسارات SVG المتجهة، يمكننا تصيير رموز متجهة عالية القابلية للتوسع دون أي تشويش بكسلي أو انزياح في التخطيط.",
  "Secure WiFi Template Deployment": "نشر قوالب شبكات الواي فاي الآمنة",
  "We launched new customized security guidelines for enterprise QR deployment on secure local networks, ensuring zero-trust credential encapsulation.": "أطلقنا إرشادات أمان مخصصة وجديدة لنشر رموز QR للمؤسسات عبر الشبكات المحلية الآمنة، مع ضمان تشفير وحماية بيانات الاعتماد وفق معايير انعدام الثقة (Zero-Trust)."
};

let count = 0;
for (const [key, value] of Object.entries(translations)) {
  if (ar[key] !== undefined) {
    ar[key] = value;
    count++;
  } else {
    console.warn(`Key missing in ar.json: ${key}`);
  }
}

fs.writeFileSync(arPath, JSON.stringify(ar, null, 2), 'utf8');
console.log(`Updated Group 1 (${count} keys) in ar.json.`);
