const fs = require('fs');
const path = require('path');

const arPath = path.join(__dirname, '../src/locales/ar.json');
const ar = JSON.parse(fs.readFileSync(arPath, 'utf8'));

const translations = {
  // Preview
  "preview.backDisplay": "الجهة الخلفية للعرض",
  "preview.centerLogoCoverage": "2. تغطية الشعار المركزي",
  "preview.centeredPrepress": "معاينة ما قبل الطباعة المركزية",
  "preview.closeSimulatorBtn": "إغلاق محاكي الطباعة",
  "preview.colorContrastRatio": "1. نسبة التباين اللوني",
  "preview.contrastCritHigh": "ممتاز: تباين لوني فائق يضمن قراءة الرمز في جميع ظروف الإضاءة.",
  "preview.contrastCritLow": "تحذير: تباين منخفض للغاية قد يؤدي إلى فشل المسح على بعض الكاميرات.",
  "preview.contrastCritMed": "مقبول: تباين مناسب ولكنه قد يتأثر بالإضاءة الخافتة أو العاكسة.",
  "preview.copyLink": "نسخ الرابط",
  "preview.currentRatio": "النسبة الحالية: {{ratio}}:1",
  "preview.customCenterLogo": "شعار مخصص في المنتصف",
  "preview.customLogoDetected": "تم اكتشاف شعار مخصص في المركز",
  "preview.customPattern": "نمط نقطي مخصص",
  "preview.darkThemeBadge": "النمط الداكن",
  "preview.defaultPreset": "القالب الافتراضي",
  "preview.deviceMockupTitle": "محاكي العرض على الأجهزة والمطبوعات",
  "preview.downloadBtn": "تنزيل الرمز",
  "preview.downloadHighRes": "تنزيل عالي الدقة",
  "preview.downloadPng": "تنزيل بصيغة PNG",
  "preview.downloadSvg": "تنزيل بصيغة SVG",
  "preview.eccHigh": "مستوى تصحيح H (30%)",
  "preview.eccLow": "مستوى تصحيح L (7%)",
  "preview.eccMedium": "مستوى تصحيح M (15%)",
  "preview.eccQuality": "مستوى تصحيح Q (25%)",
  "preview.errorCorrection": "تصحيح الأخطاء (ECC)",
  "preview.errorCorrectionLevel": "3. مستوى تصحيح الأخطاء",
  "preview.errorCorrectionTitle": "مستوى ريد-سولومون لتصحيح الأخطاء",
  "preview.exportTitle": "تصدير ومعاينة رمز QR",
  "preview.failedChecks": "فحوصات لم تجتز المعايير المطلوبة",
  "preview.frontDisplay": "الجهة الأمامية للعرض",
  "preview.gradientApplied": "تم تطبيق تدرج لوني",
  "preview.highContrast": "تباين ممتاز (أكثر من 7:1)",
  "preview.highRes": "دقة فائقة (Print Ready)",
  "preview.instantScan": "مسح فوري مؤكد",
  "preview.insufficientContrast": "تباين غير كافٍ بين الرمز والخلفية",
  "preview.largeLogoWarning": "الشعار يغطي مساحة كبيرة، يرجى رفع مستوى تصحيح الخطأ إلى H.",
  "preview.liveFeedback": "ملاحظات الفحص المباشر",
  "preview.logoCoverageOptimal": "تغطية الشعار مثالية (أقل من 20% من المساحة).",
  "preview.logoWarning": "تنبيه الشعار: تأكد من وضوح زوايا الرمز المربعة لتسهيل القراءة.",
  "preview.lowContrast": "تباين منخفض (أقل من 3:1)",
  "preview.mediumContrast": "تباين متوسط (بين 3:1 و 7:1)",
  "preview.mockupBadge": "محاكي المعاينة الواقعية",
  "preview.mockupBusinessCard": "بطاقة عمل رقمية (Business Card)",
  "preview.mockupFlyer": "منشور إعلاني (Flyer)",
  "preview.mockupMenu": "قائمة طعام مطعم (Table Tent)",
  "preview.mockupPoster": "ملصق جداري إعلاني (Poster)",
  "preview.mockupSignage": "لافتة متجر خارجية (Signage)",
  "preview.mockupTshirt": "قميص ترويجي (T-Shirt)",
  "preview.noLogoDetected": "لم يتم إدراج شعار في المنتصف",
  "preview.optimalContrast": "نسبة التباين ممتازة وتتجاوز المعايير القياسية.",
  "preview.passedAllChecks": "اجتاز الرمز جميع اختبارات القراءة والتباين بنجاح!",
  "preview.prepressSimulation": "محاكاة ما قبل الطباعة والإنتاج",
  "preview.printReady": "جاهز للطباعة بدقة 300+ DPI",
  "preview.printSimulator": "محاكي الطباعة وتوزيع الصفحات",
  "preview.qualityScore": "درجة جودة وموثوقية المسح: {{score}}%",
  "preview.quietZoneMargin": "4. هوامش منطقة الأمان (Quiet Zone)",
  "preview.quietZoneOptimal": "هوامش منطقة الأمان ممتازة (4 وحدات على الأقل).",
  "preview.quietZoneWarning": "الهامش المحيط بالرمز ضيق، قد تواجه بعض الماسحات صعوبة في تحديد أطراف الرمز.",
  "preview.readyForPrint": "الملف جاهز للطباعة التجارية الفورية",
  "preview.realtimeDiagnostic": "التشخيص الفوري لقابلية القراءة",
  "preview.recommendation": "التوصية الفنية:",
  "preview.recommendationContrast": "قم بزيادة التباين بين لون الرمز ولون الخلفية.",
  "preview.recommendationEcc": "ارفع مستوى تصحيح الخطأ إلى H عند استخدام شعار مخصص.",
  "preview.recommendationLogo": "قلل حجم الشعار ليبقى الرمز قابلاً للقراءة بسلاسة.",
  "preview.recommendationQuietZone": "أضف مساحة بيضاء كافية حول أطراف الرمز.",
  "preview.scanDiagnosticTitle": "فاحص قابلية المسح وجودة الرمز",
  "preview.scanDistance": "مسافة المسح التقديرية: {{distance}} سم",
  "preview.scanRating": "تقييم قابلية القراءة",
  "preview.scanScore": "مؤشر سهولة المسح",
  "preview.scannabilityCheck": "فحص معايير المسح الضوئي",
  "preview.simulatedPhone": "كاميرا الهاتف الذكي الافتراضية",
  "preview.simulatedPhysical": "المعاينة الفيزيائية للمنتج",
  "preview.solidColor": "لون أحادي مصمت",
  "preview.standardResolution": "دقة الويب القياسية (72 DPI)",
  "preview.statusExcellent": "ممتاز: جاهز للنشر والطباعة فوراً",
  "preview.statusGood": "جيد: يعمل بكفاءة مع معظم الأجهزة",
  "preview.statusWarning": "تنبيه: يتطلب بعض التحسينات لضمان القراءة",
  "preview.svgExport": "تصدير متجهات SVG (غير محدود الدقة)",
  "preview.switchMockup": "تبديل نموذج العرض",
  "preview.title": "معاينة الرمز المباشرة",
  "preview.totalScore": "المجموع الكلي للجودة",
  "preview.vectorHighRes": "متجه فائق النقاء للطباعة",
  "preview.viewLiveMockup": "عرض المحاكاة الواقعية",
  "preview.warningDetails": "تفاصيل التنبيهات الفنية",
  "preview.wcagPassed": "مطابق لمعايير التباين البصري WCAG AA",
  "preview.zoomIn": "تكبير المعاينة",
  "preview.zoomOut": "تصغير المعاينة",

  // Print
  "print.activeAlignmentMarks": "علامات المحاذاة والقص النشطة (تخفى عند الطباعة النهائية)",
  "print.backToStation": "العودة إلى استوديو التصميم",
  "print.badgeLabel": "شارة التعريف والملصق",
  "print.calibrationDesc": "اضبط خيارات الطباعة في اللوحة الجانبية. يتم تحديث تخطيط الصفحة أدناه فوراً بالهوامش والأبعاد الفيزيائية الحقيقية. اضغط زر الطباعة أو استخدم Ctrl+P لإرسال الأمر إلى الطابعة.",
  "print.calibrationSettings": "إعدادات المعايرة والتحجيم الدقيق",
  "print.centerOnPage": "توسيط في منتصف الورقة",
  "print.columns": "عدد الأعمدة في الصفحة",
  "print.copiesCount": "عدد النسخ الإجمالية: {{count}}",
  "print.customDimensions": "أبعاد مخصصة للرمز",
  "print.customMargin": "هوامش الورقة المخصصة (ملم)",
  "print.cutLines": "إظهار خطوط القص الإرشادية",
  "print.dpiLabel": "دقة الطباعة (DPI):",
  "print.gridColumns": "الأعمدة:",
  "print.gridRows": "الصفوف:",
  "print.gridSpacing": "المسافة بين الرموز (ملم)",
  "print.includeCutLines": "تضمين خطوط القص",
  "print.includeLabels": "طباعة نصوص توضيحية أسفل كل رمز",
  "print.labelFontSize": "حجم خط التسميات التوضيحية",
  "print.labelText": "نص التسمية التوضيحية",
  "print.layoutA4": "ورق قياسي A4 (210 × 297 ملم)",
  "print.layoutA5": "ورق قياسي A5 (148 × 210 ملم)",
  "print.layoutCustom": "حجم صفحة مخصص",
  "print.layoutLetter": "ورق رسائل أمريكي Letter (8.5 × 11 بوصة)",
  "print.layoutOptions": "خيارات تخطيط الصفحة",
  "print.margins": "الهوامش الخارجية (ملم)",
  "print.numberOfCopies": "عدد النسخ المطلوبة",
  "print.pageOrientation": "اتجاه الصفحة",
  "print.pageSize": "مقاس الورق",
  "print.paperLandscape": "عرضي (Landscape)",
  "print.paperPortrait": "طولي (Portrait)",
  "print.paperSize": "حجم الورقة:",
  "print.printBtn": "طباعة الورقة الآن",
  "print.printButton": "إرسال إلى الطابعة",
  "print.printLayoutTitle": "استوديو تخطيط وطباعة الرموز المتعددة",
  "print.printNow": "طباعة الآن (Ctrl+P)",
  "print.printPreview": "معاينة الورقة قبل الطباعة",
  "print.qrHeight": "الارتفاع (ملم)",
  "print.qrSize": "حجم الرمز الفيزيائي (ملم)",
  "print.qrWidth": "العرض (ملم)",
  "print.rows": "عدد الصفوف في الصفحة",
  "print.sheetLayout": "توزيع الشبكة في الصفحة",
  "print.sheetSummary": "إجمالي الرموز في الصفحة: {{count}} رمز",
  "print.spacing": "التباعد بين الرموز (ملم)",
  "print.title": "مركز إعداد وتوزيع الطباعة الجماعية",
  "print.totalCodes": "إجمالي الرموز:",
  "print.totalPages": "عدد الصفحات التقديري: {{count}}",

  // Programmatic
  "programmatic.authorName": "هيئة تحرير FreeQRBarcodes.com",
  "programmatic.caseStudyMetricSolutions": "زيادة بنسبة 41% في معدلات تحويل الزوار",
  "programmatic.caseStudyResultSolutions": "أدى استبدال الخطوات الورقية القديمة باختصارات رموز الباركود التفاعلية إلى أتمتة انضمام العملاء ورفع كفاءة القياس.",
  "programmatic.caseStudyTitleSolutions": "نشر حلول {{name}} للمؤسسات",
  "programmatic.challenge1": "تواجه المؤسسات صعوبات مستمرة في تداول البيانات الورقية يدوياً وتكرار أخطاء إدخال النصوص.",
  "programmatic.challenge2": "صعوبة قياس معدلات التفاعل الميداني بدقة ومحدودية تتبع الحملات الإعلانية المطبوعة.",
  "programmatic.challenge3": "ارتفاع تكاليف الاشتراكات السنوية في المولدات المدفوعة مع فرض علامات مائية على التصميمات.",
  "programmatic.challengesTitle": "التحديات التشغيلية الشائعة",
  "programmatic.conclusion": "تتيح لك منصة FreeQRBarcodes.com إنشاء وإدارة ومتابعة رموز QR وحلول الباركود بدقة طباعية متناهية ومعالجة آمنة مجانية بالكامل.",
  "programmatic.featuresTitle": "أبرز المزايا والقدرات الفنية",
  "programmatic.heroBadge": "حلول متخصصة ومجانية",
  "programmatic.heroDesc": "اكتشف كيف توفر لك منصة FreeQRBarcodes.com أقوى أدوات إنشاء الرموز المخصصة لـ {{name}} مع تصدير متجه فائق النقاء.",
  "programmatic.heroTitle": "حلول رموز QR و باركود متخصصة لـ {{name}}",
  "programmatic.howItWorks1Desc": "اختر نوع المحتوى الذي تريد ترميزه وأدخل بياناتك بسهولة وسرعة.",
  "programmatic.howItWorks1Title": "1. إعداد وتجهيز البيانات",
  "programmatic.howItWorks2Desc": "خصص الألوان والتدرجات والشعار المركزي وأشكال العيون والنقاط.",
  "programmatic.howItWorks2Title": "2. التخصيص البصري والهوية",
  "programmatic.howItWorks3Desc": "حمل الملف فوراً بصيغة SVG المتجهة للطباعة أو PNG للعرض الرقمي.",
  "programmatic.howItWorks3Title": "3. التصدير الفوري عالي الدقة",
  "programmatic.howItWorksTitle": "كيفية إنشاء واستخدام الرموز في 3 خطوات بسيطة",
  "programmatic.metric1Label": "معدل دقة المسح",
  "programmatic.metric1Value": "99.9%",
  "programmatic.metric2Label": "زمن التوليد المحلي",
  "programmatic.metric2Value": "< 10 مللي ثانية",
  "programmatic.metric3Label": "تكلفة الاستخدام",
  "programmatic.metric3Value": "مجاني للأبد",
  "programmatic.solution1Desc": "توليد فوري ومحلي 100% داخل المتصفح يضمن خصوصية البيانات دون إرسالها لأي خادم وسيط.",
  "programmatic.solution1Title": "المعالجة الموضعية الآمنة",
  "programmatic.solution2Desc": "تصدير متجهات SVG النقية القابلة للتكبير اللانهائي دون أي فقدان في الجودة أو تشويش بكسلي.",
  "programmatic.solution2Title": "جودة طباعية لا محدودة",
  "programmatic.solution3Desc": "تخصيص شامل لجميع عناصر الرمز مع فاحص فوري لنسب التباين وقابلية القراءة.",
  "programmatic.solution3Title": "تحكم جمالي وهندسي متكامل",
  "programmatic.solutionsTitle": "الحلول والميزات المبتكرة",
  "programmatic.useCasesTitle": "أبرز حالات الاستخدام والتطبيق",

  // Saved
  "saved.allCount": "الكل ({{count}})",
  "saved.batchSelectedCount": "تم تحديد {{count}} عنصر",
  "saved.createBtn": "إنشاء رمز جديد",
  "saved.desc": "إدارة رموز QR المحفوظة محلياً، والاطلاع على حالة التتبع، وتصنيف التصميمات في مجلدات مخصصة.",
  "saved.expiredBadge": "منتهي الصلاحية ⚠️",
  "saved.activeBadge": "نشط وجاهز ✓",
  "saved.deleteSelected": "حذف العناصر المحددة",
  "saved.emptyDesc": "لم تقم بحفظ أي تصميمات بعد. صمم رمزك الأول واضغط زر الحفظ للاحتفاظ به هنا.",
  "saved.emptyTitle": "لا توجد تصميمات محفوظة بعد",
  "saved.exportAll": "تصدير الكل",
  "saved.filterAll": "جميع التصميمات",
  "saved.filterFolder": "تصفية حسب المجلد",
  "saved.lastModified": "آخر تعديل: {{date}}",
  "saved.loadDesign": "تحميل وتعديل التصميم",
  "saved.moveToFolder": "نقل إلى مجلد",
  "saved.newFolder": "مجلد جديد",
  "saved.noDesignsInFolder": "هذا المجلد فارغ حالياً.",
  "saved.openDesign": "فتح في الاستوديو",
  "saved.renameDesign": "إعادة تسمية التصميم",
  "saved.searchPlaceholder": "ابحث في التصميمات المحفوظة...",
  "saved.title": "أرشيف التصميمات المحفوظة",
  "saved.totalDesigns": "إجمالي التصاميم: {{count}}",

  // SEO
  "seo.aestheticOptimization": "التحسين الجمالي والبصري",
  "seo.aiReferenceDesc": "مواصفات تقنية مهيكلة، وأفضل الممارسات الهندسية، وإجابات موثقة محسنة للفهرسة والذكاء الاصطناعي عبر Gemini و ChatGPT و Perplexity و Google AI Overviews.",
  "seo.aiReferenceTitle": "دليل المراجع والتوثيق الذكي لـ {{keyword}}",
  "seo.aiSummaryTitle": "ملخص شامل وموجز للذكاء الاصطناعي",
  "seo.backButton": "العودة إلى مساحة العمل",
  "seo.canonicalUrl": "الرابط المعياري",
  "seo.citationsHeading": "المراجع والمواصفات القياسية الدولية",
  "seo.coreTopic": "الموضوع الأساسي",
  "seo.definitionTitle": "التعريف والمفهوم التقني لـ {{keyword}}",
  "seo.faqSectionTitle": "الأسئلة الشائعة والإجابات المعتمدة",
  "seo.keyFeaturesHeading": "الميزات التقنية والمواصفات",
  "seo.keywordsLabel": "الكلمات المفتاحية:",
  "seo.lastUpdated": "آخر تحديث وتحقق:",
  "seo.metaDescription": "الوصف التعريفي لمحركات البحث (Meta Description)",
  "seo.metaTitle": "عنوان الصفحة لمحركات البحث (Title Tag)",
  "seo.openGraphDesc": "وصف المشاركة عبر وسائل التواصل (Open Graph Description)",
  "seo.openGraphTitle": "عنوان المشاركة عبر وسائل التواصل (Open Graph Title)",
  "seo.overviewHeading": "نظرة عامة ودليل الاستخدام",
  "seo.primaryKeyword": "الكلمة المفتاحية الأساسية",
  "seo.publisher": "الناشر المعتمد: FreeQRBarcodes.com",
  "seo.readTime": "وقت القراءة المقدر: {{mins}} دقائق",
  "seo.readingLevel": "المستوى الفني: احترافي للمطورين والمصممين",
  "seo.relatedTopics": "مواضيع وأدلة ذات صلة",
  "seo.schemaType": "نوع هيكل البيانات المرجعي (Schema.org)",
  "seo.structuredData": "البيانات المهيكلة المعتمدة",
  "seo.tableOfContents": "جدول المحتويات والمحاور الرئيسية",
  "seo.targetAudience": "الجمهور المستهدف: المطورون، المسوقون، أصحاب الأعمال",
  "seo.technicalSpecs": "المواصفات الفنية التفصيلية",
  "seo.verifiedBy": "تمت المراجعة الفنية بواسطة الفريق الهندسي",

  // Shortcuts
  "shortcuts.close": "إغلاق النوافذ المنبثقة",
  "shortcuts.closeDesc": "إغلاق النوافذ المعروضة، والقوائم المنسدلة، وصناديق الحوار المفتوحة (Esc)",
  "shortcuts.disabledNote": "يتم تعطيل الاختصارات تلقائياً أثناء الكتابة داخل حقول النصوص لمنع أي تداخل.",
  "shortcuts.downloadDesc": "تنزيل الرمز بالدقة الفائقة فوراً (Ctrl+S / ⌘S)",
  "shortcuts.openHelp": "فتح دليل الاختصارات السريعة",
  "shortcuts.openHelpDesc": "عرض نافذة اختصارات لوحة المفاتيح في أي وقت (?)",
  "shortcuts.printDesc": "فتح لوحة إعداد وتخطيط الطباعة (Ctrl+P / ⌘P)",
  "shortcuts.redoDesc": "إعادة تطبيق الإجراء الأخير (Ctrl+Y / ⌘⇧Z)",
  "shortcuts.resetDesc": "إعادة تعيين كافة خيارات التصميم للافتراضي (Ctrl+R / ⌘R)",
  "shortcuts.switchTabDesc": "التبديل بين علامات تبويب أنواع الرموز (1-9)",
  "shortcuts.title": "اختصارات لوحة المفاتيح السريعة",
  "shortcuts.togglePreviewDesc": "تبديل وضع معاينة المحاكاة الفيزيائية (Space)",
  "shortcuts.undoDesc": "التراجع عن التعديل الأخير (Ctrl+Z / ⌘Z)"
};

let count = 0;
for (const [key, value] of Object.entries(translations)) {
  ar[key] = value;
  count++;
}

fs.writeFileSync(arPath, JSON.stringify(ar, null, 2), 'utf8');
console.log(`Updated Group 4 translations (${count} keys) in ar.json.`);
