const fs = require('fs');
const path = require('path');

const arPath = path.join(__dirname, '../src/locales/ar.json');
const ar = JSON.parse(fs.readFileSync(arPath, 'utf8'));

const batch1 = {
  // nav
  "nav.brand": "منشئ رموز QR الفائق",
  "nav.home": "الرئيسية",
  "nav.analytics": "التحليلات",
  "nav.saved": "المحفوظات",
  "nav.scanner": "الماسح الضوئي",
  "nav.templates": "القوالب الجاهزة",

  // barcode
  "barcode.title": "منشئ الباركود الخطي عالي التباين",
  "barcode.desc": "توليد باركود قياسي جاهز للطباعة لأنظمة نقاط البيع والمستودعات والتجارة الإلكترونية.",
  "barcode.formatLabel": "نوع وتنسيق الباركود",
  "barcode.valueLabel": "قيمة وبيانات الباركود",
  "barcode.format.ean13": "EAN-13 (المنتجات العالمية والتجزئة)",
  "barcode.format.upca": "UPC-A (التجزئة في أمريكا الشمالية)",
  "barcode.format.code128": "CODE128 (شامل - نصوص وأرقام)",
  "barcode.format.code39": "CODE39 (الصناعي وقطع الغيار والسيارات)",
  "barcode.margin": "الهامش الخارجي الأبيض (بكسل)",
  "barcode.barHeight": "ارتفاع الخطوط ({height} بكسل)",
  "barcode.lineThickness": "سُمك الخط ({width} بكسل)",
  "barcode.lineColor": "لون الخطوط",
  "barcode.backgroundColor": "لون الخلفية",
  "barcode.renderValueText": "إظهار النص أسفل الباركود",
  "barcode.renderValueTextDesc": "عرض الأرقام أو النصوص المقروءة أسفل خطوط الباركود",
  "barcode.livePreviewBoard": "لوحة المعاينة المباشرة",
  "barcode.invalidStructure": "بنية البيانات غير صالحة",
  "barcode.symbologyLabel": "الترميز المعتمد:",
  "barcode.charactersLabel": "عدد الأحرف:",
  "barcode.heightLabel": "الارتفاع:",
  "barcode.linesColorLabel": "لون الخطوط:",
  "barcode.downloadPng": "تنزيل بصيغة PNG",
  "barcode.downloadSvg": "تنزيل بصيغة SVG المتجهية",
  "barcode.tipTitle": "نصيحة للمطورين وأنظمة نقاط البيع",
  "barcode.tipDesc": "تتطلب الباركودات الخطية تبايناً مادياً عالياً لضمان سرعة القراءة عبر أجهزة المسح الليزري. احرص على استخدام ألوان عالية التباين (مثل الأسود على الأبيض) واختر تنسيق SVG المتجهي لأعمال طباعة عبوات المنتجات التجارية.",
  "barcode.validFormat": "تنسيق الباركود صحيح ومعتمد.",
  "barcode.passedValidation": "تم التحقق من صحة التنسيق بنجاح! التباين العالي جاهز للعرض والطباعة.",
  "barcode.valEmpty": "يرجى إدخال قيمة لتوليد الباركود.",
  "barcode.valEanDigits": "يتطلب EAN-13 أرقاماً فقط (0-9).",
  "barcode.valEanLen": "يتطلب EAN-13 بالضبط 12 أو 13 رقماً (الحالي: {count}). يتم احتساب وإضافة رقم التحقق تلقائياً عند إدخال 12 رقماً.",
  "barcode.valUpcDigits": "يتطلب UPC-A أرقاماً فقط (0-9).",
  "barcode.valUpcLen": "يتطلب UPC-A بالضبط 11 أو 12 رقماً (الحالي: {count}). يتم احتساب وإضافة رقم التحقق تلقائياً عند إدخال 11 رقماً.",
  "barcode.valCode39Chars": "يدعم CODE39 الأرقام 0-9 والحروف الإنجليزية الكبيرة A-Z والمسافة والرموز: - . $ / + %",
  "barcode.valCode128Ascii": "يدعم CODE128 أحرف ASCII القياسية فقط.",
  "barcode.helpEan": "يتطلب EAN-13 بالضبط 12 رقماً (يتم احتساب الرقم الثالث عشر للتحقق تلقائياً).",
  "barcode.helpUpc": "يتطلب UPC-A بالضبط 11 رقماً (يتم احتساب الرقم الثاني عشر للتحقق تلقائياً).",
  "barcode.helpCode39": "يدعم CODE39 الحروف الإنجليزية الكبيرة (A-Z) والأرقام (0-9) والرموز: - . $ / + % والمسافة.",
  "barcode.helpCode128": "يتميز CODE128 بمرونة فائقة ويدعم كافة أحرف ASCII القياسية (حروف، أرقام، رموز).",
  "barcode.renderFailed": "تعذر عرض هذا المحتوى لتنسيق {format}. يرجى التحقق من الأحرف المدخلة.",
  "barcode.unsupportedChars": "تحتوي القيمة على أحرف غير مدعومة لتنسيق الباركود المحدد.",

  // blog
  "blog.category.qr_code_guides": "أدلة وإرشادات رموز QR",
  "blog.category.business_marketing": "التسويق التجاري والشركات",
  "blog.category.digital_marketing": "التسويق الرقمي",
  "blog.category.small_business_tools": "أدوات المشاريع الصغيرة",
  "blog.category.technology": "التكنولوجيا والبرمجيات",
  "blog.category.contactless_solutions": "الحلول اللاتلامسية",
  "blog.category.restaurant_qr_menus": "قوائم طعام المطاعم الرقمية",
  "blog.category.event_qr_codes": "رموز QR للفعاليات والمؤتمرات",
  "blog.category.education_qr_codes": "رموز QR للتعليم والجامعات",
  "blog.category.social_media_marketing": "تسويق منصات التواصل الاجتماعي",
  "blog.allCategories": "جميع التصنيفات",
  "blog.backToHub": "العودة إلى مركز المقالات",
  "blog.blogTitle": "مدونة منشئ رموز QR غير المحدود",
  "blog.copied": "تم النسخ بنجاح!",
  "blog.coreFaqs": "الأسئلة الشائعة حول المقال",
  "blog.filterTopic": "تصفية المقالات حسب الموضوع",
  "blog.marketingGuides": "أدلة التسويق والتقنية",
  "blog.marketingGuidesDesc": "ابقَ على اطلاع بأحدث استراتيجيات التسويق الرقمي، وأنظمة الضيافة اللاتلامسية، وتصحيح الأخطاء، وإعدادات التصميم الاحترافية.",
  "blog.readArticle": "قراءة المقال",
  "blog.relatedTools": "أدوات ذات صلة في مساحة العمل",
  "blog.share": "مشاركة المقال",

  // analytics
  "analytics.colBrowser": "متصفح المستخدم",
  "analytics.colDatetime": "تاريخ ووقت المسح",
  "analytics.colLocation": "الموقع الجغرافي التقريبي",
  "analytics.colPlatform": "نظام التشغيل",
  "analytics.desc": "سجلات ومؤشرات سحابية آمنة ترصد عمليات إعادة التوجيه الفعالة للمستخدمين.",
  "analytics.heatmapDesc": "نقاط تفاعلية توضح التوزيع الجغرافي لتفاعل المستخدمين.",
  "analytics.heatmapTitle": "التوزيع الجغرافي لمناطق المسح",
  "analytics.leaderboardDesc": "أبرز المناطق الجغرافية مرتبة حسب كثافة المسح.",
  "analytics.leaderboardTitle": "ترتيب المناطق الجغرافية الأكثر نشاطاً",
  "analytics.noLogs": "لا توجد سجلات تتبع لعمليات المسح حتى الآن",
  "analytics.platformsDesc": "أنظمة وأجهزة المستخدمين المستخدمة في قراءة الرموز.",
  "analytics.platformsTitle": "توزيع منصات وأنظمة التشغيل",
  "analytics.statDistinct": "وكلاء المستخدمين الفريدون",
  "analytics.statGrade": "معدل التحويل العالمي",
  "analytics.statScans": "إجمالي نقرات ومسحات الحملة",
  "analytics.streamDesc": "موجز فوري لعمليات إعادة التوجيه الناجحة للعملاء.",
  "analytics.streamTitle": "سجل تتبع عمليات المسح المباشر",
  "analytics.title": "تحليلات الأداء السحابية",

  // auth
  "auth.createAccount": "إنشاء حساب جديد",
  "auth.emailAddress": "عنوان البريد الإلكتروني",
  "auth.failed": "فشلت المصادقة. يرجى التحقق من بيانات الاعتماد الخاصة بك.",
  "auth.fullName": "الاسم الكامل",
  "auth.nameRequired": "حقل الاسم مطلوب",
  "auth.secureCloudShield": "حماية سحابية مشفرة",
  "auth.securePassword": "كلمة المرور الآمنة",
  "auth.signInButton": "تسجيل الدخول",
  "auth.signInDesc": "سجل الدخول للوصول إلى تصميمات رموز QR المحفوظة وتحليلات الأداء.",
  "auth.signInTab": "تسجيل الدخول",
  "auth.signUpButton": "إنشاء بيانات الاعتماد",
  "auth.signUpDesc": "ابدأ الآن واحتفظ بسجلات وتصميمات لوحة التحكم الخاصة بك.",
  "auth.signUpTab": "إنشاء حساب",
  "auth.storageInfo": "محرك تخزين سحابي آمن وسريع. جميع العمليات مشفرة ومحمية بالكامل.",
  "auth.welcomeBack": "مرحباً بعودتك",

  // animations
  "animations.canvasDesc": "محاكاة حية مدعومة بطبقات تسريع العتاد عبر Framer Motion",
  "animations.canvasTitle": "لوحة التصميم الحركي التفاعلي",
  "animations.deploy.instore.desc": "استخدم حركة التنفس المتدرجة مع تعليمات واضحة أسفل الإطار.",
  "animations.deploy.instore.title": "شاشات المتاجر ونقاط البيع",
  "animations.deploy.stream.desc": "ضع الرمز في الزوايا مع دوران خفيف للحفاظ على سهولة القراءة والمسح.",
  "animations.deploy.stream.title": "بث الفيديو والشاشات المباشرة",
  "animations.deploy.tv.desc": "احرص على تباين لوني عالٍ مع دورة تكرار مدتها 10 ثوانٍ لجذب انتباه المشاهد.",
  "animations.deploy.tv.title": "إعلانات التلفزيون والشاشات الكبيرة",
  "animations.deployTitle": "أين يمكنك استخدام رموز QR المتحركة",
  "animations.downloadBtn": "تنزيل صورة رمز QR المتحرك",
  "animations.downloadDesc": "يحافظ تنسيق PNG على خصائص الشفافية والتصميم المتميز بدقة تامة.",
  "animations.durationLabel": "مدة دورة الحركة والانتقال",
  "animations.eyeRetention": "معدل جذب الانتباه البصري",
  "animations.galleryDesc": "اختر نمطاً حركياً تفاعلياً لتحديث إعدادات لوحة الرسم فوراً.",
  "animations.galleryTitle": "معرض التأثيرات الحركية الجاهزة",
  "animations.hyperFast": "⚡ سريع جداً (3 ثوانٍ)",
  "animations.marketingDesc": "تطبيق الحركات التفاعلية الدقيقة يرفع معدلات التحويل بنسبة تصل إلى <strong>44%</strong> على شاشات العرض الرقمية، وإعلانات التلفزيون، والبث المباشر، وروابط السيرة الذاتية.",
  "animations.marketingTitle": "لوحات ولافتات رقمية عالية الأداء",
  "animations.preset.ambientGlow.badge": "مظهر سحابي راقٍ",
  "animations.preset.ambientGlow.desc": "نبضات ضوئية هادئة تحاكي أضواء الشفق مع خلفيات متغيرة الألوان.",
  "animations.preset.ambientGlow.title": "وهج الشفق القطبي الهادئ",
  "animations.preset.colorShift.badge": "تفاعل بصري فائق",
  "animations.preset.colorShift.desc": "تحول لوني تدريجي سلس عبر ألوان نمط QR باستخدام Framer Motion.",
  "animations.preset.colorShift.title": "التحول اللوني الكوني",
  "animations.preset.gentleRotate.badge": "حركة جذابة",
  "animations.preset.gentleRotate.desc": "دوران مداري هادئ ومستمر يحافظ على ثبات العناصر المركزية وسهولة مسحها.",
  "animations.preset.gentleRotate.title": "دوران الجاذبية المداري",
  "animations.preset.none.badge": "كلاسيكي ثابت",
  "animations.preset.none.desc": "تصميم قياسي عالي الأداء مع تخصيص المظهر دون أي تأثيرات حركية.",
  "animations.preset.none.title": "لوحة تصميم ثابتة",
  "animations.preset.pulse.badge": "حركة نابضة ملموسة",
  "animations.preset.pulse.desc": "نبضات هادئة مع تمدد الظلال الاحترافية لجذب انتباه المستخدم فوراً.",
  "animations.preset.pulse.title": "حركة التنفس والتكبير الهادئ",
  "animations.readyResolution": "دقة جاهزة للتصدير",
  "animations.scanConversion": "معدل تحويل المسح",
  "animations.secondsCount": "{speed} ثانية",
  "animations.smoothLoop": "دورة سلسة متكررة (30 ثانية)"
};

let count = 0;
for (const [key, value] of Object.entries(batch1)) {
  ar[key] = value;
  count++;
}

fs.writeFileSync(arPath, JSON.stringify(ar, null, 2), 'utf8');
console.log(`Successfully updated batch 1 (${count} keys) in ar.json.`);
