const fs = require('fs');
const path = require('path');

const arPath = path.join(__dirname, '../src/locales/ar.json');
const ar = JSON.parse(fs.readFileSync(arPath, 'utf8'));

const translations = {
  // templates
  "templates.ariaBreadcrumb": "مسار التصفح",
  "templates.authorityLiterature": "المراجع والمؤلفات المعتمدة",
  "templates.authorityOverview": "نظرة عامة على المعايير والمواصفات",
  "templates.bestPractices": "أفضل الممارسات والتوصيات",
  "templates.brandName": "FreeQRBarcodes.com",
  "templates.commonMistakes": "الأخطاء الشائعة في التصميم",
  "templates.ctaDescription": "استخدم هذا القالب وابدأ في تخصيص ألوانه وشعاره مجاناً بالكامل.",
  "templates.ctaTitle": "جاهز لتخصيص هذا القالب؟",
  "templates.customizeButton": "تخصيص هذا القالب الآن",
  "templates.description": "مكتبة شاملة من قوالب رموز QR المصممة باحترافية لتناسب كافة الأنشطة التجارية والمناسبات.",
  "templates.editorialNotes": "ملاحظات فريق التحرير والتصميم",
  "templates.emptyCategory": "لا توجد قوالب متوفرة في هذا التصنيف حالياً.",
  "templates.faqSection": "الأسئلة الشائعة حول القالب",
  "templates.filterAll": "جميع القوالب",
  "templates.geometricPattern": "النمط الهندسي للنقاط",
  "templates.guideStep1": "اختر القالب الأنسب لنشاطك من القائمة.",
  "templates.guideStep2": "عدل الألوان وارفع شعارك في المركز.",
  "templates.guideStep3": "حمل التصميم فوراً بصيغة SVG أو PNG.",
  "templates.heroBadge": "قوالب احترافية جاهزة",
  "templates.heroSubtitle": "قوالب تصميم جاهزة ومختبرة لضمان أعلى تباين وقابلية قراءة ممتازة.",
  "templates.heroTitle": "مكتبة قوالب رموز QR الاحترافية",
  "templates.howToUse": "كيفية استخدام وتخصيص القوالب",
  "templates.industryBadge": "قالب معتمد للقطاع",
  "templates.keyMetrics": "المؤشرات والمقاييس الفنية",
  "templates.lastModified": "آخر تحديث للقالب:",
  "templates.metaDescription": "استكشف مئات قوالب رموز QR الجاهزة والمجانية المصممة لبطاقات الأعمال والمطاعم والفعاليات في FreeQRBarcodes.com.",
  "templates.metaTitle": "قوالب رموز QR احترافية ومجانية | FreeQRBarcodes.com",
  "templates.overview": "نظرة عامة على مواصفات القالب",
  "templates.popularDesigns": "التصاميم الأكثر استخداماً",
  "templates.previewModal": "معاينة تفاصيل القالب",
  "templates.primaryUseCase": "حالة الاستخدام الأساسية",
  "templates.readGuide": "قراءة دليل التصميم",
  "templates.recommendedEcc": "مستوى تصحيح الأخطاء الموصى به: {{ecc}}",
  "templates.relatedDesigns": "قوالب وتصميمات مشابهة",
  "templates.resetFilters": "إعادة تعيين عوامل التصفية",
  "templates.scannabilityScore": "مؤشر سهولة المسح: 100%",
  "templates.searchPlaceholder": "ابحث في قوالب التصميم...",
  "templates.seeMore": "عرض المزيد من القوالب",
  "templates.selectCategory": "اختر فئة القالب",
  "templates.styleModern": "طراز عصري وحديث",
  "templates.tableOfContents": "جدول المحتويات",
  "templates.tags": "الوسوم والتصنيفات:",
  "templates.title": "قوالب رموز QR الجاهزة",
  "templates.useTemplate": "استخدام القالب",
  "templates.verifiedStandard": "مطابق لمعايير ISO/IEC 18004",

  // templatesHub
  "templatesHub.allCategories": "جميع الفئات",
  "templatesHub.backButton": "العودة إلى استوديو التصميم",
  "templatesHub.badge": "هياكل وقوالب تصميم معدة يدوياً",
  "templatesHub.clearFilter": "مسح التصفية",
  "templatesHub.customizeBtn": "تخصيص هذا القالب",
  "templatesHub.desc": "استعرض مجموعة واسعة من قوالب رموز QR الجاهزة والمصممة هندسياً لضمان أعلى نسب المسح والتباين.",
  "templatesHub.filterCategory": "تصفية حسب الفئة",
  "templatesHub.heroSubtitle": "قوالب جاهزة تلائم الهويات البصرية والشركات والمطاعم والفعاليات.",
  "templatesHub.heroTitle": "مركز قوالب رموز QR الاحترافية",
  "templatesHub.noResults": "لم نتمكن من العثور على قوالب تطابق خيارات البحث الحالية.",
  "templatesHub.searchPlaceholder": "ابحث بالاسم أو الفئة أو اللون...",
  "templatesHub.title": "مركز قوالب التصميم الجاهزة",

  // templatesTab
  "templatesTab.applyBtn": "تطبيق إعدادات القالب",
  "templatesTab.applyPresetBtn": "تطبيق القالب المختار",
  "templatesTab.bespokeArt": "تصميم فني وإبداعي",
  "templatesTab.corporateStandard": "النمط المؤسسي القياسي",
  "templatesTab.desc": "اختر من تصنيفات القوالب المصممة باحتراف لتعديل الألوان والعيون والشعارات وأشكال الإطارات فوراً.",
  "templatesTab.minimalist": "النمط البسيط الهادئ",
  "templatesTab.vibrant": "ألوان حيوية وجريئة",

  // trust
  "trust.aboutP1": "يمثل موقع FreeQRBarcodes.com الجيل الجديد لأنظمة الروابط التلامسية وتوزيع متجهات الباركود الثابتة. نحن نلغي تماماً جدران الدفع والاشتراكات الإجبارية والخوادم البطيئة وأنظمة التتبع غير الضرورية المرتبطة عادةً بإنشاء الباركود.",
  "trust.aboutP2": "نحن نؤمن بأن أدوات توليد الباركود الأساسية يجب أن تكون مفتوحة، ومجانية للجميع، وفائقة السرعة، ومبنية على معايير خصوصية صارمة تعالج البيانات محلياً داخل جهاز المستخدم دون إرسالها لأي طرف ثالث.",
  "trust.aboutP3Brand": "مجموعة iSolutions الرقمية",
  "trust.aboutP3Prefix": "بدعم ورعاية من ",
  "trust.aboutP3Suffix": "، نلتزم بإبقاء الوصول مفتوحاً، وآمناً، وسريعاً. وإلى جانب الأدوات المفتوحة، نقوم بتطوير قوالب وتكاملات مؤسسية متخصصة تلائم حملات الطباعة المعقدة مثل تتبع الأصول، واللافتات، ونقاط الاتصال المحلية.",
  "trust.aboutP3_1": "بدعم ورعاية من ",
  "trust.aboutP3_2": "، نحن ملتزمون بالحفاظ على تجربة مستخدم مفتوحة ومجانية للأبد.",
  "trust.aboutP4": "تخضع كافة الأدوات والتحديثات لدينا لاختبارات دورية صارمة للتأكد من توافقها التام مع ماسحات الكاميرا القياسية وأنظمة القراءة الصناعية.",
  "trust.aboutTitle": "من نحن ورسالتنا الهندسية",
  "trust.academicReference": "المراجع الأكاديمية والمواصفات القياسية",
  "trust.accessibilityP1": "نلتزم بتوفير واجهات مستخدم ميسرة ومتوافقة مع معايير إمكانية الوصول العالمية (WCAG 2.1 AA) لضمان سهولة الاستخدام لكافة الأفراد.",
  "trust.accessibilityTitle": "إمكانية الوصول والشمولية الرقمية",
  "trust.advisoryBoard": "المجلس الاستشاري الهندسي والتقني",
  "trust.annualScans": "أكثر من 100 مليون عملية مسح ناجحة سنوياً",
  "trust.auditCertification": "شهادات التدقيق والأمان",
  "trust.authorBio": "فريق هندسي متخصص في معايير الباركود، وهندسة الأنظمة الموزعة، وتأمين البنى التحتية السحابية.",
  "trust.authorTitle": "هيئة التحرير والتدقيق التقني في FreeQRBarcodes.com",
  "trust.backToStudio": "العودة إلى استوديو الإنشاء",
  "trust.badge": "مركز الثقة والأمان والنزاهة الهندسية",
  "trust.careersP1": "نحن نبحث دائماً عن مهندسين ومصممين ومترجمين شغوفين للانضمام إلى فريقنا وبناء مستقبل الأدوات الرقمية المفتوحة.",
  "trust.careersTitle": "الوظائف وفرص العمل",
  "trust.cert1Title": "معيار ISO/IEC 18004 المعتمد",
  "trust.cert2Title": "الامتثال لمعايير الخصوصية الأوروبية (GDPR)",
  "trust.cert3Title": "معايير سهولة الوصول WCAG 2.1 AA",
  "trust.certificationsTitle": "الاعتمادات والمعايير المطبقة",
  "trust.changelogP1": "سجل كامل وتفصيلي بكافة التحديثات والميزات والتحسينات المضافة للمنصة مع تواريخ الإصدارات.",
  "trust.changelogTitle": "سجل التحديثات والإصدارات",
  "trust.communityP1": "انضم إلى مجتمعنا من المطورين والمصممين لتبادل الخبرات والمساهمة في تطوير أفضل أدوات الباركود.",
  "trust.communityTitle": "المجتمع والابتكار المفتوح",
  "trust.complianceDesc": "نلتزم بأعلى معايير حماية البيانات والخصوصية العالمية لضمان سلامة وأمان مستخدمينا في كل مكان.",
  "trust.complianceTitle": "الامتثال والضوابط التنظيمية",
  "trust.contactDesc": "فريقنا الهندسي جاهز للرد على كافة استفساراتكم التقنية واقتراحاتكم لتطوير المنصة.",
  "trust.contactEmail": "الدعم الفني: support@freeqrbarcodes.com",
  "trust.contactTitle": "اتصل بنا وتواصل معنا",
  "trust.dataProcessingP1": "تحدد هذه الاتفاقية التزاماتنا الصارمة بمعالجة البيانات موضعياً داخل المتصفح وعدم تخزين أو بيع أي بيانات شخصية تخص المستخدمين.",
  "trust.dataProcessingTitle": "اتفاقية ومعايير معالجة البيانات",
  "trust.editorialPolicyP1": "تخضع كافة الأدلة والمقالات الفنية على منصتنا لتدقيق هندسي دقيق ومراجعة أقران مستقلة لضمان صحة المعلومات ودقتها.",
  "trust.editorialPolicyTitle": "السياسة التحريرية ومراجعة الأقران",
  "trust.eeatHeading": "الخبرة، المصداقية، والجدارة بالثقة (E-E-A-T)",
  "trust.engineeringStandards": "المعايير الهندسية والبرمجية",
  "trust.enterpriseSlaP1": "نقدم ضمانات تشغيلية واستقراراً بنسبة 99.99% لكافة الروابط والخدمات المؤسسية مع دعم فني متخصص.",
  "trust.enterpriseSlaTitle": "اتفاقية مستوى الخدمة للمؤسسات (SLA)",
  "trust.environmentalP1": "يساهم الانتقال للحلول الرقمية وتصحيح الطباعة المسبق في تقليل الهدر الورقي وحماية البيئة.",
  "trust.environmentalTitle": "الاستدامة والمسؤولية البيئية",
  "trust.faqP1": "إجابات وافية وشاملة على أكثر الأسئلة شيوعاً حول إنشاء الرموز، والطباعة، والأمان، والتراخيص.",
  "trust.faqTitle": "الأسئلة الشائعة والمساعدة",
  "trust.glossaryP1": "قاموس فني شامل يشرح كافة المصطلحات الهندسية المتعلقة بمصفوفات الباركود ونسب التباين وتصحيح الأخطاء.",
  "trust.glossaryTitle": "قاموس المصطلحات الفنية",
  "trust.governanceTitle": "الحوكمة والشفافية التشغيلية",
  "trust.guarantee1Desc": "جميع أدوات الإنشاء والتصدير الأساسية مجانية بالكامل ومفتوحة بدون أي اشتراكات خفية.",
  "trust.guarantee1Title": "مجاني للأبد 100%",
  "trust.guarantee2Desc": "تتم معالجة الرموز الثابتة محلياً في متصفحك دون إرسال محتواها إلى أي خوادم خارجية.",
  "trust.guarantee2Title": "أمان وخصوصية محلية تامة",
  "trust.guarantee3Desc": "تصدير متجهات SVG نقية قابلة للتكبير اللانهائي دون أي فقدان للجودة أو تشويش.",
  "trust.guarantee3Title": "جودة طباعية لا محدودة",
  "trust.guaranteesTitle": "ضمانات منصة FreeQRBarcodes.com الأساسية",
  "trust.heroSubtitle": "نحن ملتزمون بالشفافية المطلقة، والخصوصية المحلية، وتوفير أدوات مجانية عالية الدقة للجميع.",
  "trust.heroTitle": "مركز الثقة، الشفافية، والأمان الرقمي",
  "trust.leadershipBio": "يقود فريقنا نخبة من الخبراء في هندسة البرمجيات والأنظمة البصرية مع خبرات تتجاوز 15 عاماً في قطاع التقنية.",
  "trust.leadershipTitle": "القيادة الهندسية",
  "trust.mediaKitP1": "تنزيل الشعارات الرسمية وأصول الهوية البصرية ودليل استخدام العلامة التجارية لوسائل الإعلام.",
  "trust.mediaKitTitle": "الملف الإعلامي وأصول العلامة التجارية",
  "trust.missionDesc": "تمكين الملايين حول العالم من إنشاء وتخصيص واستخدام رموز QR والباركود الاحترافية مجاناً وبأعلى معايير الأمان والسرعة.",
  "trust.missionTitle": "مهمتنا ورؤيتنا المستقبلية",
  "trust.noTrackingP1": "نحن لا نتتبع نشاطك الشخصي ولا نقوم بتسجيل محتوى الرموز الثابتة التي تنشئها على المنصة.",
  "trust.noTrackingTitle": "سياسة عدم التتبع الصارمة",
  "trust.openStandardsP1": "نعتمد كلياً على المواصفات القياسية المفتوحة والمعتمدة من ISO و W3C دون استخدام أي تقنيات احتكارية مغلقة.",
  "trust.openStandardsTitle": "المعايير والبروتوكولات المفتوحة",
  "trust.peerReviewDesc": "يتم فحص وتدقيق كل خوارزمية وتحديث من قبل مراجعين مستقلين لضمان أعلى درجات الموثوقية.",
  "trust.peerReviewTitle": "نظام مراجعة الأقران المستقل",
  "trust.pressP1": "أحدث الأخبار والبيانات الصحفية والتقارير الصادرة عن منصة FreeQRBarcodes.com.",
  "trust.pressTitle": "المركز الصحفي والإعلامي",
  "trust.privacyP1": "نولي خصوصيتك الأهمية القصوى؛ تتم كافة عمليات توليد الرموز محلياً داخل جهازك دون رفع أي بيانات حساسة.",
  "trust.privacyTitle": "سياسة الخصوصية وحماية البيانات",
  "trust.qualityAssuranceP1": "نظام اختبارات آلي شامل يضمن سلامة الرموز وتوافقها مع 100% من أجهزة القراءة والماسحات الضوئية.",
  "trust.qualityAssuranceTitle": "ضمان الجودة والاختبار المستمر",
  "trust.researchP1": "أوراق بحثية ودراسات تطبيقية حول تحسين خوارزميات التعرف البصري واسترداد البيانات التالفة.",
  "trust.researchTitle": "الأبحاث والدراسات الهندسية",
  "trust.responsibleDisclosureP1": "إذا اكتشفت ثغرة أمنية، يرجى إبلاغ فريق الأمان لدينا فوراً للتعامل معها وحلها وفق برنامج المكافآت التقديرية.",
  "trust.responsibleDisclosureTitle": "برنامج الإفصاح الأمني المسؤول",
  "trust.securityP1": "تشفير شامل لجميع الاتصالات عبر TLS 1.3 مع تطبيق بروتوكولات الأمان الصارمة لحماية بيانات المستخدمين.",
  "trust.securityTitle": "الأمان وحماية البنية التحتية",
  "trust.serverUptime": "نسبة توافر الخوادم السحابية: 99.99%",
  "trust.standardsP1": "تلتزم منصتنا بجميع المعايير الدولية المنظمة لترميز الباركود ومصفوفات 2D بما يضمن توافقاً عالمياً لا مثيل له.",
  "trust.standardsTitle": "المعايير القياسية الدولية",
  "trust.termsP1": "شروط استخدام واضحة ومباشرة تمنحك الحق الكامل في استخدام وتوزيع الرموز المنشأة لأغراض شخصية وتجارية مجاناً.",
  "trust.termsTitle": "شروط الخدمة والترخيص",
  "trust.title": "مركز الثقة والأمان - FreeQRBarcodes.com",
  "trust.valuesDesc": "الشفافية، والخصوصية، والابتكار المفتوح، وإتاحة الأدوات الاحترافية للجميع دون حواجز مادية.",
  "trust.valuesTitle": "قيمنا ومبادئنا الجوهرية",
  "trust.verifiedUptime": "جاهزية واستقرار تشغيلي بنسبة 99.99%",
  "trust.zeroDataStorage": "معالجة محلية بدون تخزين سحابي إجباري"
};

let count = 0;
for (const [key, value] of Object.entries(translations)) {
  ar[key] = value;
  count++;
}

fs.writeFileSync(arPath, JSON.stringify(ar, null, 2), 'utf8');
console.log(`Updated Group 5 translations (${count} keys) in ar.json.`);
