const fs = require("fs");
const hi = JSON.parse(fs.readFileSync("src/locales/hi.json", "utf8"));

// Comprehensive English word & phrase mapping to Hindi
const WORD_MAP = {
  // Common small connector/stop words
  "with": "के साथ",
  "or": "या",
  "in": "में",
  "our": "हमारा",
  "on": "पर",
  "of": "का",
  "by": "द्वारा",
  "is": "है",
  "we": "हम",
  "are": "हैं",
  "can": "सकते हैं",
  "you": "आप",
  "that": "जो",
  "this": "यह",
  "campaigns": "अभियान",
  "campaign": "अभियान",
  "directly": "सीधे",
  "instantly": "तुरंत",
  "from": "से",
  "up": "ऊपर",
  "destination": "गंतव्य",
  "clean": "स्वच्छ",
  "all": "सभी",
  "without": "के बिना",
  "as": "के रूप में",
  "professional": "पेशेवर",
  "using": "का उपयोग करके",
  "use": "उपयोग करें",
  "modern": "आधुनिक",
  "designed": "डिजाइन किया गया",
  "across": "भर में",
  "yes": "हाँ",
  "app": "ऐप",
  "into": "में",
  "be": "होना",
  "it": "यह",
  "optical": "ऑप्टिकल",
  "how": "कैसे",
  "printed": "मुद्रित",
  "guides": "गाइड",
  "guide": "गाइड",
  "suite": "सूट",
  "s": "सेकंड",
  "contactless": "संपर्करहित",
  "configurations": "कॉन्फ़िगरेशन",
  "configuration": "कॉन्फ़िगरेशन",
  "like": "जैसे",
  "redirection": "पुनर्निर्देशन",
  "logos": "लोगो",
  "logo": "लोगो",
  "smart": "स्मार्ट",
  "high": "उच्च",
  "resolution": "रिज़ॉल्यूशन",
  "performance": "प्रदर्शन",
  "fast": "तेज़",
  "easy": "आसान",
  "simple": "सरल",
  "secure": "सुरक्षित",
  "security": "सुरक्षा",
  "dynamic": "डायनेमिक",
  "static": "स्टैटिक",
  "custom": "कस्टम",
  "vector": "वेक्टर",
  "files": "फ़ाइलें",
  "file": "फ़ाइल",
  "free": "निःशुल्क",
  "generator": "जनरेटर",
  "creation": "सृजन",
  "create": "बनाएं",
  "management": "प्रबंधन",
  "manage": "प्रबंधित करें",
  "tracking": "ट्रैकिंग",
  "analytics": "विश्लेषण",
  "dashboard": "डैशबोर्ड",
  "platform": "प्लेटफ़ॉर्म",
  "system": "सिस्टम",
  "service": "सेवा",
  "solution": "समाधान",
  "solutions": "समाधान",
  "enterprise": "एंटरप्राइज",
  "business": "व्यवसाय",
  "marketing": "मार्केटिंग",
  "digital": "डिजिटल",
  "mobile": "मोबाइल",
  "online": "ऑनलाइन",
  "offline": "ऑफ़लाइन",
  "print": "प्रिंट",
  "support": "सहायता",
  "tools": "उपकरण",
  "tool": "उपकरण",
  "type": "प्रकार",
  "types": "प्रकार",
  "value": "मान",
  "values": "मान",
  "data": "डेटा",
  "user": "उपयोगकर्ता",
  "users": "उपयोगकर्ता",
  "content": "सामग्री",
  "link": "लिंक",
  "links": "लिंक",
  "page": "पृष्ठ",
  "pages": "पृष्ठ",
  "code": "कोड",
  "codes": "कोड",
  "scan": "स्कैन",
  "scans": "स्कैन",
  "scanner": "स्कैनर",
  "image": "छवि",
  "images": "छवियां",
  "style": "शैली",
  "styles": "शैली",
  "color": "रंग",
  "colors": "रंग",
  "frame": "फ्रेम",
  "frames": "फ्रेम",
  "pattern": "पैटर्न",
  "patterns": "पैटर्न",
  "shape": "आकार",
  "shapes": "आकार",
  "border": "बॉडर",
  "borders": "बॉडर",
  "size": "आकार",
  "quality": "गुणवत्ता",
  "preview": "पूर्वावलोकन",
  "download": "डाउनलोड करें",
  "save": "सहेजें",
  "share": "साझा करें",
  "edit": "संपादित करें",
  "delete": "हटाएं",
  "copy": "कॉपी करें",
  "select": "चुनें",
  "option": "विकल्प",
  "options": "विकल्प",
  "setting": "सेटिंग",
  "settings": "सेटिंग्स",
  "info": "जानकारी",
  "help": "सहायता",
  "status": "स्थिति",
  "active": "सक्रिय",
  "enabled": "सक्षम",
  "disabled": "निष्क्रिय",
  "yes": "हाँ",
  "no": "नहीं",
  "an": "एक",
  "a": "एक",
  "the": "यह",
  "and": "और",
  "to": "को",
  "for": "के लिए",
  "at": "पर",
  "from": "से",
  "about": "के बारे में",
  "more": "अधिक",
  "less": "कम",
  "new": "नया",
  "top": "शीर्ष",
  "best": "सर्वश्रेष्ठ",
  "great": "महान",
  "good": "अच्छा",
  "better": "बेहतर",
  "full": "पूर्ण",
  "total": "कुल",
  "main": "मुख्य",
  "key": "प्रमुख",
  "first": "पहला",
  "last": "अंतिम",
  "next": "अगला",
  "back": "वापस",
  "close": "बंद करें",
  "open": "खोलें",
  "start": "प्रारंभ करें",
  "stop": "रोकें",
  "view": "देखें",
  "check": "जांचें",
  "click": "क्लिक करें",
  "add": "जोड़ें",
  "remove": "हटाएं",
  "change": "बदलें",
  "update": "अपडेट करें",
  "load": "लोड करें",
  "send": "भेजें",
  "get": "प्राप्त करें",
  "find": "खोजें",
  "search": "खोजें",
  "show": "दिखाएं",
  "hide": "छिपाएं",
  "choose": "चुनें",
  "apply": "लागू करें",
  "cancel": "रद्द करें",
  "ok": "ठीक है",
  "done": "हो गया",
  "clear": "साफ़ करें",
  "reset": "रीसेट करें"
};

function translateMixedText(val) {
  if (typeof val !== "string") return val;
  let res = val;
  
  // Replace words in WORD_MAP
  for (const [eng, hin] of Object.entries(WORD_MAP)) {
    const regex = new RegExp("\\b" + eng + "\\b", "gi");
    res = res.replace(regex, hin);
  }
  
  return res;
}

let modified = 0;
for (const [k, v] of Object.entries(hi)) {
  const tr = translateMixedText(v);
  if (tr !== v) {
    hi[k] = tr;
    modified++;
  }
}

fs.writeFileSync("src/locales/hi.json", JSON.stringify(hi, null, 2), "utf8");
console.log("Translated words in", modified, "keys in hi.json!");
