const fs = require('fs');
const path = require('path');

const arPath = path.join(__dirname, '../src/locales/ar.json');
const ar = JSON.parse(fs.readFileSync(arPath, 'utf8'));

const translations = {
  // Auth
  "auth.createAccount": "إنشاء حساب جديد",
  "auth.emailAddress": "عنوان البريد الإلكتروني",
  "auth.failed": "فشل تسجيل الدخول. يرجى التحقق من صحة بيانات الاعتماد.",
  "auth.fullName": "الاسم الكامل",
  "auth.nameRequired": "الاسم مطلوب",
  "auth.secureCloudShield": "حماية سحابية مشفرة",
  "auth.securePassword": "كلمة المرور الآمنة",
  "auth.signInButton": "تسجيل الدخول",
  "auth.signInDesc": "سجل الدخول للوصول إلى تصميمات رموز QR المحفوظة والتحليلات.",
  "auth.signInTab": "تسجيل الدخول",
  "auth.signUpButton": "إنشاء الحساب",
  "auth.signUpDesc": "ابدأ الآن واحتفظ بسجلات وتصميمات لوحة تحكم رموز QR الخاصة بك.",
  "auth.signUpTab": "إنشاء حساب",
  "auth.storageInfo": "محرك تخزين آمن وسريع. جميع العمليات مشفرة ومحمية بالكامل.",
  "auth.welcomeBack": "مرحباً بعودتك",

  // Nav
  "nav.barcodeGeneratorTab": "منشئ الباركود",
  "nav.formTab": "منشئ النماذج",
  "nav.restaurantMenuTab": "قوائم المطاعم",
  "nav.digitalCardTab": "البطاقات الرقمية",
  "nav.pdfTab": "مشاركة PDF",
  "nav.bulkGeneratorTab": "الإنشاء بالجملة",
  "nav.aiVision": "رؤية الذكاء الاصطناعي (AI Vision)",
  "nav.analytics": "التحليلات والإحصائيات",
  "nav.batch": "المعالجة المجمعة",
  "nav.brandHub": "مركز العلامة التجارية",
  "nav.community": "المجتمع",
  "nav.crm": "إدارة جهات الاتصال (CRM)",
  "nav.dashboard": "لوحة التحكم",
  "nav.developer": "بوابة المطورين",
  "nav.docs": "التوثيق البرمجي",
  "nav.download": "تنزيل",
  "nav.dynamic": "رموز ديناميكية",
  "nav.enterprise": "حلول المؤسسات",
  "nav.features": "الميزات",
  "nav.feedback": "الملاحظات",
  "nav.generator": "منشئ الرموز",
  "nav.help": "المساعدة والدعم",
  "nav.home": "الرئيسية",
  "nav.integrations": "التكامل والربط",
  "nav.knowledge": "قاعدة المعرفة",
  "nav.pricing": "الأسعار (مجاني 100%)",
  "nav.privacy": "الخصوصية",
  "nav.profile": "الملف الشخصي",
  "nav.qrScanner": "قارئ رمز QR",
  "nav.roadmap": "خارطة الطريق",
  "nav.saved": "التصاميم المحفوظة",
  "nav.security": "الأمان والامتثال",
  "nav.settings": "الإعدادات",
  "nav.status": "حالة النظام",
  "nav.templates": "قوالب التصميم",

  // Tour
  "tour.back": "السابق",
  "tour.close": "إغلاق الجولة",
  "tour.complete": "إنهاء الجولة التعليمية",
  "tour.desc1": "اختر نوع المحتوى الذي تريد ترميزه: رابط موقع، شبكة واي فاي، بطاقة عمل رقمية، بريد إلكتروني والمزيد.",
  "tour.desc2": "خصص أشكال النقاط وزوايا الرمز والتدرجات اللونية لتناسب هويتك البصرية بدقة.",
  "tour.desc3": "ارفع شعار علامتك التجارية في المنتصف مع المحافظة على معايير تصحيح الأخطاء لسهولة المسح.",
  "tour.desc4": "صدر رمز QR بصيغة SVG المتجهة فائقة النقاء للطباعة أو صيغة PNG عالية الدقة فوراً وبشكل مجاني.",
  "tour.next": "التالي",
  "tour.skip": "تخطي",
  "tour.start": "بدء جولة سريعة",
  "tour.step1Title": "1. اختر نوع البيانات",
  "tour.step2Title": "2. خصص المظهر والألوان",
  "tour.step3Title": "3. أضف شعار مخصص",
  "tour.step4Title": "4. تنزيل عالي الدقة",

  // Status & Palette
  "status.active": "نشط وجاهز للعمل",
  "palette.title": "لوحات الألوان الموصى بها",
  "palette.subtitle": "اختر من مجموعات التناسق اللوني المختبرة لضمان تباين فائق وسهولة قراءة عبر جميع الكاميرات.",
  "palette.apply": "تطبيق اللوحة",
  "palette.brand": "ألوان العلامة التجارية",
  "palette.contrast": "نسبة التباين: {{ratio}}:1",
  "palette.custom": "لوحة مخصصة",
  "palette.dark": "النمط الداكن",
  "palette.light": "النمط الفاتح",
  "palette.monochrome": "أحادي اللون الكلاسيكي",
  "palette.modern": "ألوان عصرية وجريئة",
  "palette.nature": "درجات الطبيعة الهادئة",
  "palette.ocean": "درجات المحيط الزرقاء",
  "palette.sunset": "ألوان الغروب الدافئة",
  "palette.vintage": "النمط الكلاسيكي العتيق",

  // Mockup
  "mockup.badge": "معاينة واقعية للمطبوعات",
  "mockup.title": "محاكي المعاينة الفيزيائية المباشرة",
  "mockup.desc": "شاهد كيف يبدو رمز QR الخاص بك مطبوعاً على بطاقات العمل، واللافتات، وقوائم المطاعم، والملصقات الترويجية.",
  "mockup.viewLive": "عرض المعاينة المباشرة",
  "mockup.switchScene": "تبديل نموذج المعاينة",

  // KB & Knowledge
  "kb.badge": "قاعدة المعرفة التقنية",
  "kb.title": "مركز المعرفة والتوثيق المتخصص",
  "kb.desc": "أدلة هندسية ومقالات تفصيلية حول معايير ISO لرموز QR، وتصحيح الأخطاء، وحسابات التباين، والطباعة الاحترافية.",
  "kb.searchPlaceholder": "ابحث في المقالات والأدلة الفنية...",
  "kb.allCategories": "جميع الفئات",
  "kb.standards": "المعايير الدولية (ISO/IEC)",
  "kb.designTips": "نصائح التصميم والتباين",
  "kb.printingGuide": "دليل الطباعة والتحجيم",
  "kb.securityPrivacy": "الأمان والخصوصية المحلية",
  "kb.troubleshooting": "حل المشكلات الفنية",
  "kb.readMore": "قراءة المقال كاملاً",
  "kb.backToKnowledge": "العودة لمركز المعرفة",
  "kb.readingTime": "{{mins}} دقيقة قراءة",
  "kb.lastUpdated": "آخر تحديث: {{date}}",
  "kb.author": "بقلم الفريق الهندسي",
  "kb.relatedArticles": "مقالات ذات صلة",
  "kb.helpfulQuestion": "هل كان هذا المقال مفيداً لك؟",
  "kb.yes": "نعم، مفيد جداً",
  "kb.no": "يحتاج لتوضيح أكثر",
  "kb.feedbackThanks": "شكراً لملاحظاتك القيمة!",
  "kb.popularTopics": "المواضيع الأكثر قراءة",
  "kb.noResults": "لم يتم العثور على مقالات تطابق بحثك.",

  "knowledge.title": "أكاديمية المعرفة الفنية لرموز QR",
  "knowledge.subtitle": "مرجع شامل يغطي المعايير الهندسية، وحسابات المسافات الطباعية، وتحسين التباين، وأمان البيانات.",
  "knowledge.categoryAll": "الكل",
  "knowledge.categoryEngineering": "الهندسة والمعايير",
  "knowledge.categoryDesign": "التصميم والجماليات",
  "knowledge.categoryPrint": "الطباعة والإنتاج",
  "knowledge.categorySecurity": "الأمان والخصوصية",
  "knowledge.search": "ابحث في قاعدة المعرفة...",
  "knowledge.articleCount": "{{count}} مقالاً متخصصاً",
  "knowledge.readArticle": "قراءة المقال",
  "knowledge.tableOfContents": "جدول المحتويات",
  "knowledge.keyTakeaways": "النقاط الرئيسية المستفادة",
  "knowledge.authorRole": "خبير معايير الباركود والأنظمة البصرية",
  "knowledge.shareArticle": "مشاركة المقال",
  "knowledge.copyLink": "نسخ الرابط",
  "knowledge.copied": "تم نسخ الرابط! ✓",
  "knowledge.qrStandardsTitle": "معايير ISO/IEC 18004 لرموز QR",
  "knowledge.qrStandardsSummary": "نظرة متعمقة على المواصفات القياسية الدولية الحاكمة لترميز وتصحيح أخطاء مصفوفات QR ثنائية الأبعاد.",
  "knowledge.printResolutionTitle": "حسابات دقة الطباعة ومسافة المسح المثالية",
  "knowledge.printResolutionSummary": "المعادلات الرياضية لحساب الأبعاد الفيزيائية المناسبة للرموز لضمان قراءتها من أي مسافة دون عناء.",
  "knowledge.errorCorrectionTitle": "مستويات تصحيح الأخطاء ريد-سولومون (L, M, Q, H)",
  "knowledge.errorCorrectionSummary": "كيف يعمل الاسترداد الرياضي للبيانات التالفة وكيفية اختيار المستوى الأنسب عند إضافة شعار.",
  "knowledge.colorContrastTitle": "إرشادات التباين اللوني وتجنب أخطاء المسح",
  "knowledge.colorContrastSummary": "دراسة بصرية لنسب التباين المطلوبة ومعايير WCAG للألوان الأمامية والخلفية وتأثير التدرجات.",
  "knowledge.svgVsPngTitle": "مقارنة المتجهات SVG مقابل الصور النقطية PNG في الإنتاج",
  "knowledge.svgVsPngSummary": "لماذا تعد المتجهات الحسابية الخيار الأمثل للمطابع التجارية وتطبيقات الهوية البصرية الكبيرة.",
  "knowledge.wifiSecurityTitle": "تأمين بيانات شبكات الواي فاي عبر التشفير المحلي",
  "knowledge.wifiSecuritySummary": "كيف يتم تضمين بروتوكولات WPA2/WPA3 محلياً داخل المتصفح دون إرسال كلمة المرور لأي خادم خارجي.",
  "knowledge.vcardSpecsTitle": "معايير تنسيق بطاقات جهات الاتصال الرقمية (vCard 3.0)",
  "knowledge.vcardSpecsSummary": "الهيكل القياسي للبيانات المضمنة في بطاقات الهوية الرقمية لتوافق تام مع هواتف iOS و Android.",
  "knowledge.dynamicVsStaticTitle": "الفرق الجوهري بين الرموز الثابتة والديناميكية",
  "knowledge.dynamicVsStaticSummary": "مقارنة شاملة بين الرموز المضمنة مباشرة والروابط الوسيطة من حيث الأمان والمرونة والتحليلات.",
  "knowledge.scannabilityTitle": "أفضل الممارسات لمنع فشل مسح الرموز في البيئات الحقيقية",
  "knowledge.scannabilitySummary": "قائمة تحقق هندسية قبل إرسال ملفات التصميم للطباعة لضمان تجربة مستخدم سلسة وخالية من الأخطاء.",
  "knowledge.articleHelpful": "هل ساعدك هذا المقال؟",
  "knowledge.thankYou": "شكراً لتقييمك!",
  "knowledge.relatedGuides": "أدلة إرشادية ذات صلة",
  "knowledge.viewAllGuides": "استعراض كافة الأدلة الفنية",

  // i18n Dashboard & Verification Keys
  "i18n.activeKeyTracking": "تتبع المفاتيح النشطة",
  "i18n.activeLocalizers": "المترجمون والمدققون النشطون:",
  "i18n.alignment": "المحاذاة والاتجاه",
  "i18n.allSeverities": "جميع مستويات الخطورة",
  "i18n.arabic": "العربية",
  "i18n.backgroundWorkspace": "مساحة عمل الخلفية",
  "i18n.bgWorkspaceCanvas": "لوحة مساحة العمل الخلفية",
  "i18n.cacheBundles": "حزم التخزين المؤقت",
  "i18n.cacheCold": "بدء التشغيل البارد",
  "i18n.cacheHitRatio": "معدل الإصابة في الذاكرة المؤقتة",
  "i18n.cacheInitialized": "تمت التهيئة بنجاح",
  "i18n.cacheOptimal": "مثالي (تخزين مؤقت نشط)",
  "i18n.cacheStrategy": "استراتيجية التخزين المؤقت",
  "i18n.carouselDesc": "يجب أن تتحرك عناصر العرض الدوار من اليسار إلى اليمين في اللغات اللاتينية (LTR)، ومن اليمين إلى اليسار في العربية (RTL). انقر للتحقق.",
  "i18n.carouselTitle": "3. محاذاة العرض الدوار المتسلسل",
  "i18n.chinese": "الصينية",
  "i18n.close": "إغلاق",
  "i18n.coldStartup": "بدء التشغيل البارد",
  "i18n.complete": "مكتمل",
  "i18n.completeness": "نسبة اكتمال الترجمة",
  "i18n.completenessDesc": "تتبع تغطية المفاتيح المترجمة مقارنة بالملف المصدري الإنجليزي الأساسي.",
  "i18n.component": "المكون البرمجي",
  "i18n.context": "السياق والملاحظات",
  "i18n.contextLabel": "سياق الترجمة:",
  "i18n.contrast": "التباين اللوني",
  "i18n.copyKey": "نسخ اسم المفتاح",
  "i18n.copyTranslation": "نسخ النص المترجم",
  "i18n.dashboardDesc": "بيئة هندسية متكاملة لتدقيق وضمان جودة الترجمات العالمية وفحص اتجاهات الواجهة (RTL/LTR) في الوقت الفعلي.",
  "i18n.dashboardTitle": "لوحة تحكم تدويل النظام وضمان الجودة (i18n QA)",
  "i18n.dateTimeFormat": "تنسيق التاريخ والوقت",
  "i18n.debugging": "التصحيح وتتبع الأخطاء",
  "i18n.direction": "اتجاه النص",
  "i18n.drawerDesc": "تفتح الأدراج الجانبية من اليمين في واجهات RTL ومن اليسار في واجهات LTR.",
  "i18n.drawerTitle": "2. سلوك الدرج والألواح الجانبية",
  "i18n.english": "الإنجليزية",
  "i18n.error": "خطأ",
  "i18n.exportJson": "تصدير ملف JSON",
  "i18n.exportMissing": "تصدير المفاتيح المفقودة",
  "i18n.filterByLang": "تصفية حسب اللغة",
  "i18n.filterByStatus": "تصفية حسب الحالة",
  "i18n.french": "الفرنسية",
  "i18n.german": "الألمانية",
  "i18n.hindi": "الهندية",
  "i18n.icuFormatting": "تنسيق قوالب ICU والمتغيرات",
  "i18n.icuTest": "اختبار صيغ الجمع والمتغيرات",
  "i18n.indonesian": "الإندونيسية",
  "i18n.issuesFound": "{{count}} مشكلة مكتشفة",
  "i18n.italian": "الإيطالية",
  "i18n.japanese": "اليابانية",
  "i18n.key": "المفتاح البرمجي",
  "i18n.keySearch": "البحث عن مفتاح ترجمة...",
  "i18n.korean": "الكورية",
  "i18n.language": "اللغة",
  "i18n.layout": "تخطيط الواجهة",
  "i18n.livePreview": "المعاينة المباشرة للترجمة",
  "i18n.locale": "اللغة والمنطقة",
  "i18n.ltr": "من اليسار إلى اليمين (LTR)",
  "i18n.missing": "مفقود",
  "i18n.missingKeys": "المفاتيح غير المترجمة",
  "i18n.missingKeysDesc": "المفاتيح الموجودة في الملف الأساسي ولكنها تفتقر إلى ترجمة مكتملة في هذه اللغة.",
  "i18n.noIssues": "لا توجد أي مشكلات في الترجمة! جميع النصوص مطابقة ومتكاملة 100%.",
  "i18n.numberFormat": "تنسيق الأرقام والعملات",
  "i18n.optimal": "مثالي",
  "i18n.passed": "ناجح",
  "i18n.pending": "قيد المراجعة",
  "i18n.percentComplete": "{{percent}}% مكتمل",
  "i18n.pluralRules": "قواعد الجمع والتثنية",
  "i18n.portuguese": "البرتغالية",
  "i18n.productionReady": "جاهز للإنتاج والنشر",
  "i18n.qaChecklist": "قائمة تدقيق الجودة اللغوية",
  "i18n.qaSuite": "جناح اختبارات الجودة الدولية",
  "i18n.quickFilters": "عوامل التصفية السريعة",
  "i18n.refresh": "تحديث البيانات",
  "i18n.rtl": "من اليمين إلى اليسار (RTL)",
  "i18n.rtlCheckDesc": "التحقق من سلامة المحاذاة والتباعد وهوامش العناصر عند استخدام الواجهة العربية واللغات المشابهة.",
  "i18n.rtlCheckTitle": "1. فحص التوافق مع اتجاه RTL",
  "i18n.runAllTests": "تشغيل جميع اختبارات الجودة",
  "i18n.runValidation": "بدء تدقيق التوافق",
  "i18n.save": "حفظ الترجمة",
  "i18n.saved": "تم الحفظ بنجاح! ✓",
  "i18n.saving": "جارٍ الحفظ...",
  "i18n.searchKeys": "بحث في المفاتيح...",
  "i18n.selectLang": "اختر اللغة",
  "i18n.severity": "درجة الأهمية",
  "i18n.sourceText": "النص الأصلي (الإنجليزية)",
  "i18n.spanish": "الإسبانية",
  "i18n.status": "الحالة",
  "i18n.stringLength": "طول النص والتناسب مع الواجهة",
  "i18n.summary": "ملخص التدويل الشامل",
  "i18n.sync": "مزامنة المفاتيح",
  "i18n.syncSuccess": "تمت المزامنة بنجاح!",
  "i18n.systemHealthy": "النظام اللغوي مستقر ومتوافق بالكامل",
  "i18n.targetText": "النص المترجم",
  "i18n.testDynamicVars": "اختبار المتغيرات الديناميكية",
  "i18n.testPluralization": "اختبار صيغ الجمع والتثنية",
  "i18n.totalKeys": "إجمالي المفاتيح: {{count}}",
  "i18n.totalLanguages": "14 لغة عالمية مدعومة",
  "i18n.translated": "مترجم بالكامل",
  "i18n.translationProgress": "تقدم الترجمة اللغوية",
  "i18n.turkish": "التركية",
  "i18n.urdu": "الأردية",
  "i18n.validate": "تدقيق فوري",
  "i18n.validated": "تم التحقق والاعتماد",
  "i18n.validationPassed": "اجتازت جميع الاختبارات بنجاح!",
  "i18n.variables": "المتغيرات المحجوزة",
  "i18n.verify": "تحقق",
  "i18n.viewDiff": "عرض الفروقات",
  "i18n.warning": "تنبيه",
  "i18n.warningsFound": "{{count}} تنبيه للمراجعة",
  "i18n.zeroTrustLocale": "معالجة محلية بدون خوادم وسيطة",
  "i18n.testCases": "حالات الاختبار",
  "i18n.testRunner": "مشغل اختبارات التدويل",
  "i18n.testPassed": "اجتاز الاختبار",
  "i18n.testFailed": "فشل الاختبار",
  "i18n.benchmark": "مؤشرات سرعة التبديل بين اللغات",
  "i18n.latency": "زمن التبديل: {{ms}} مللي ثانية",
  "i18n.rtlMirroring": "انعكاس الواجهة في النمط العربي (RTL Mirroring)"
};

let count = 0;
for (const [key, value] of Object.entries(translations)) {
  if (ar[key] !== undefined) {
    ar[key] = value;
    count++;
  } else {
    // Check if key is in en.json
    ar[key] = value;
    count++;
  }
}

fs.writeFileSync(arPath, JSON.stringify(ar, null, 2), 'utf8');
console.log(`Updated Group 2 (${count} keys) in ar.json.`);
