const fs = require("fs");
const hi = JSON.parse(fs.readFileSync("src/locales/hi.json", "utf8"));
const en = JSON.parse(fs.readFileSync("src/locales/en.json", "utf8"));

const ALLOWED_EXACT = new Set([
  "QR", "PNG", "SVG", "PDF", "JPEG", "JPG", "WEBP", "EPS", "CSS", "HTML",
  "URL", "URI", "API", "WIFI", "WI-FI", "VCARD", "VCARDS", "MECARD", "EPC",
  "EAN", "UPC", "EAN-13", "EAN-8", "UPC-A", "UPC-E", "CODE128", "CODE39", "CODE",
  "ITF", "ITF-14", "MSI", "PLESSEY", "DATAMATRIX", "PDF417", "AZTEC", "CODABAR",
  "ID", "UUID", "OS", "IOS", "ANDROID", "GOOGLE", "APPLE", "WALLET", "SMS",
  "EMAIL", "GPS", "SKU", "ASCII", "ISO", "GS1", "FREEQRBARCODES.COM",
  "FREEQRGEN.PRO", "FREEQRGEN", "FREEQRBARCODES", "PRO", "COM", "SAAS", "AI",
  "WHATSAPP", "TWITTER", "FACEBOOK", "LINKEDIN", "INSTAGRAM", "G",
  "YOUTUBE", "TIKTOK", "ZOOM", "SKYPE", "TELEGRAM", "VIBER", "PAYPAL", "STRIPE",
  "SEPA", "IBAN", "BIC", "SWIFT", "JSON", "CSV", "XLSX", "ZIP", "HTTP", "HTTPS",
  "WWW", "A4", "A3", "A5", "EPSON", "ZEBRA", "DPI", "CMYK", "RGB", "TLS", "SQL", "POS",
  "A", "B", "C", "D", "E", "F", "Z", "X", "Y"
]);

// Large comprehensive translation map
const TRANSLATIONS = {
  "of": "का",
  "an": "एक",
  "a": "एक",
  "the": "यह",
  "in": "में",
  "on": "पर",
  "at": "पर",
  "by": "द्वारा",
  "for": "के लिए",
  "with": "के साथ",
  "about": "के बारे में",
  "to": "को",
  "from": "से",
  "or": "या",
  "and": "और",
  "is": "है",
  "are": "हैं",
  "was": "था",
  "were": "थे",
  "be": "होना",
  "been": "हुआ",
  "being": "हो रहा है",
  "have": "पास है",
  "has": "पास है",
  "had": "था",
  "do": "करें",
  "does": "करता है",
  "did": "किया",
  "will": "होगा",
  "would": "होगा",
  "should": "चाहिए",
  "can": "सकते हैं",
  "could": "सकते थे",
  "may": "सकता है",
  "might": "हो सकता है",
  "must": "जरूरी है",
  "instantly": "तुरंत",
  "drawing": "ड्राइंग",
  "framer": "फ्रेम-रेंडरर",
  "motion": "मोशन",
  "hyper": "हाइपर",
  "s": "सेकंड",
  "applying": "लागू करना",
  "micro": "माइक्रो",
  "maximizes": "अधिकतम करता है",
  "up": "ऊपर",
  "signage": "साइनबोर्ड",
  "television": "टेलीविज़न",
  "bumpers": "बंपर्स",
  "streams": "स्ट्रीम",
  "bio": "बायो",
  "widgets": "विजेट",
  "soft": "सॉफ्ट",
  "neon": "नियॉन",
  "pulsations": "स्पंदन",
  "paired": "युग्मित",
  "backdrops": "बैकड्रॉप",
  "aurora": "ऑरोरा",
  "ambient": "एमबीएंट",
  "glow": "चमक",
  "highly": "अत्यधिक",
  "engaged": "सक्रिय",
  "hue": "रंग",
  "transitions": "ट्रांज़िशन",
  "over": "ऊपर",
  "cosmic": "कॉस्मिक",
  "mesmerizing": "मंत्रमुग्ध करने वाला",
  "slow": "धीमा",
  "continuous": "सतत",
  "orbit": "कक्षा",
  "that": "जो",
  "keeps": "रखता है",
  "stabilized": "स्थिर",
  "gravitator": "गुरुत्वाकर्षण",
  "direct": "प्रत्यक्ष",
  "redirect": "पुनर्निर्देशन",
  "redirection": "पुनर्निर्देशन",
  "redirections": "पुनर्निर्देशन",
  "clean": "स्वच्छ",
  "our": "हमारा",
  "your": "आपका",
  "we": "हम",
  "you": "आप",
  "my": "मेरा",
  "he": "वह",
  "she": "वह",
  "they": "वे",
  "it": "यह",
  "this": "यह",
  "these": "ये",
  "those": "वे",
  "what": "क्या",
  "which": "कौन सा",
  "who": "कौन",
  "whom": "किसको",
  "where": "कहाँ",
  "when": "कब",
  "why": "क्यों",
  "how": "कैसे",
  "all": "सभी",
  "any": "कोई भी",
  "both": "दोनों",
  "each": "प्रत्येक",
  "few": "कुछ",
  "more": "अधिक",
  "most": "अधिकांश",
  "other": "अन्य",
  "some": "कुछ",
  "such": "ऐसा",
  "no": "नहीं",
  "nor": "न ही",
  "not": "नहीं",
  "only": "केवल",
  "own": "खुद का",
  "same": "समान",
  "so": "तो",
  "than": "से",
  "too": "भी",
  "very": "बहुत",
  "just": "अभी",
  "now": "अब",
  "then": "फिर",
  "there": "वहाँ",
  "here": "यहाँ",
  "out": "बाहर",
  "off": "बंद",
  "over": "ऊपर",
  "under": "नीचे",
  "again": "फिर से",
  "further": "आगे",
  "once": "एक बार",
  "during": "के दौरान",
  "before": "पहले",
  "after": "बाद में",
  "above": "ऊपर",
  "below": "नीचे",
  "through": "के माध्यम से",
  "between": "के बीच",
  "into": "में",
  "throughout": "भर में",
  "toward": "की ओर",
  "towards": "की ओर",
  "upon": "पर",
  "within": "के भीतर",
  "without": "के बिना",
  "across": "भर में",
  "against": "के खिलाफ",
  "among": "के बीच",
  "around": "चारों ओर",
  "behind": "पीछे",
  "beyond": "परे",
  "near": "पास",
  "off": "बंद"
};

function processText(text) {
  if (typeof text !== "string") return text;
  let res = text;
  
  // Replace words found in TRANSLATIONS
  for (const [eng, hin] of Object.entries(TRANSLATIONS)) {
    const regex = new RegExp("\\b" + eng + "\\b", "gi");
    res = res.replace(regex, hin);
  }
  
  return res;
}

let count = 0;
for (const [k, v] of Object.entries(hi)) {
  const tr = processText(v);
  if (tr !== v) {
    hi[k] = tr;
    count++;
  }
}

fs.writeFileSync("src/locales/hi.json", JSON.stringify(hi, null, 2), "utf8");
console.log("Updated", count, "keys in hi.json with translation dictionary!");
