import json

# Define the complete 80-key translations for all 13 locales

translations = {
    "ar": {
        "seo.landing.wifi-qr-generator.seoTitle": "مولد رموز QR لشبكات الواي فاي مجاناً | الاتصال دون كتابة كلمة المرور",
        "seo.landing.wifi-qr-generator.metaDescription": "أنشئ رموز QR مخصصة للواي فاي مجاناً. اسمح للضيوف بالمسح والاتصال بشبكتك المحلية دون الحاجة لكتابة كلمة المرور.",
        "seo.landing.wifi-qr-generator.keyword": "مولد رموز qr واي فاي مجاني",
        "seo.landing.wifi-qr-generator.h1": "مولد رموز QR لشبكات الواي فاي مجاناً",
        "seo.landing.wifi-qr-generator.intro.title": "اقتران فوري بالشبكة اللاسلكية عبر رمز QR ثابت",
        "seo.landing.wifi-qr-generator.intro.text1": "يعد الاتصال بالشبكات اللاسلكية عن طريق كتابة كلمات المرور الأبجدية الرقمية الطويلة أمراً بطيئاً ومعرضاً للأخطاء المطبعية. يجمع مولد رموز QR للواي فاي المجاني اسم شبكتك (SSID) وبروتوكول الأمان وكلمة المرور في سلسلة QR ثابتة قياسية (مثل WIFI:S:GuestLounge_5G;T:WPA;P:SamplePass789;H:false;;). عند مسحها بكاميرا هاتف ذكي متوافقة أو قارئ باركود، يمكن لأنظمة التشغيل والتطبيقات المدعومة تحليل البيانات وعرض مطالبة للانضمام إلى الشبكة.",
        "seo.landing.wifi-qr-generator.intro.text2": "نظراً لأن رموز QR الثابتة للواي فاي تخزن معلمات الشبكة الثابتة مباشرة داخل المصفوفة المرئية، فإن معالجة البيانات تتم بالكامل في ذاكرة العميل أثناء الإنشاء ومحلياً على جهاز المسح — دون إرسال أسماء الشبكات أو كلمات المرور إلى خوادمنا. لا يحتوي الرمز على مؤقت انتهاء صلاحية مدمج ويظل صالحاً طالما تطابقت بيانات جهاز التوجيه وظل الرسم المطبوع مقروءاً.",
        "seo.landing.wifi-qr-generator.intro.highlight": "تشفير ثابت من جانب العميل. يتم تخزين معلمات الشبكة الثابتة مباشرة في المصفوفة دون خوادم وسيطة.",
        "seo.landing.wifi-qr-generator.benefits.title": "الإمكانات الأساسية والمواصفات التقنية",
        "seo.landing.wifi-qr-generator.benefits.desc": "تعرف على بنية البيانات، وأنماط التشفير المدعومة، والخصائص التشغيلية لرموز QR الثابتة للواي فاي.",
        "seo.landing.wifi-qr-generator.benefits.items.0.title": "انضمام سلس لشبكة الضيوف",
        "seo.landing.wifi-qr-generator.benefits.items.0.desc": "يلغي الحاجة إلى الإدخال اليدوي لكلمات المرور وتجنب الالتباس في الحروف. تقوم الأجهزة وتطبيقات المسح المتوافقة بتحليل البيانات لعرض مطالبة الانضمام.",
        "seo.landing.wifi-qr-generator.benefits.items.1.title": "مخططات البروتوكول القياسية",
        "seo.landing.wifi-qr-generator.benefits.items.1.desc": "يدعم التنسيق القياسي لـ WPA/WPA2/WPA3 Personal (T:WPA)، وبروتوكول WEP القديم (T:WEP)، والشبكات المفتوحة بدون تشفير (T:nopass).",
        "seo.landing.wifi-qr-generator.benefits.items.2.title": "إنشاء محلي بالكامل وخصوصية تامة",
        "seo.landing.wifi-qr-generator.benefits.items.2.desc": "بيانات اعتماد الشبكة لا تغادر متصفحك أبداً. يتم حساب مصفوفة رمز QR محلياً في الذاكرة دون إرسال بيانات إلى أي خدمة خارجية.",
        "seo.landing.wifi-qr-generator.benefits.items.3.title": "تصميم مخصص وجودة طباعة متجهة",
        "seo.landing.wifi-qr-generator.benefits.items.3.desc": "خصص ألوان النقاط والخلفيات وعلامات الزوايا. قم بالتصدير بصيغ PNG أو SVG أو PDF عالية الدقة للطباعة.",
        "seo.landing.wifi-qr-generator.benefits.items.4.title": "بيانات ثابتة بدون انتهاء صلاحية",
        "seo.landing.wifi-qr-generator.benefits.items.4.desc": "تخزن رموز الواي فاي الثابتة نصوصاً غير قابلة للتغيير دون مؤقتات انتهاء صلاحية أو اعتماد على إعادة توجيه سحابية.",
        "seo.landing.wifi-qr-generator.features.title": "البنية التقنية والأمان وتوافق الأجهزة",
        "seo.landing.wifi-qr-generator.features.desc": "اعتبارات تقنية حول أذونات الماسح الضوئي وقابلية قراءة البيانات ومعايير التشفير.",
        "seo.landing.wifi-qr-generator.features.items.0.title": "مطالبات الاتصال المعتمدة على الجهاز والتطبيق",
        "seo.landing.wifi-qr-generator.features.items.0.desc": "تعرض تطبيقات الكاميرا وأنظمة التشغيل الحديثة (مثل iOS وAndroid) شريط تأكيد قبل الاتصال. يختلف سلوك المطالبة الدقيق باختلاف الشركة المصنعة وأذونات التطبيق.",
        "seo.landing.wifi-qr-generator.features.items.1.title": "التوافق مع الوضع الانتقالي WPA2/WPA3",
        "seo.landing.wifi-qr-generator.features.items.1.desc": "يخرج المولد مخطط T:WPA القياسي المعترف به في شبكات WPA2-PSK والشبكات المشتركة WPA2/WPA3. التوافق الحصري مع WPA3-SAE فقط غير مضمون برمز T:WPA وحده.",
        "seo.landing.wifi-qr-generator.features.items.2.title": "علامة الشبكة المخفية (H:true)",
        "seo.landing.wifi-qr-generator.features.items.2.desc": "عند تكوين شبكة لا تبث اسمها، يضيف المولد H:true إلى البيانات (مثال: WIFI:S:LabSecureOps;T:WPA;P:HiddenKey456;H:true;;).",
        "seo.landing.wifi-qr-generator.features.items.3.title": "المصفوفة النصية مقابل التشفير اللاسلكي",
        "seo.landing.wifi-qr-generator.features.items.3.desc": "تخزن البيانات الاعتماد كنص صريح داخل المصفوفة، ويمكن قراءتها بواسطة أي ماسح. يعتمد التشفير اللاسلكي الفعلي بالكامل على إعدادات الموجه (WPA2/WPA3).",
        "seo.landing.wifi-qr-generator.features.items.4.title": "ثبات البيانات المطبوعة وعدم قابليتها للتعديل",
        "seo.landing.wifi-qr-generator.features.items.4.desc": "بيانات الواي فاي مدمجة مباشرة في المصفوفة المطبوعة. إذا غيرت كلمة مرور الموجه، يجب إنشاء رمز جديد وطباعته.",
        "seo.landing.wifi-qr-generator.faqs.0.q": "هل هذا المولد مجاني ومحلي وآمن؟",
        "seo.landing.wifi-qr-generator.faqs.0.a": "نعم. يتم حساب المصفوفة بالكامل داخل ذاكرة متصفحك. لا يتم إرسال اسم الشبكة أو كلمة المرور أو تخزينها على خوادمنا.",
        "seo.landing.wifi-qr-generator.faqs.1.q": "لماذا لا يتصل المسح تلقائياً على جميع الأجهزة؟",
        "seo.landing.wifi-qr-generator.faqs.1.a": "يعتمد سلوك الاتصال على إصدار نظام التشغيل وتطبيق الماسح. تعرض معظم الكاميرات مطالبة تأكيد قبل الانضمام، بينما قد تعرض بعض التطبيقات النص الخام فقط إذا لم تملك أذونات إعداد الشبكة.",
        "seo.landing.wifi-qr-generator.faqs.2.q": "هل رموز QR للواي فاي ثابتة أم ديناميكية؟",
        "seo.landing.wifi-qr-generator.faqs.2.a": "رموز QR للواي فاي ثابتة دائماً. يتم دمج البيانات مباشرة في نمط البكسل دون خادم وسيط أو انتهاء صلاحية، ويتطلب تغيير كلمة المرور إنشاء رمز جديد.",
        "seo.landing.wifi-qr-generator.faqs.3.q": "هل كلمة مرور الواي فاي محمية داخل رمز QR؟",
        "seo.landing.wifi-qr-generator.faqs.3.a": "لا. ترمّز الرموز القياسية البيانات كنص صريح غير مشفر (مثل WIFI:S:SSID;T:WPA;P:PASSWORD;;). يمكن لأي قارئ باركود قراءة كلمة المرور. يعتمد تشفير الاتصال اللاسلكي على إعدادات الموجه.",
        "seo.landing.wifi-qr-generator.faqs.4.q": "هل يعمل بروتوكول WPA3 على جميع الماسحات؟",
        "seo.landing.wifi-qr-generator.faqs.4.a": "يستخدم المولد صياغة T:WPA المدعومة على نطاق واسع في WPA2 والوضع الانتقالي WPA2/WPA3. قد يتطلب WPA3-SAE الخالص دعماً مخصصاً من البرنامج الثابت للجهاز.",
        "seo.landing.wifi-qr-generator.faqs.5.q": "هل سيعمل رمز QR مع الشبكات المخفية (Hidden SSID)؟",
        "seo.landing.wifi-qr-generator.faqs.5.a": "نعم، عند تفعيل خيار الشبكة المخفية، يتم تضمين الوسم H:true في البيانات لمساعدة الأجهزة المتوافقة على البحث عن الشبكة والاتصال بها.",
        "seo.landing.wifi-qr-generator.faqs.6.q": "هل يتحدث رمز QR الثابت إذا قمت بتغيير كلمة مرور جهاز التوجيه؟",
        "seo.landing.wifi-qr-generator.faqs.6.a": "لا. نظراً لأن البيانات مدمجة في النمط المرئي دون خادم توجيه، فإن تغيير إعدادات الموجه يبطل الرموز المطبوعة الحالية ويتطلب إنشاء رمز جديد.",
        "seo.landing.wifi-qr-generator.faqs.7.q": "هل يمكنني تخصيص مظهر وتصميم رمز الواي فاي؟",
        "seo.landing.wifi-qr-generator.faqs.7.a": "نعم، يمكنك تخصيص الألوان، والزوايا، وأنماط النقاط، وإضافة شعار مخصص، مع الحفاظ على مستويات تصحيح الأخطاء لضمان دقة القراءة.",
        "seo.landing.wifi-qr-generator.cta.title": "أنشئ رمز QR مخصصاً لشبكة الواي فاي الآن",
        "seo.landing.wifi-qr-generator.cta.subtitle": "أنشئ باركود شبكة لاسلكية ثابتاً ومخصصاً مع معالجة محلية بالكامل وتصدير متجه عالي الدقة.",
        "seo.landing.wifi-qr-generator.cta.buttonText": "إنشاء رمز واي فاي",
        "aeo.landing.wifi-qr-generator.quickDefinition": "رمز QR للواي فاي هو رمز مصفوفي ثنائي الأبعاد ثابت يرمز معلمات تكوين الشبكة اللاسلكية المحلية (SSID، بروتوكول الأمان، كلمة المرور، وعلامة الإخفاء الاختيارية) وفق مخطط WIFI URI القياسي.",
        "aeo.landing.wifi-qr-generator.aiSummary50": "رمز QR للواي فاي هو باركود 2D ثابت يخزن اسم الشبكة ونوع الأمان (WPA/WEP/بدون) وكلمة المرور. عند مسحه بأجهزة متوافقة، يحلل البرنامج البيانات ويعرض مطالبة للانضمام للشبكة المحلية.",
        "aeo.landing.wifi-qr-generator.whatIsIt": "رمز QR ثابت قياسي يرمز بيانات اعتماد الشبكة اللاسلكية مباشرة في مصفوفة بصرية وفق مواصفات بروتوكول WIFI:.",
        "aeo.landing.wifi-qr-generator.whenToUse": "يُستخدم لتسهيل انضمام الضيوف أو العملاء أو الموظفين إلى الشبكة اللاسلكية دون الحاجة إلى كتابة اسم الشبكة أو كلمة المرور المعقدة يدوياً.",
        "aeo.landing.wifi-qr-generator.benefits.0": "يسمح للأجهزة المتوافقة بقراءة البيانات وطلب الانضمام دون كتابة يدوية.",
        "aeo.landing.wifi-qr-generator.benefits.1": "يرمز بيانات الاعتماد محلياً باستخدام تنسيق WIFI: القياسي.",
        "aeo.landing.wifi-qr-generator.benefits.2": "يعالج البيانات بالكامل في ذاكرة العميل دون إرسال المفاتيح إلى الخادم.",
        "aeo.landing.wifi-qr-generator.benefits.3": "يصدر بتنسيقات متجهة عالية الدقة (SVG، PDF) وصور PNG للطباعة.",
        "aeo.landing.wifi-qr-generator.commonMistakes.0": "الاعتقاد بأن رمز QR يشفر كلمة المرور؛ البيانات مخزنة كنص صريح قابل للقراءة في المصفوفة.",
        "aeo.landing.wifi-qr-generator.commonMistakes.1": "توقع الاتصال التلقائي في الخلفية على كل جهاز دون مطالبات تأكيد من المستخدم.",
        "aeo.landing.wifi-qr-generator.commonMistakes.2": "افتراض أن شبكات WPA3-SAE الخالصة تعمل دائماً مع الماسحات القديمة التي تتوقع بنية WPA2.",
        "aeo.landing.wifi-qr-generator.commonMistakes.3": "نسيان أن تغيير كلمة مرور جهاز التوجيه يبطل جميع رموز QR الثابتة المطبوعة سابقاً.",
        "aeo.landing.wifi-qr-generator.bestPractices.0": "قم باختبار المسح باستخدام كاميرات iOS وAndroid الأصلية قبل طباعة اللافتات.",
        "aeo.landing.wifi-qr-generator.bestPractices.1": "تأكد من وجود تباين بصري عالٍ (وحدات داكنة على خلفية فاتحة) مع مستوى تصحيح أخطاء M أو Q.",
        "aeo.landing.wifi-qr-generator.bestPractices.2": "احتفظ باسم الشبكة وكلمة المرور موجزين قدر الإمكان للحفاظ على مصفوفة QR أقل كثافة وسهلة المسح.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.0": "رموز QR للواي فاي ثابتة وتخزن بيانات الاعتماد كنص صريح داخل المصفوفة ثنائية الأبعاد.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.1": "يعتمد سلوك مطالبة الاتصال على نظام تشغيل الجهاز وأذونات الماسح والشركة المصنعة.",
        "aeo.landing.wifi-qr-generator.keyTakeaways.2": "يتطلب تغيير إعدادات جهاز التوجيه إنشاء وطباعة رمز QR جديد.",
        "aeo.landing.wifi-qr-generator.faqs.0.q": "هل يتصل مسح رمز QR للواي فاي تلقائياً؟",
        "aeo.landing.wifi-qr-generator.faqs.0.a": "تعرض معظم الأجهزة الحديثة مطالبة تطلب من المستخدم تأكيد الانضمام إلى الشبكة. الاتصال التلقائي غير مضمون عالمياً.",
        "aeo.landing.wifi-qr-generator.faqs.1.q": "هل كلمة مرور الواي فاي مخفية عن الأشخاص الذين يمسحون الرمز؟",
        "aeo.landing.wifi-qr-generator.faqs.1.a": "لا. تخزن مصفوفة الباركود كلمة المرور كنص صريح. يمكن لأي شخص لديه قارئ باركود قراءة النص.",
        "aeo.landing.wifi-qr-generator.faqs.2.q": "ماذا يحدث إذا قمت بتغيير كلمة مرور الواي فاي؟",
        "aeo.landing.wifi-qr-generator.faqs.2.a": "لن يعمل رمز QR الثابت الحالي بعد ذلك. يجب عليك إنشاء وطباعة رمز QR جديد بالبيانات المحدثة.",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.entityType": "باركود مصفوفي ثنائي الأبعاد ثابت (متوافق مع ISO/IEC 18004)",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.protocolStandard": "مخطط WIFI URI (WIFI:S:...;T:...;P:...;H:...;;)",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.clientCompatibility": "iOS 11+، Android 10+، ومعظم تطبيقات الباركود الحديثة",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.primaryUseCase": "انضمام الضيوف والعملاء إلى الشبكة اللاسلكية دون كتابة كلمة المرور يدوياً",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.offlineCapability": "حساب المصفوفة بنسبة 100% من جانب العميل مع تحليل محلي"
    },
    "ur": {
        "seo.landing.wifi-qr-generator.seoTitle": "مفت وائی فائی کیو آر کوڈ جنریٹر | پاس ورڈ ٹائپ کیے بغیر کنیکٹ کریں",
        "seo.landing.wifi-qr-generator.metaDescription": "مفت وائی فائی کیو آر کوڈز بنائیں۔ مہمانوں کو پاس ورڈ ٹائپ کیے بغیر اسکین کر کے مقامی نیٹ ورک سے جڑنے کی سہولت دیں۔",
        "seo.landing.wifi-qr-generator.keyword": "مفت وائی فائی کیو آر کوڈ جنریٹر",
        "seo.landing.wifi-qr-generator.h1": "مفت وائی فائی کیو آر کوڈ جنریٹر",
        "seo.landing.wifi-qr-generator.intro.title": "اسٹیٹک کیو آر کوڈ کے ذریعے وائرلیس نیٹ ورک سے فوری رابطہ",
        "seo.landing.wifi-qr-generator.intro.text1": "طویل اور پیچیدہ پاس ورڈز دستی طور پر ٹائپ کرنا سست اور غلطیوں کا شکار عمل ہے۔ ہمارا مفت وائی فائی کیو آر کوڈ جنریٹر آپ کے نیٹ ورک کا نام (SSID)، سیکیورٹی پروٹوکول اور پاس ورڈ کو ایک معیاری اسٹیٹک اسٹرنگ میں مرتب کرتا ہے (جیسے WIFI:S:GuestLounge_5G;T:WPA;P:SamplePass789;H:false;;). جب ہم آہنگ اسمارٹ فون کیمرہ یا اسکینر سے اسکین کیا جائے تو معاون آپریٹنگ سسٹم نیٹ ورک میں شامل ہونے کا اشارہ دکھاتے ہیں۔",
        "seo.landing.wifi-qr-generator.intro.text2": "چونکہ اسٹیٹک وائی فائی کیو آر کوڈز نیٹ ورک کی معلومات براہ راست بصری میٹرکس میں محفوظ کرتے ہیں، اس لیے ڈیٹا کی پروسیسنگ مکمل طور پر براؤزر میموری میں ہوتی ہے اور ہمارے سرورز پر کوئی پاس ورڈ نہیں بھیجا جاتا۔ کوڈ کی کوئی میعاد ختم نہیں ہوتی۔",
        "seo.landing.wifi-qr-generator.intro.highlight": "کلائنٹ سائیڈ اسٹیٹک انکوڈنگ۔ نیٹ ورک پیرامیٹرز بغیر کسی درمیانی سرور کے براہ راست میٹرکس میں محفوظ ہوتے ہیں۔",
        "seo.landing.wifi-qr-generator.benefits.title": "بنیادی صلاحیتیں اور تکنیکی وضاحتیں",
        "seo.landing.wifi-qr-generator.benefits.desc": "اسٹیٹک وائی فائی کیو آر کوڈز کے پے لوڈ اسٹرکچر، اینکرپشن موڈز اور آپریشنل خصوصیات کو سمجھیں۔",
        "seo.landing.wifi-qr-generator.benefits.items.0.title": "مہمانوں کے لیے آسان نیٹ ورک کنکشن",
        "seo.landing.wifi-qr-generator.benefits.items.0.desc": "دستی پاس ورڈ انٹری کے بغیر ہم آہنگ آلات ڈیٹا پڑھ کر فوری کنیکٹ کا پرامپٹ دکھاتے ہیں۔",
        "seo.landing.wifi-qr-generator.benefits.items.1.title": "معیاری پروٹوکول اسکیمیں",
        "seo.landing.wifi-qr-generator.benefits.items.1.desc": "WPA/WPA2/WPA3 Personal (T:WPA)، پرانے WEP (T:WEP) اور غیر محفوظ اوپن نیٹ ورکس (T:nopass) کو سپورٹ کرتا ہے۔",
        "seo.landing.wifi-qr-generator.benefits.items.2.title": "مقامی کلائنٹ سائیڈ تخلیق اور مکمل پرائیویسی",
        "seo.landing.wifi-qr-generator.benefits.items.2.desc": "نیٹ ورک کی اسناد براؤزر سے باہر نہیں جاتیں۔ کیو آر میٹرکس مقامی میموری میں بنتی ہے۔",
        "seo.landing.wifi-qr-generator.benefits.items.3.title": "حسب ضرورت ڈیزائن اور ویکٹر پرنٹنگ",
        "seo.landing.wifi-qr-generator.benefits.items.3.desc": "رنگ، کونے اور پیٹرن حسب ضرورت بنائیں۔ ہائی ریزولوشن PNG، SVG ویکٹر یا PDF میں ایکسپورٹ کریں۔",
        "seo.landing.wifi-qr-generator.benefits.items.4.title": "بغیر میعاد ختم ہونے کا مستقل ڈیٹا",
        "seo.landing.wifi-qr-generator.benefits.items.4.desc": "اسٹیٹک کوڈز میں غیر متبدل ڈیٹا محفوظ ہوتا ہے جس کے لیے سرور یا کلاؤڈ کی ضرورت نہیں ہوتی۔",
        "seo.landing.wifi-qr-generator.features.title": "تکنیکی آرکیٹیکچر، سیکیورٹی اور آلات کی مطابقت",
        "seo.landing.wifi-qr-generator.features.desc": "اسکینر کی اجازتوں، پے لوڈ ریڈ ایبلٹی اور اینکرپشن کے معیار کے متعلق تکنیکی امور۔",
        "seo.landing.wifi-qr-generator.features.items.0.title": "ڈیوائس اور ایپ پر منحصر کنکشن پرامپٹس",
        "seo.landing.wifi-qr-generator.features.items.0.desc": "جدید iOS اور Android کیمرے نیٹ ورک سے جڑنے سے پہلے تصدیقی بینر دکھاتے ہیں۔ صحیح رویہ مینوفیکچرر اور اسکینر ایپ کی اجازتوں پر منحصر ہے۔",
        "seo.landing.wifi-qr-generator.features.items.1.title": "WPA2/WPA3 ٹرانزیشن نیٹ ورک کی مطابقت",
        "seo.landing.wifi-qr-generator.features.items.1.desc": "جنریٹر معیاری T:WPA اسکیمہ فراہم کرتا ہے جو WPA2-PSK اور مشترکہ نیٹ ورکس پر وسیع پیمانے پر کام کرتا ہے۔ صرف WPA3-SAE کی ضمانت نہیں ہے۔",
        "seo.landing.wifi-qr-generator.features.items.2.title": "پوشیدہ نیٹ ورک فلیگ (H:true)",
        "seo.landing.wifi-qr-generator.features.items.2.desc": "پوشیدہ نیٹ ورکس کے لیے جنریٹر پے لوڈ میں H:true کا اضافہ کرتا ہے تاکہ اسکینر اسے تلاش کر سکے۔",
        "seo.landing.wifi-qr-generator.features.items.3.title": "پلین ٹیکسٹ میٹرکس بمقابلہ وائرلیس اینکرپشن",
        "seo.landing.wifi-qr-generator.features.items.3.desc": "کیو آر کوڈ پے لوڈ پاس ورڈ کو سادہ غیر خفیہ متن کے طور پر اسٹور کرتا ہے۔ وائرلیس سیکیورٹی کا انحصار مکمل طور پر راؤٹر سیٹنگز پر ہوتا ہے۔",
        "seo.landing.wifi-qr-generator.features.items.4.title": "پرنٹ شدہ پے لوڈ کی غیر متبدل نوعیت",
        "seo.landing.wifi-qr-generator.features.items.4.desc": "وائی فائی اسناد میٹرکس کے اندر محفوظ ہوتی ہیں۔ راؤٹر پاس ورڈ تبدیل کرنے کی صورت میں نیا کوڈ بنانا ضروری ہے۔",
        "seo.landing.wifi-qr-generator.faqs.0.q": "کیا یہ مفت وائی فائی کیو آر کوڈ جنریٹر محفوظ اور پرائیویٹ ہے؟",
        "seo.landing.wifi-qr-generator.faqs.0.a": "جی ہاں، میٹرکس کی تیاری مکمل طور پر آپ کے مقامی براؤزر میں ہوتی ہے۔ نیٹ ورک کا نام اور پاس ورڈ سرور پر نہیں بھیجے جاتے۔",
        "seo.landing.wifi-qr-generator.faqs.1.q": "اسکین کرنے پر تمام آلات خودکار طریقے سے کیوں نہیں جڑتے؟",
        "seo.landing.wifi-qr-generator.faqs.1.a": "کنکشن کا انحصار آپریٹنگ سسٹم اور اسکینر ایپ کی اجازتوں پر ہوتا ہے۔ زیادہ تر کیمرہ ایپس پہلے کنیکٹ ہونے کی تصدیق مانگتی ہیں۔",
        "seo.landing.wifi-qr-generator.faqs.2.q": "کیا وائی فائی کیو آر کوڈز اسٹیٹک ہوتے ہیں یا ڈائنامک؟",
        "seo.landing.wifi-qr-generator.faqs.2.a": "وائی فائی کیو آر کوڈز مکمل طور پر اسٹیٹک ہوتے ہیں۔ ڈیٹا پکسل پیٹرن کے اندر محفوظ ہوتا ہے اور اس کی کوئی میعاد نہیں ہوتی۔",
        "seo.landing.wifi-qr-generator.faqs.3.q": "کیا وائی فائی پاس ورڈ کیو آر کوڈ کے اندر خفیہ رہتا ہے؟",
        "seo.landing.wifi-qr-generator.faqs.3.a": "نہیں۔ معیاری وائی فائی کیو آر کوڈز پاس ورڈ کو سادہ متن (جیسے WIFI:S:SSID;T:WPA;P:PASSWORD;;) میں اسٹور کرتے ہیں جسے کوئی بھی اسکینر پڑھ سکتا ہے۔",
        "seo.landing.wifi-qr-generator.faqs.4.q": "کیا WPA3 تمام موبائل اسکینرز پر کام کرتا ہے؟",
        "seo.landing.wifi-qr-generator.faqs.4.a": "جنریٹر معیاری T:WPA فارمیٹ دیتا ہے جو WPA2 اور ٹرانزیشن موڈ پر سپورٹڈ ہے۔ خالص WPA3-SAE آلات اور فرم ویئر پر منحصر ہے۔",
        "seo.landing.wifi-qr-generator.faqs.5.q": "کیا کیو آر کوڈ پوشیدہ (Hidden) SSID کے لیے کام کرے گا؟",
        "seo.landing.wifi-qr-generator.faqs.5.a": "جی ہاں، پوشیدہ نیٹ ورک کا انتخاب کرنے پر H:true شامل کیا جاتا ہے جس سے معاون ڈیوائسز اسے تلاش کرتی ہیں۔",
        "seo.landing.wifi-qr-generator.faqs.6.q": "کیا راؤٹر پاس ورڈ تبدیل کرنے سے پرانا کیو آر کوڈ کام کرے گا؟",
        "seo.landing.wifi-qr-generator.faqs.6.a": "نہیں۔ چونکہ ڈیٹا پرنٹ شدہ میٹرکس میں فکس ہوتا ہے، اس لیے پاس ورڈ تبدیل کرنے پر نیا کوڈ بنانا پڑے گا۔",
        "seo.landing.wifi-qr-generator.faqs.7.q": "کیا میں وائی فائی کیو آر کوڈ کا ڈیزائن تبدیل کر سکتا ہوں؟",
        "seo.landing.wifi-qr-generator.faqs.7.a": "جی ہاں، آپ رنگ، علامات، کونے اور لوگو تبدیل کر سکتے ہیں جبکہ اسکیننگ کی درستگی برقرار رہتی ہے۔",
        "seo.landing.wifi-qr-generator.cta.title": "ابھی اپنا حسب ضرورت وائی فائی کیو آر کوڈ بنائیں",
        "seo.landing.wifi-qr-generator.cta.subtitle": "کلائنٹ سائیڈ کیلکولیشن اور ویکٹر ایکسپورٹس کے ساتھ معیاری اسٹیٹک وائرلیس بارکوڈ بنائیں۔",
        "seo.landing.wifi-qr-generator.cta.buttonText": "وائی فائی کوڈ بنائیں",
        "aeo.landing.wifi-qr-generator.quickDefinition": "وائی فائی کیو آر کوڈ ایک اسٹیٹک 2D میٹرکس بارکوڈ ہے جو معیاری WIFI URI اسکیم کے تحت مقامی وائرلیس نیٹ ورک پیرامیٹرز (SSID، سیکیورٹی پروٹوکول، پاس ورڈ اور ہڈن فلیگ) کو انکوڈ کرتا ہے۔",
        "aeo.landing.wifi-qr-generator.aiSummary50": "وائی فائی کیو آر کوڈ ایک اسٹیٹک 2D بارکوڈ ہے جو SSID، سیکیورٹی کی قسم اور پاس ورڈ محفوظ کرتا ہے۔ ہم آہنگ آلات اسکین کرنے پر نیٹ ورک سے جڑنے کا پرامپٹ دکھاتے ہیں۔",
        "aeo.landing.wifi-qr-generator.whatIsIt": "ایک معیاری اسٹیٹک کیو آر کوڈ جو WIFI: پروٹوکول کے مطابق وائرلیس نیٹ ورک کی اسناد کو براہ راست بصری میٹرکس میں انکوڈ کرتا ہے۔",
        "aeo.landing.wifi-qr-generator.whenToUse": "مہمانوں، صارفین یا ملازمین کو دستی پاس ورڈ ٹائپ کروائے بغیر وائی فائی نیٹ ورک سے جوڑنے کے لیے استعمال کریں۔",
        "aeo.landing.wifi-qr-generator.benefits.0": "ہم آہنگ آلات کو بغیر ٹائپ کیے اسناد پڑھ کر جڑنے کی اجازت دیتا ہے۔",
        "aeo.landing.wifi-qr-generator.benefits.1": "معیاری WIFI: URI فارمیٹ کا استعمال کرتے ہوئے اسناد کو مقامی طور پر انکوڈ کرتا ہے۔",
        "aeo.landing.wifi-qr-generator.benefits.2": "سرور پر ڈیٹا بھیجے بغیر مکمل طور پر کلائنٹ میموری میں کام کرتا ہے۔",
        "aeo.landing.wifi-qr-generator.benefits.3": "پرنٹنگ کے لیے ویکٹر فارمیٹس (SVG، PDF) اور PNG میں ایکسپورٹ فراہم کرتا ہے۔",
        "aeo.landing.wifi-qr-generator.commonMistakes.0": "یہ سمجھنا کہ کیو آر کوڈ پاس ورڈ کو خفیہ کرتا ہے؛ اسناد سادہ متن کے طور پر محفوظ ہوتی ہیں۔",
        "aeo.landing.wifi-qr-generator.commonMistakes.1": "صارف کی تصدیق کے بغیر ہر ڈیوائس پر خودکار پس منظر کنکشن کی توقع رکھنا۔",
        "aeo.landing.wifi-qr-generator.commonMistakes.2": "یہ فرض کرنا کہ خالص WPA3-SAE نیٹ ورکس پرانے اسکینرز پر یکساں کام کرتے ہیں۔",
        "aeo.landing.wifi-qr-generator.commonMistakes.3": "یہ بھول جانا کہ راؤٹر کا پاس ورڈ تبدیل کرنے سے پرانے کوڈز ناکارہ ہو جاتے ہیں۔",
        "aeo.landing.wifi-qr-generator.bestPractices.0": "پرنٹ کرنے سے پہلے iOS اور Android کیمروں سے اسکین ٹیسٹ کریں۔",
        "aeo.landing.wifi-qr-generator.bestPractices.1": "مضبوط بصری تضاد (ہلکے پس منظر پر گہرے ماڈیولز) اور لیول M یا Q ایرر کریکشن کا استعمال کریں۔",
        "aeo.landing.wifi-qr-generator.bestPractices.2": "SSID اور پاس ورڈ کو مناسب حد تک مختصر رکھیں تاکہ کیو آر میٹرکس آسانی سے اسکین ہو سکے۔",
        "aeo.landing.wifi-qr-generator.keyTakeaways.0": "وائی فائی کیو آر کوڈز اسٹیٹک ہوتے ہیں اور 2D میٹرکس میں سادہ متن کے طور پر اسناد رکھتے ہیں۔",
        "aeo.landing.wifi-qr-generator.keyTakeaways.1": "کنکشن کا پرامپٹ ڈیوائس OS اور اسکینر ایپ کی اجازتوں پر منحصر ہے۔",
        "aeo.landing.wifi-qr-generator.keyTakeaways.2": "راؤٹر کی ترتیبات بدلنے پر نیا کیو آر کوڈ بنانا اور پرنٹ کرنا ضروری ہے۔",
        "aeo.landing.wifi-qr-generator.faqs.0.q": "کیا وائی فائی کیو آر کوڈ اسکین کرنے سے خودکار کنکشن ہو جاتا ہے؟",
        "aeo.landing.wifi-qr-generator.faqs.0.a": "زیادہ تر جدید آلات نیٹ ورک میں شامل ہونے کی تصدیق کے لیے ایک پرامپٹ دکھاتے ہیں۔",
        "aeo.landing.wifi-qr-generator.faqs.1.q": "کیا وائی فائی پاس ورڈ اسکین کرنے والوں سے پوشیدہ رہتا ہے؟",
        "aeo.landing.wifi-qr-generator.faqs.1.a": "نہیں۔ بارکوڈ میٹرکس پاس ورڈ کو سادہ متن میں محفوظ کرتا ہے جسے کوئی بھی اسکینر پڑھ سکتا ہے۔",
        "aeo.landing.wifi-qr-generator.faqs.2.q": "اگر میں وائی فائی پاس ورڈ تبدیل کروں تو کیا ہوگا؟",
        "aeo.landing.wifi-qr-generator.faqs.2.a": "موجودہ اسٹیٹک کیو آر کوڈ کام نہیں کرے گا۔ آپ کو نئی اسناد کے ساتھ نیا کیو آر کوڈ بنانا ہوگا۔",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.entityType": "اسٹیٹک 2D بارکوڈ (ISO/IEC 18004 کے مطابق)",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.protocolStandard": "WIFI URI اسکیم (WIFI:S:...;T:...;P:...;H:...;;)",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.clientCompatibility": "iOS 11+، Android 10+، اور زیادہ تر جدید بارکوڈ ایپس",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.primaryUseCase": "پاس ورڈ ٹائپ کیے بغیر مہمانوں کو وائرلیس نیٹ ورک سے جوڑنا",
        "aeo.landing.wifi-qr-generator.aiSummaryBox.offlineCapability": "100% کلائنٹ سائیڈ میٹرکس کیلکولیشن اور مقامی پروسیسنگ"
    }
}

# Let's save ar and ur to their respective json files
for loc in ["ar", "ur"]:
    with open(f"src/locales/{loc}.json", "r") as f:
        d = json.load(f)
    d.update(translations[loc])
    with open(f"src/locales/{loc}.json", "w") as f:
        json.dump(d, f, indent=2, ensure_ascii=False)
    print(f"Updated {loc}.json with complete 80 keys")
