name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_DEPLOY_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FREEQRGEN || secrets.FIREBASE_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - name: Deploy to Firebase Hosting
        if: ${{ env.FIREBASE_DEPLOY_SERVICE_ACCOUNT != '' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ env.FIREBASE_DEPLOY_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: gen-lang-client-0962876854
